### ISSUE TITLE
(property) NuxtImage: unknown

### ISSUE THREAD

**Issue by imcm7** [nuxt/image#1001]
If not import NuxtImage manually it is `(property) NuxtImage: unknown`.
But I not found how to import it? From what? From #app, #imports, #image, @nuxt/image.
Nothing not work. 

If I import it from @nuxt/image i get

```
Argument of type '{}' is not assignable to parameter of type 'ModuleOptions & Record<string, unknown>'.
  Type '{}' is missing the following properties from type 'ModuleOptions': inject, provider, presets, dir, and 7 more.ts(2345)
  ```

**Comment by Baroshem** [comment]
The component is auto imported so there is no need to import it additionally.

Closing.

Feel free to reopen if needed :)
