### ISSUE TITLE
Type imports in build are not transformed when bundling

### ISSUE THREAD

**Issue by DrJume** [nuxt/image#1008]
https://github.com/nuxt/image/blob/36285464fc10b4d6e7ad8bf166d89e6d09ff88df/src/runtime/utils/index.ts#L1

works in development but after bundling all types are combined into one types.d.ts:

![image](https://github.com/nuxt/image/assets/12785972/d060127c-9e60-4fb6-bc16-e0f6ebe89842)

which breaks type imports and causes the types to be `any`.

The above type import should be transformed to `import type { OperationGeneratorConfig } from '../../types'`

**Comment by Baroshem** [comment]
I think this issue was resolved.

Closing the issue but feel free to reopen if needed :)
