### ISSUE TITLE
Expose component types

### ISSUE THREAD

**Issue by rcerljenko** [nuxt/image#1013]
Hi,

I want to create a wrapper component around `<nuxt-img>` that can set some defaults that can be easily overridable like so:
```vue
<script lang="ts" setup>

import { imgProps } from '@nuxt/image/dist/runtime/components/nuxt-img'

const config = useRuntimeConfig()

const props = defineProps(imgProps)

</script>

<template>
	<nuxt-img :alt="config.public.appName" loading="lazy" decoding="async" v-bind="props" />
</template>
```

and then use that component in pages and other components:
```vue
<Image src="..." />
```

But it kinda feels wrong to import props like that... I expected to import types like so:
```ts
const props = defineProps<NuxtImgProps>()
```

Any ideas?

**Comment by billiewillie** [comment]
<script
  lang="ts"
  setup>
import type { NuxtImgProps } from '@base/modules/image/types/nuxt-image'

/*
 * Small wrapper over NuxtImg
 * Supports fallback to default img tag when nuxt-img was unable to optimize the image.
 * This could happen if an image file is corrupted (e.g. wrongly saved by an image editing software)
 * However, providing a fallback is always a good practise
 */

interface Emits {
  (e: 'error', data: any): void

  (e: 'load', data: any): void
}

interface Props extends /* @vue-ignore */ NuxtImgProps {
  src?: string
  fallback?: string
}

const emit = defineEmits<Emits>()

const props = defineProps<Props>()

const attrs = useAttrs()

const propsWithoutFallbackAndSrc = computed(() => {
  const { fallback, src, ...restProps } = props

  return { ...attrs, ...restProps }
})

const hasError = ref(false)

const handleError = (data: any) => {
  emit('error', data)
  hasError.value = true
}
</script>

<template>
  <NuxtImg
    v-if="!hasError || !fallback"
    v-bind="propsWithoutFallbackAndSrc"
    :src="src"
    @error="handleError"
    @load="emit('load', $event)" />
  <img
    v-else
    v-bind="propsWithoutFallbackAndSrc"
    :src="fallback"
    alt="" />
</template>

**Comment by Baroshem** [comment]
I believe that the types are exported already https://github.com/nuxt/image/blob/main/src/types/image.ts and also there is an example shown in the comment above

**Comment by thasmo** [comment]
> I believe that the types are exported already https://github.com/nuxt/image/blob/main/src/types/image.ts and also there is an example shown in the comment above

👋 Would it make sense to export them at the root?

```ts
import type { NuxtImgProps } from '@nuxt/image';
```

**Comment by thasmo** [comment]
Also, I'm not able to get this to work with the mentioned snippets.

**Comment by thasmo** [comment]
My current solution is this:

```ts
import type { ImageOptions, ImageSizes } from '@nuxt/image';

interface ImageProperties extends ImageOptions, ImageSizes {}

const properties = defineProps<ImageProperties>();
```

**Comment by leemethvenmtc** [comment]
> My current solution is this:
> 
> import type { ImageOptions, ImageSizes } from '@nuxt/image';
> 
> interface ImageProperties extends ImageOptions, ImageSizes {}
> 
> const properties = defineProps<ImageProperties>();

Does this actually do what the original snippet suggested? This seems to bring in provider types / modifiers, not actual NuxtImg props etc. 

The snippet suggested by @billiewillie no longer seems to be working, at least I can't find an easy solution to export the NuxtImg props from the module.

Combining attrs with props I need to add has helped though, I think it does most of the same thing just without full type support.

**Comment by thasmo** [comment]
@leemev91, indeed, my "solution" actually doesn't really work correctly, I figured.

> Combining attrs with props I need to add has helped though, I think it does most of the same thing just without full type support.

How does that look?

Thanks!

**Comment by leemev91** [comment]
> [@leemev91](https://github.com/leemev91), indeed, my "solution" actually doesn't really work correctly, I figured.
> 
> > Combining attrs with props I need to add has helped though, I think it does most of the same thing just without full type support.
> 
> How does that look like?
> 
> Thanks!

Sorry, just seeing this now

```
const props = defineProps<Props>()

const attrs = useAttrs()

const defaultPropsWithAttrs = computed(() => {
    return { ...attrs, ...props }
})
```

I then bind

```
    <NuxtImg
        v-bind="defaultPropsWithAttrs"
    />
```
On my wrapping component, I just pass NuxtImg props as you would usually, and this approach binds them to NuxtImg directly, and they behave the same way etc.

Thanks,
Lee
