### ISSUE TITLE
contentful provider, blur is an invalid url param

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/image#1055]
nuxt image lazy load then contentful provider  adds blur to url param,  which is an invalid param on contentful
https://images.ctfassets.net/-/-/cf95a9ac042aa58912b8c2f7d3906f83/Image_block_11.png?w=10&h=10&fm=webp&q=50&blur=3

this is on  "@nuxt/image": "1.0.0-rc.3",

**Comment by Baroshem** [comment]
Hey, does this occur in the newer versions of the module?
