### ISSUE TITLE
IPX: Throws Sharp Error Message when using Bun

### ISSUE THREAD

**Issue by kingofdreams777** [nuxt/image#1064]
# Steps to Reproduce:
1. Create new Nuxt Project
2. `bun add @nuxt/image`
3. Use `<NuxtImg src="/path_to_image_in_public_folder"`
4. `bun run dev -o`
5. Go to page that Image is supposed to be rendered on
6. Observe broken image link or just the alt text if you added any
7. Right-click broken image and choose `Open Image in New Tab` (I'm using Firefox)
8. Observe Error Message from sharp

### Expected Results
`<img>` tag renders correctly and displays the image linked in the folder

### Actual Results
Error message is displayed
```
{
  "error": {
    "message": "[500] [IPX_ERROR] \n
    Something went wrong installing the \"sharp\" module
    \n
    \nCannot find module '../build/Release/sharp-linux-x64.node'
    \nRequire stack:
    \n- </path_to_node_modules>/node_modules/sharp/lib/sharp.js
    \n- </path_to_node_modules>/node_modules/sharp/lib/constructor.js
    \n- </path_to_node_modules>/node_modules/sharp/lib/index.js
    \n
    \nPossible solutions:
    \n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"
    \n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"
    \n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
  }
}
```
---
### Additional Notes
I did try the possible solutions in the error message. No change in behavior

#### My system information
```
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      devtools, css, postcss, app, runtimeConfig, modules
- Runtime Modules:  @nuxt/image@1.0.0
- Build Modules:    -
```

**Comment by danielroe** [comment]
This can be tracked in https://github.com/oven-sh/bun/issues/4549.

**Comment by jakubkoje** [comment]
Sharp has been updated to hopefully support bun in the 0.33.0. @nuxt/image is not using this version.
