### ISSUE TITLE
How to remove the generated width and height attributes?

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/image#1069]
``` vue
<NuxtImg
  provider="xxx"
  :src="xxx"
  width="64"
  height="64"
/>
```

The final generated image has width and height attributes

``` html
<img 
  src="xxx" 
  onerror="xxx" 
  width="64" 
  height="64" 
  loading="lazy" 
  data-nuxt-img=""  
  srcset="xxx" 
/>
```

This will cause the css control of the width and height of the image to fail.

**Comment by Baroshem** [comment]
Hey, 

This is the expected behavior. I dont think we can do anything about it.

Closing as not planned.
