### ISSUE TITLE
Disable automatic f_auto and q_auto transformations for cloudinary

### ISSUE THREAD

**Issue by Bukunmikuti** [nuxt/image#1085]
When using NuxtImg with the Cloudinary provider, f_auto and q_auto are automatically applied to URLs. The documentation rightly stated this but is there a way to disable this behaviour?
I simply want the Cloudinary URL to be left as is with no added transformations.

```vue
<NuxtImg provider="cloudinary" 
src="/brand.png" alt="brand logo" 
placeholder="_nuxt/assets/images/placeholder.svg">
</NuxtImg>

<!-- Expected URL: https://res.cloudinary.com/<cloud-name>/image/upload/brand.logo -->
<!-- no automatic f_auto/q_auto -->
```

**Comment by Baroshem** [comment]
Hey,

These optimizations are meant to help. Could you explain why want to remove them?
