### ISSUE TITLE
Unknown provider unsplash

### ISSUE THREAD

**Issue by michealroberts** [nuxt/image#1089]
I'm slightly confused with the usage for the "unsplash" provider as documented here: [https://image.nuxt.com/providers/unsplash](https://image.nuxt.com/providers/unsplash).

My usage is as follows:

```vue
<NuxtImg
  provider="unsplash"
  src="/photo-1560260240-c6ef90a163a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  width="600"
  height="600"
  fit="cover"
  :modifiers="{ auto: 'format,compress' }"
/>
```

Yet, I see this error:

<img width="481" alt="Screenshot 2023-11-05 at 13 17 49" src="https://github.com/nuxt/image/assets/84131395/442d3e17-e835-400f-9646-3e4ddc37f25c">

---

Should I be using it with a baseURL for unsplash, with the imgix provider? The documentation doesn't make this quite clear ...

**Comment by michealroberts** [comment]
I see this also for the imgix proivder ...

**Comment by mathix420** [comment]
why did you close the issue, did you found a solution?
