### ISSUE TITLE
$fetch is not defined

### ISSUE THREAD

**Issue by parafeu** [nuxt/image#1108]
Hello,

After installing the @nuxt/image module on my project, this error appeared.
In server/utils, I created an instance of ofetch with a custom baseURL.

Thanks for your help

Reproduction: https://stackblitz.com/edit/nuxt-starter-xrmprj

**Comment by Baroshem** [comment]
Cannot reproduce on newer versions. 

Closing the issue.

Feel free to reopen if needed :)
