### ISSUE TITLE
static placeholder and seo

### ISSUE THREAD

**Issue by djixadin** [nuxt/image#1115]
this is more of a question and less so an issue.. when specifying static placeholder image from public folder as a placeholder the html that is generated has that image as a src for the image as the onMounted fires it changes the image source to a proper one.. its my understanding that this affects SEO poorly and is there some workaround for this ?

**Comment by bernhardberger** [comment]
you can do your own "placeholder" image:

```vue
<NuxtImg
src="your-source.jpg"
style="`background-image:url(${ $img(src: 'your-source.jpg', {w: 10, q: 70}) }`; background-repeat: no-repeat; background-size: cover" />
```

**Comment by Baroshem** [comment]
Thanks @bernhardberger for the answer.

Closing the issue.
