### ISSUE TITLE
Generating URLs with SEO suffixes using with Cloudinry

### ISSUE THREAD

**Issue by mohdlatif** [nuxt/image#1129]
How to set SEO suffix in Cloudinary Images
The setup from the docs looks pretty easy 

```
https://demo-res.cloudinary.com/image/upload/t8sn7wg4jd74j.jpg

The delivery URL with the suffix basketball-game added to the Public ID is:

https://demo-res.cloudinary.com/images/t8sn7wg4jd74j/basketball-game.jpg

```

1) Erasing `upload`
2) replace `image `with `images`
3) replace `image extension` with /<seo>.jpg 

Docs:
[Generating URLs with SEO suffixes using](https://cloudinary.com/documentation/advanced_url_delivery_options#dynamic_seo_suffixes)

How to configure Nuxt image to use SEO ? 

Thanks

**Comment by Baroshem** [comment]
Hey there,

I think there is no feature in Nuxt Image for that. However you can use Nuxt Seo module that should help to achieve better seo :)
