### ISSUE TITLE
Questions about NuxtImage on site deployed to Vercel

### ISSUE THREAD

**Issue by molul** [nuxt/image#1131]
Hi. I was using NuxtImage in a website deployed to Vercel (an illustrator portfolio which heavily relies on images for the content) but I had to switch to plain <img> tag because <NuxtImage> by default enables Vercel's image provider for optimization on a project deployed to Vercel, according to the docs. 

The problem with that is that it's a website with around 100 images in total (for now; it might be more in the future), so if the website had 10 people watching all the image galleries, it would reach the 1000/month limit of the hobby plan easily, and my customer doesn't want to pay $20/month for that, coming from a Wordpress website where hosting was $9/month.

Now a few questions:

1- Is it possible to disable Vercel's image provider and use self-hosted ipx instead on a Nuxt project deployed to Vercel?
2- If it was possible, would image optimization still be counted by Vercel?
3- I'm also considering using Contentful as the image provider, as I believe it has no image optimization limit. If I switched to it, can I just set it as the provider as specified in the docs (https://image.nuxt.com/providers/contentful) to avoid Vercel's provider or is Vercel mandatory no matter what provider you set?

Thanks a lot in advance :)

**Comment by DavidDeSloovere** [comment]
These questions are probably better suited in the Discussions section of the repo.

**Comment by Baroshem** [comment]
Hey there, I think you can try to force to use provider ipx to override automatically discovered image optimizer.
