### ISSUE TITLE
Allow setting dataURI as placeholder

### ISSUE THREAD

**Issue by hahagu** [nuxt/image#1134]
Allowing setting dataURI as a placeholder would allow custom implementations of placeholders.
This would partially solve the issue of using custom placeholder implementations for images, using things like blurhashes,
by allowing such to be loaded in via code on client side.

An alternative would be a pluggable system for generating such instead of `useImage()`.

**Comment by Baroshem** [comment]
Closing in favor of https://github.com/nuxt/image/issues/1307
