### ISSUE TITLE
dynamic src causes transitions to face to 0 opacity

### ISSUE THREAD

**Issue by songololo** [nuxt/image#114]
I am using a dynamic `src` for `nuxt-image`.

When dynamically changing the source image the image will change..., but then the transition will kick-in, which fades the image opacity to 0 (and the image is then not visible).

Is there a way to prevent the transition effects from running when changing out sources dynamically?

**Comment by songololo** [comment]
PS - at the moment a workaround for my case is to first change the source to `null`, then to change to the new source using `$nextTick()`.

**Comment by pkpowell** [comment]
I'm having similar problems with the css rules that come with lazy-loading.
The `transition: opacity 800ms` property seems to block the display of all images on a page the very first time the page is opened (actual loading time for all images + 800ms?). Subsequent loads are very fast. 
If I set `:lazy="false"` on all images the page loads normally.

**Comment by axel-verse** [comment]
Faced very similar bug. When lazy enabled, already loaded v-for generated images (I keep their filenames in content module) placed out of viewport become transparent when they appears in viewport. When lazy disabled, everything works just fine.
