### ISSUE TITLE
bug: Can't use variables in :imgAttrs in NuxtPicture

### ISSUE THREAD

**Issue by mctweb** [nuxt/image#1140]
If you provide a variable to the style or class attributes, then these do not update.

**Reproduction:**
https://stackblitz.com/edit/github-kgc1vh?file=app.vue

Example:

        <script setup lang="ts">
        const { y } = useWindowScroll();
        const changingValue = computed(() => {
          return y.value ? y.value / 2 : 50;
        });
        
        const style = computed(() => {
          return `padding-top: ${insetValue.value}px;`;
        });
        </script>

          <template>
            <div style="height: 200vh; position: relative">
              <div style="position: fixed; top: 0; right: 0">{{ style }}</div>
              <NuxtPicture src="https://placehold.co/600x400" :imgAttrs="{style: style  }"  />
            </div>
          </template>

**Comment by Baroshem** [comment]
Closing due to no traffic on this issue.

**Comment by Atulin** [comment]
Could you reopen this issue? I'm having the exact same problem
