### ISSUE TITLE
Does anyone use multiple densities? The images are huge

### ISSUE THREAD

**Issue by notflip** [nuxt/image#1146]
I'm wondering if anyone uses densities `x1 x2` or even with `x3`? 

When I've got an 800px width by 1000px height image, using `x2` has to download a 2000px image, which is pretty big in filesize, I can't imagine being able to get good pagespeed results when there's multiple of these on a webpage?

**Comment by bernhardberger** [comment]
That's the cost of having retina displays and wantint super duper sharp images..

**Comment by raphaelbernhart** [comment]
As @bernhardberger already mentioned, this decision is completely up to to you.

Current displays have `>=2x` densities which means you probably should ALSO use this higher pixel densities. You are right this of course costs more bandwidth.

But f.e. with the Google Page Speed Insights the emulated device (desktop) has a DPR of 1x so only the 1x ratio image should be served by nuxt/image. The emulated mobile device on the other hand uses 1.75 DPR, this probably ends up in a using of the 2x image which will be slower to load, thats true.

IMO a website should be be built on just always having the best performance, this is only one factor of a "good" website.

[image](https://github.com/nuxt/image/assets/48283236/4251a27f-5ca7-4030-b111-f844de10bb2b)
[image](https://github.com/nuxt/image/assets/48283236/da0f947e-aaca-433d-b8a2-658db39785c0)

@notflip Can we close this as IMO this is not a issue with the module?

**Comment by notflip** [comment]
@raphaelbernhart Thanks for the explanation, and yes I'll close this, since it's not an issue.
