### ISSUE TITLE
Not working on edge functions - Cannot resolve "node-fetch-native/native/proxy" externals are not allowed!

### ISSUE THREAD

**Issue by MickL** [nuxt/image#1168]
When deployed to Vercel Edge Functions I get the following error during build:

> [error] [nitro] Error: Cannot resolve "node-fetch-native/native/proxy" from "/vercel/path0/node_modules/giget/dist/index.mjs" and externals are not allowed!

I tried both `"@nuxt/image": "^1.1.0"` and `"@nuxt/image": "npm:@nuxt/image-edge@latest"`, both showing the same error.

It works when deployed normal.

**Comment by medaminefh** [comment]
facing the same error here, when deploying to vercel 
![Screenshot from 2024-02-28 22-40-20](https://github.com/nuxt/image/assets/37845480/83f349a0-1bd7-4c98-ad9c-8351abe02c50)
