### ISSUE TITLE
option to disable local cache

### ISSUE THREAD

**Issue by mostafa6765** [nuxt/image#117]
My website load image from CDN aws (CloudFront) . nuxt-image store all images inside the cache folder.

how much time does cache exist?  don't want to store image as cache because my all images size about 100gb+

~ Any suggestions or tips?

**Comment by pi0** [comment]
Hi @mostafa6765. Actually image module is not production ready yet in terms of API, defaults and documentation.

I would suggest either disabling cache or switch to a cloud provider option like Cloudinary for prod.

**Comment by mostafa6765** [comment]
this module is amazing but store image that is painful. my all image store on s3.

can you (@pi0)  suggest to me how to disable caching this module?

`cacheDir: '~~/node_modules/.cache/nuxt-image',` this module by default cache all images.

**Comment by pi0** [comment]
@mostafa6765 There is an `clearCache` but i'm afraid it is not possible now. Putting issue on pending until fixed.

**Comment by pi0** [comment]
fs cache in no longer used by ipx and image module
