### ISSUE TITLE
Static images with remote image

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/image#1175]
Hi,

Seem to be encountering some sort of bug. I would like to use nuxt image to optimise images both in public folder and remote (subdomain). 

Whilst in dev all works fine however in production nothing works. However when I go to website.com/image.png it works. 

The project is deployed on azure. 

Have included module. Image in nuxt config just has the subdomain included in domains and format of webp.

The error I get from local files is 404. And external files get 500. 

It is all set to ssr:true

Is this behaviour expected?? Have I missed something?

Thanks so much.

**Comment by moshetanzer** [comment]
Just did a bit more testing, doesnt seem to be working at all in production when using azure for deployment.

**Comment by moshetanzer** [comment]
After a drop more testing when i remove domains, all remote images work but not local images. get errro ipx 404 not found. Howver when i remove ipx from url (in browser) images is there. Is this repo maintained??

**Comment by januarfonti** [comment]
@moshetanzer did you resolved this issue? I've a same issue, so I've a 2 kinds of source image

1. Local image (public folder)
2. External url (defined in domains)
