### ISSUE TITLE
[Vue Warn] getCurrentInstance... - Custom provider - useRuntimeConfig()

### ISSUE THREAD

**Issue by or2e** [nuxt/image#1188]
After recent updates to vue.js, warning started to occur when using `useRuntimeConfig` hook in the custom image-provider.
Reproduction: https://stackblitz.com/edit/nuxt-image-swdizt?file=providers%2Fmy-provider.ts

`[Vue warn]: getCurrentInstance() called inside a computed getter. This is incorrect usage as computed getters are not guaranteed to be executed with an active component instance. If you are using a composable inside a computed getter, move it ouside to the setup scope.`

topic: https://github.com/vuejs/core/discussions/9974

**Comment by or2e** [comment]
Version [3.4.7](https://github.com/vuejs/core/blob/main/CHANGELOG.md#347-2024-01-09) has rolled back this behavior for now

**Comment by Baroshem** [comment]
Closing due to the comment above.
