### ISSUE TITLE
Hydration attribute mismatch

### ISSUE THREAD

**Issue by siimok** [nuxt/image#1190]
Using NuxtPicture gives an hydration error.

For reproduction:
1. >npx nuxi@latest init <project-name>
2.  run "npm install @nuxt/image" in project folder
3.  Add module to nuxt config "modules: ['@nuxt/image',]"
4. <nuxt-picture
       src="someimageurl/location"
      :img-attrs="{ width: '100%', height: '100%' }"
    ></nuxt-picture>

Next Nuxt and Vue version don't seem to solve the issue.

Link to a reproduction
https://stackblitz.com/edit/github-jcbjtc?file=components%2FExampleImage.vue

**Comment by or2e** [comment]
dup: https://github.com/nuxt/image/issues/1189

**Comment by Baroshem** [comment]
Closing as duplicate
