### ISSUE TITLE
Prevent image generation with IPX

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt/image#1195]
Is it possible to prevent the image generation when using `nuxt generate` and the IPX image provider? We host a standalone IPX version on a lambda and have an s3 with a redirection rule so the image only get's generated once. This would drastically improve the build time of static pages.

Thanks!

**Comment by Baroshem** [comment]
Hey there, I am not sure if that even makes sense. The whole idea of having this module is that it does the inage transformation/optimization by using IPX. If you dont need it as you have it hosted separately, then maybe a better approach would be to just use regular img tags?
