### ISSUE TITLE
Version 1.3.0 upgraded to 0.7.2?

### ISSUE THREAD

**Issue by dethdkn** [nuxt/image#1212]
Im just wondering if this is right 🤔, Every time I use pnpm up --latest it "upgrades" to 0.7.2
![Screenshot_1](https://github.com/nuxt/image/assets/106754824/ca0fb533-dbc9-4d40-9f35-eb6d75ac3ed9)

**Comment by danielroe** [comment]
This is now resolved! My apologies 🙏
