### ISSUE TITLE
How to share the various assets present within the Nuxt 3 project with other Nuxt 3 project in same root folder?

### ISSUE THREAD

**Issue by Aravinda93** [nuxt/image#1220]
I have a root folder which contains multiple `Nuxt 3` projects, with the following folder structure:
root
  --ProjectA
  --ProjectB

`ProjectB` extends `ProjectA` and can use all the components from `ProjectA` within `ProjectB`. This is working fine. However, I am unable to use the various images, styles and themes present within the `ProjectA/assets` and `ProjectB/public`.

Can someone please let me know how can I use the `ProjectA` assets and public folder elements within `ProjectB`?

Following is the `ProjectB/nuxt-config.ts` which is extending `components` from `ProjectA`:
```
  // auto import components
components: [
  {
    path: '~/components',
    pathPrefix: false,
  },
  {
    path: "../ProjectA/components",
    pathPrefix: false,
  },
],

extends: ["../ProjectA"],


  buildModules: [
    {
      handler: require('../ProjectA/nuxt.config').default,
      vue: {
        config: {
          assetDirs: [
            'assets',
            'public'
          ]
        }
      }
    }
  ],
```

What additional changes needs to be done to the config so I can directly use the images and public folder elements in ProjectB?

**Comment by Baroshem** [comment]
Hey, this seems to me like a perfect candidate for a Nuxt Layer 

https://nuxt.com/docs/getting-started/layers
