### ISSUE TITLE
Request module IPX does not provide an export named 'createIPXH3Handler'

### ISSUE THREAD

**Issue by TakCastel** [nuxt/image#1223]
I just installed this devDep:

```json
"@nuxt/image": "^1.3.0",
"ipx": "^1.0.0",
```

And I got this error when lauching `npm run dev` in a Nuxt 3 project:

```bash
✔ Nitro built in 3760 ms                                                                   nitro 11:54:25

[11:54:26]  ERROR  [worker reload] [worker init] The requested module 'file:/// (...) /node_modules/ipx/dist/index.mjs' does not provide an export named 'createIPXH3Handler'

  import { ipxFSStorage, ipxHttpStorage, createIPX, createIPXH3Handler } from 'node_modules/ipx/dist/index.mjs';
  ^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/ipx/dist/index.mjs' does not provide an export named 'createIPXH3Handler'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

ℹ Vite server warmed up in 5751ms                                                                11:54:26
ℹ Vite client warmed up in 7820ms
```

**Comment by gwynhokkers** [comment]
Having the same issue running generate. Using Nuxt v3.9.3 | @nuxt/image: "^1.3.0"
Looks like I also had previously installed "@nuxt/image-edge": "^1.0.0-28008586.381b906",

Removing the image-edge and reinstalling node-modules cleared this issue for me. @TakCastel check your packages for anything stray like this? I do not have ipx defined in my package manager.

**Comment by TakCastel** [comment]
I managed to solve this issue. When I run `npm run dev` a subtask is running and whenever I press "enter" key in the terminal it auto installs @nuxt/image that I clearly asked NOT to install. This is the worst way of installing a package in a framework, causing breaking changes. Can you please prevent this package to be installed on a simple keypress @Atinux? Thank you for your time, keep up the good work :)

**Comment by Atinux** [comment]
Thanks for the feedback. we will look into this (cc @danielroe)
