### ISSUE TITLE
v1.3.0 not working

### ISSUE THREAD

**Issue by Psycarlo** [nuxt/image#1227]
Version 1.3.0 does not work for me.

Replicate:

`
pnpm dlx nuxi@latest init .
pnpm add @nuxt/image
`

Add to modules.

When I run the server, the image does not show.

It works with v1.2.0...

**Comment by MateThemes** [comment]
I have the same error

**Comment by riobahtiar** [comment]
This issue seems to be related or duplicated to the previous issue. For workaround and temporary update you can see #1210. Thanks

**Comment by szvest** [comment]
I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

**Comment by szvest** [comment]
> Reference

I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

**Comment by ThePlastic** [comment]
+1

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/image/issues/1210

**Comment by MateThemes** [comment]
> I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

I have node version +21 and have the same problem

**Comment by chasebank** [comment]
I updated Yarn and this finally went away, even without locking the version.

Yarn 4.1.0
Node 20.11.0

**Comment by G3Raven** [comment]
do this, it worked for me
in package.json
```json
"overrides": {
    "sharp": "0.32.6"
}
``` 

```shell
npm remove sharp && npm update
```
