### ISSUE TITLE
[IPX_ERROR] Cannot find package 'sharp' imported

### ISSUE THREAD

**Issue by Sherzod06** [nuxt/image#1237]
500 error on build nuxt project. I have just deleted node_modlues and reinstalled all the packages. Then this error on production build.
![image](https://github.com/nuxt/image/assets/65542674/9692d328-c011-4201-b0d5-4ac508b66af0)
Now image module is not working. All the images giving 500 error

**Comment by ItzAmirreza** [comment]
Yes I'm facing the same issue here, NuxtImg nor NuxtPicture works.

**Comment by Sherzod06** [comment]
I have 

> Yes I'm facing the same issue here, NuxtImg nor NuxtPicture doesn't works.
> 
> Any way I can revert back to a version that it used to work? It's emergency (which version for what?)

I deleted node_modules. I have upgraded all the packages using `nuxi upgrade`. And it worked

**Comment by Aareksio** [comment]
As temporary fix you can downgrade sharp via overrides:
```json
{
  "pnpm": {
    "overrides": {
      "sharp": "0.32.6"
    }
  }
}
```
Alternatively you can downgrade the whole module `pnpm add @nuxt/image@1.2.0`.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/image/pull/1265.
