### ISSUE TITLE
Cache images generated by ipx locally

### ISSUE THREAD

**Issue by MickL** [nuxt/image#1245]
It seems like locally ipx is regenerating all images every time the website reloaded. Is it possible to cache the generated images?

- I have 20 images on one page, they come from AWS S3 and take 3-8s every time I reload the page
- This also produces unnecessary traffic to my the file storage

In contrast: Deployed to Vercel images are cached

**Comment by BananaAcid** [comment]
Same problem, different case: a 22mb file ist generated on the fly each time, taking 5secs to load … having the generated files locally cached, would be a dream.

**Comment by vonec** [comment]
may be some flag to force regeneration would be useful, it can check if image exists and move on

**Comment by Aareksio** [comment]
Caching is difficult, especially as scale increases. A basic cache layer could be added as opt-in via middleware. However, adding a layer on top of your nuxt app should be a better solution for deployment (external CDN - cloudflare, vercel; cache as proxy - eg. nginx).

**Comment by MickL** [comment]
An external layer is not an option. This issue is solely about adding caching for local development.

**Comment by MickL** [comment]
Closing this as a duplicate of #795
