### ISSUE TITLE
sizes based on viewport-height unit

### ISSUE THREAD

**Issue by tennox** [nuxt/image#1280]
I have a use-case which I think is not currently possible:
A hero image with `object-fit: cover` that has full width a height of `88vh` - so on portrait-orientation screens, using the width as indicator leads to a pixelated image.

I've tried different variations of `sizes` values, but setting a `vh` unit does not work:
```
<NuxtPicture class="block h-full w-full" :img-attrs="{ 'class': 'w-full h-full object-cover object-center-top' }"
    sizes="88vh lg:100vw" />
```

Might be enabled by #469 if I can set a custom value :thinking: 

Or is there a different way to achieve my goal?

**Comment by Baroshem** [comment]
Closing as the linked issue was closed after implementing a feature :)
