### ISSUE TITLE
Template src not found:

### ISSUE THREAD

**Issue by laraketai** [nuxt/image#129]
Fresh install nuxt and "@nuxt/image"

**Comment by doubtx** [comment]
Same issue
Installing alpha version from npm helped, but then I encountered Ecma import failure

**Comment by Tukizz** [comment]
same issue here
i use nuxt version 2.14.6
and @nuxt/image 0.1.0

**Comment by flapili** [comment]
using the version 0.0.2 seem solve the issue. `yarn add --dev @nuxt/image@0.0.2` @laraketai @doubtx @Tukizz 😉
@Atinux any hint on the issue ?

**Comment by f3ltron** [comment]
yeah you have to use alpha version @flapili  no it's "@nuxt/image": "^0.2.0-alpha.1. But there is an issue with runtime on alpha
#130

**Comment by dariuspasca** [comment]
Also tried to add to a new project and had the same issue.
Running nuxt 2.14.2 and @nuxt/image 0.1.0

**Comment by pi0** [comment]
Hi. Latest tested version is `0.0.4` [see versions](https://www.npmjs.com/package/@nuxt/image?activeTab=versions). `0.2.0-alpha` is  WIP and based on dev branch rewrites so is not recommended to use.

**Comment by f3ltron** [comment]
Maybe tag the new version may help @pi0
