### ISSUE TITLE
Unable to execute generate or build successfully(ERROR: Exiting due to prerender errors)

### ISSUE THREAD

**Issue by hmingv** [nuxt/image#1296]
Hi everyone, I received the following error when executing `pnpm generate`, which is frustrating because I have no idea why it is, but I speculate that it has something to do with my environment.

I am currently testing on two platforms and there is a problem
1. Windows 11
      - Operating System: Windows_NT
     - Node Version: v20.1.0
     - Nuxt Version: 3.10.0
     - CLI Version: 3.10.0
     - Nitro Version: 2.8.1
     - Package Manager: npm@9.6.4
     - Builder: -
     - User Config: devtools, modules, image
     - Runtime Modules: @nuxt/image@1.4.0
     - Build Modules: -
     -  ![image](https://github.com/nuxt/image/assets/57735185/b4c38e4e-e8fb-41eb-b10b-618c79a2e842)

2. Ubuntu 22.04.3 LTS
     - Operating System: Linux
     - Node Version: v20.11.1
     - Nuxt Version: 3.10.0
     - CLI Version: 3.10.0
     - Nitro Version: 2.8.1
     - Package Manager: npm@10.2.4
     - Builder: -
     - User Config: devtools, modules, image
     - Runtime Modules: @nuxt/image@1.4.0
     - Build Modules: -
     -  ![image](https://github.com/nuxt/image/assets/57735185/ae7ac481-8255-4799-afea-9c97ed43618e)

Their errors vary, but all prevent me from deploying.

But consciously, when I try to create [mimimal reproduction](https://codesandbox.io/p/devbox/test-nuxt-image-forked-klnzvq) it is successful.
Whether it's `pnpm generate` or `pnpm build` it goes very smoothly.

> Note: The code running in the three environments is the same

![image](https://github.com/nuxt/image/assets/57735185/a7da817c-a7d9-4fe0-ba6d-bcffd1a148cb)

But unfortunately, I need to deploy the project in a real environment, so I would like to ask everyone, what is the reason for this? What should I do to solve it.

If there is anything you need to add, please let me know, thank you!

**Comment by henriquemarba2** [comment]
Nada ainda?

**Comment by Rugpjutis** [comment]
![image](https://github.com/nuxt/image/assets/3072011/6e0d5994-0e1c-4889-9964-a765159b14e6)
windows reserved character : (colon)
