### ISSUE TITLE
random 403 errors Ipx

### ISSUE THREAD

**Issue by Kaynec** [nuxt/image#1302]
hi 
as my title suggests , the issue i have is that i get random 403 errors when trying to access images stored on a external storage space 

```ts
image: {
    quality: 75,
    format: ["webp", "jpg", "jpeg"],
    domains: [
      "https://storage.iran.liara.space/cheatsgame-storage",
      "https://storage.iran.liara.space/cheatsgame-storage/product",
    ],
  },
```

this is the sort of response i get back

```
{
  "error": {
    "message": "[403] [Forbidden] [GET] \"https://storage.iran.liara.space/cheatsgame-storage/product/main_images/2-137_1.png?AWSAccessKeyId=6499e5um61969pmk&Signature=FXzkCysyZhe9+PlRFbmF3TBOqMY=&Expires=1711465733\": 403 Forbidden"
  }
}
```

i don't really know why this happens because it seems to be totally random too , i have let's say ten images , on reload i get this error for the first image , another page refresh and some different images are now not loading

**Comment by danielroe** [comment]
cc: @pi0

**Comment by HeavenSwordz** [comment]
I'm also experiencing this issue but only when running `npm run dev`, not on the production build. 

The only workaround I've found so far, although it's not ideal, is to force the image to repaint when it fails to load using `@error`.

I'm aware that it's really not the best solution, but if it can help someone else facing the same problem, then I'm happy to share it.

In the script:
```
const retryCount: Ref<number> = ref(0);
const displayImg: Ref<boolean> = ref(true);

function onError() {
  if (retryCount.value < 2) {
    displayImg.value = false;
    nextTick(() => {
      displayImg.value = true;
      retryCount.value++;
    });
  }
}
```
In the template:
```
<NuxtPicture
      v-if="displayImg"
      :src="src"
      :alt="name"
      loading="lazy"
      sizes="565px"
      @error="onError"
/>
```

Perhaps the problem stems from my weird setup, using a Docker container with Nginx to host images and access them externally on the host. It's also possible that unsanitized image paths contribute to the issue. However, neither of these factors fully explain the randomness of it.

At some point, I might attempt to reproduce the issue in a smaller project and share it with others.

**Comment by Baroshem** [comment]
Closing as the workaround was provided.
