### ISSUE TITLE
Alias configuration is invalid

### ISSUE THREAD

**Issue by hmingv** [nuxt/image#1304]
I expect that @nuxt/image can be used as the documentation says. After saving the image of the remote site to the local, the domain name path is replaced with an alias.

But no matter how I configure the alias option, I can't achieve the effect in the document.

minimal reprodction: https://codesandbox.io/p/devbox/test-nuxt-image-forked-klnzvq

![image](https://github.com/nuxt/image/assets/57735185/b4311c76-7e1b-4bf1-8b68-719c0bb67f22)

**Comment by tewnut** [comment]
Same with this [issue](https://github.com/nuxt/image/issues/1065)
