### ISSUE TITLE
Feature Request: option to disable image density warning

### ISSUE THREAD

**Issue by Aareksio** [nuxt/image#1308]
![image](https://github.com/nuxt/image/assets/11166786/18a7870a-2000-4d31-bc6d-3855ad4dcf30)

Option to disable the message, or at least print only once per dev server restart. While a decent recommendation, the warning provides little additional value being displayed more than once.

Ref: https://github.com/nuxt/image/pull/973

**Comment by danielroe** [comment]
Yes, we should print this only once.
