### ISSUE TITLE
cannot find module 'storyblok' when trying custom provider

### ISSUE THREAD

**Issue by f3ltron** [nuxt/image#131]
Hello I am currently using:

nuxt: 
@nuxt/image: 0.0.4

I followed documentation: https://image.nuxtjs.org/custom-provider

My files

```js
[nuxt.config.js]
...
image: {
    providers: {
      storyblok: {
        name: 'storyblok', // optional value to overrider provider name
        provider: '~/providers/storyblok', // Path to custom provider
        options: {
          // ... provider options
        },
      },
    },
  },
```

```js
[/providers/storyblok.js]
export default {
  getImage(src, modifiers, options) {
    // const { width, height, format, fit, ...providerModifiers } = modifiers
    // const { width, height, format, fit } = modifiers
    const operations = []

    // process modifiers

    const operationsString = operations.join(',')
    return {
      url: options.baseURL + operationsString + src,
      static: false,
      getInfo: () => {
        return {
          width: 1,
          height: 1,
          bytes: 1,
        }
      },
    }
  },
}
```

```js
[/providers/runtime.js]
export default {
  getImage(src, modifiers, options) {
    // const { width, height, format, fit, ...providerModifiers } = modifiers
    // const { width, height, format, fit } = modifiers
    const operations = []

    // process modifiers

    const operationsString = operations.join(',')
    return {
      url: options.baseURL + operationsString + src,
      static: false,
      getInfo: () => {
        return {
          width: 1,
          height: 1,
          bytes: 1,
        }
      },
    }
  },
}
```

the error I have. 

 FATAL  Cannot find module 'storyblok'                                                                                                                                                            09:49:30
Require stack:
- /Users/giraudflorent/workdir/bankora/landing/node_modules/@nuxt/core/dist/core.js
- /Users/giraudflorent/workdir/bankora/landing/node_modules/@nuxt/cli/dist/cli-index.js
- /Users/giraudflorent/workdir/bankora/landing/node_modules/@nuxt/cli/dist/cli.js
- /Users/giraudflorent/workdir/bankora/landing/node_modules/nuxt/bin/nuxt.js

**Comment by f3ltron** [comment]
It's working with directly passing `random: '~/providers/random',` but with that I can't pass any options

**Comment by tillmon** [comment]
You have to create a subfolder under providers and rename `storyblok.js` to `index.js`. The content of `runtime.js` is not correct.

```
/providers/storyblok/index.js
/providers/storyblok/runtime.js
```

**Comment by f3ltron** [comment]
I am closing it as I have created a PR to implement it internally. Thanks for your answer tillmon
