### ISSUE TITLE
NuxtImg not show image when install with Bun

### ISSUE THREAD

**Issue by kang49** [nuxt/image#1318]
It's okay if i install NuxtImg with Yarn or NPM but on Bun it not load image

## Bun install log
```
bun install v1.0.9 (98f20170)
 + @nuxt/devtools@1.1.5
 + @nuxt/image@1.5.0
 + @nuxtjs/tailwindcss@6.11.4
 + nuxt@3.11.2
 + vue@3.4.21
 + vue-router@4.3.0
 + @octokit/core@6.1.2
 + @vuepic/vue-datepicker@8.4.0
 + apexcharts@3.48.0
 + vue3-apexcharts@1.5.2
ℹ Using default Tailwind CSS file                                                                                                                                 nuxt:tailwindcss 1:48:17 PM
✔ Types generated in .nuxt                                                                                                                                                         1:48:17 PM

 898 packages installed [16.15s]
 ```

**Comment by kang49** [comment]
I don't know what wrong but in [reproduction](https://codesandbox.io/p/devbox/funny-fire-tqepd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluuzn7zh00073d5uw3h3j590%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluuzn7zh00023d5uqia35qb3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluuzn7zh00043d5u0unrtmxq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluuzn7zh00063d5urce3nvuk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluuzn7zh00023d5uqia35qb3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluuzn7zg00013d5uyz5zw46e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluuzn7zh00023d5uqia35qb3%2522%252C%2522activeTabId%2522%253A%2522cluuzn7zg00013d5uyz5zw46e%2522%257D%252C%2522cluuzn7zh00063d5urce3nvuk%2522%253A%257B%2522id%2522%253A%2522cluuzn7zh00063d5urce3nvuk%2522%252C%2522activeTabId%2522%253A%2522cluv02vob00l83d5u2lm7kztn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluuzn7zh00053d5unvljbr83%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cluv02vob00l83d5u2lm7kztn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluuzn7zh00043d5u0unrtmxq%2522%253A%257B%2522id%2522%253A%2522cluuzn7zh00043d5u0unrtmxq%2522%252C%2522activeTabId%2522%253A%2522cluuzpz4y00fm3d5ub4zsg87q%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluuzpz4y00fm3d5ub4zsg87q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluuzpzcs02w4ddg7hivieg1u%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) it's work, But in my computer not work and i found this error on console

```
{
    "error": {
        "message": "[500] [IPX_ERROR] \nSomething went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp-darwin-arm64v8.node'\nRequire stack:\n- /Users/kang49/Desktop/nanami-bot-frontend/.output/server/node_modules/sharp/lib/sharp.js\n- /Users/kang49/Desktop/nanami-bot-frontend/.output/server/node_modules/sharp/lib/constructor.js\n- /Users/kang49/Desktop/nanami-bot-frontend/.output/server/node_modules/sharp/lib/index.js\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current darwin-arm64v8 runtime: \"npm install --platform=darwin --arch=arm64v8 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
    }
}
```

**Comment by kang49** [comment]
Issue is duplicate with nuxt/image#624, So i will close this issue.

**Comment by kang49** [comment]
I fixed this problem! Just upgrade bun to latest version(now bun 1.1.3) and run `bun add sharp --ignore-engines` if you use bun.

**Comment by ealbinu** [comment]
> I fixed this problem! Just upgrade bun to latest version(now bun 1.1.3)

This worked
