### ISSUE TITLE
loading="lazy" don't work

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt/image#1343]
![image](https://github.com/nuxt/image/assets/52190592/09b5db41-7e8d-4354-a9b8-55205ed4f507)

rendered into：

![image](https://github.com/nuxt/image/assets/52190592/2299f2bd-7946-44ed-afc9-1584c86005c3)

loading should be placed before src

Such rendering causes lazy loading to not take effect.

**Comment by danielroe** [comment]
Yes, this is already resolved in https://github.com/nuxt/image/pull/1338 and will be fixed in the next release.

**Comment by lceihen** [comment]
> Yes, this is already resolved in #1338 and will be fixed in the next release.

hi bro, still find this problem at <nuxt3.11.1>  <@nuxt/image 1.7.0>, the next release has include this version ?

**Comment by danielroe** [comment]
No, v1.7.0 includes this fix.
