### ISSUE TITLE
Nitro publicAssets 404

### ISSUE THREAD

**Issue by woldtwerk** [nuxt/image#1363]
When adding public assets to nitro via a hook:

```ts
nitroConfig.publicAssets.push({
   dir: resolver.resolve(`${nuxt.options.rootDir}/content/.uploads/media`),
   maxAge: 60 * 60 * 24 * 365,
})
```

ipx will throw a 404 error. I guess ipx resolves the file directory and doesn't care if the file is reachable under '/'

  ├─ /_ipx/_/ogimage.jpg (12ms)                                                                                                                                   nitro 10:24:35 AM
  │ ├── Error: [404] IPX_FILE_NOT_FOUND

My current workaround is to do a symlink instead.

**Comment by Skyost** [comment]
Same problem happens to me when I'm trying to push a directory with a `baseURL` that already exists.
