### ISSUE TITLE
error code 503 problems why 

### ISSUE THREAD

**Issue by tolgahanbeyazoglu** [nuxt/image#1398]
why do I get error 503 even though everything is fine then I refresh the page sometimes it comes sometimes it doesn't when I try the local host  everything is correct I wonder if it is related to the local host

![Ekran görüntüsü 2024-07-04 095517](https://github.com/nuxt/image/assets/129540736/af92bd76-73a9-48e7-a6ba-45cff17d30ef)

**Comment by mak33v** [comment]
I've been experiencing this issue for over a year now, both in development and production mode. What can be wrong?

![image](https://github.com/user-attachments/assets/159bb32a-af39-4db9-a002-859d3a925fe0)
