### ISSUE TITLE
NuxtImage + IPX + SWR = return buffer

### ISSUE THREAD

**Issue by bernhardberger** [nuxt/image#1400]
When I enable SWR on our website IPX/nitro/whatever the culprit.. returns a buffer instead of an image:

![image](https://github.com/nuxt/image/assets/2110083/80d46e96-ccf9-47ab-b90e-3c57eae6a8dd)

Any ideas how to work around this? This has been a major issue for us, preventing is to run SWR on our website and customer projects..

**Comment by metkm** [comment]
do you have reproduction? I can't seem to replicate the issue

**Comment by bernhardberger** [comment]
Sure:
https://github.com/bernhardberger/nuxt-ipx-swr-buffer-minimal-reproduction

`npm run build && node .output/server/index.mjs`

-> hard reload (CTRL+SHIFT+R) a few times after 10 seconds -> image will be dead

**Comment by bernhardberger** [comment]
related: https://github.com/nuxt/nuxt/issues/27307

**Comment by bernhardberger** [comment]
Imho this should be documented..

**Comment by bernhardberger** [comment]
We have now solved this using a nitro onBeforeResponse hook that unwraps and streams the Buffer.

**Comment by manot40** [comment]
Hey @bernhardberger, did you already done working with nitro hook code sample? Thanks in advance.

**Comment by ItsRyanWu** [comment]
> Hey [@bernhardberger](https://github.com/bernhardberger), did you already done working with nitro hook code sample? Thanks in advance.
> 
> EDIT: Just made simple [nuxt module](https://stackblitz.com/edit/github-62ndkb) to cache optimized images from ipx request to disk, inspired by [#795](https://github.com/nuxt/image/issues/795). (You'll need to download and run the example project since stackblitz seems not working with native `.node` file sharp uses)

You are my hero! You should consider making this a published module, it will save a lot of people's life!

**Comment by Baroshem** [comment]
Closing as the solution was provided.

Feel free to reopen if needed :)
