### ISSUE TITLE
Vercel Support

### ISSUE THREAD

**Issue by simonmaass** [nuxt/image#141]
Is there a way to get this working on vercel? serverless?

**Comment by pi0** [comment]
Embedding local provider (IPX/sharp) is not recommended if possible. Currently you may use a CDN provider like cloudinary for on-demand image resizing. Vercel also has an endpoint for resizing but it is currently Next.js specific (something like `/_next/image`). We are in contact with vercel team to support vercel provider...

**Comment by simonmaass** [comment]
@pi0 totally makes sense! thank you for the quick reply! great project here btw! thank you!
