### ISSUE TITLE
IPX provider not working properly when the default provider is not IPX

### ISSUE THREAD

**Issue by mupinnn** [nuxt/image#1414]
I have custom provider (thumbor) as my default provider in the config and in some case I still need IPX provider, so I pass provider props in the `NuxtImg` components as `<NuxtImg provider="ipx" />` and the result is 404. `_ipx` path is not found.

The config I had:
```ts
image: {
  ipx: {},
  provider: "thumbor",
  providers: {
    thumbor: { ... }
  }
}
```

When I omit the `ipx` property, it throw `Unknown provider: IPX` error. The config works when I replace the default provider with `ipx`.

Is it expected behavior?

I create a minimal reproduction using `ipx` and `unsplash` provider to suit my problem: https://stackblitz.com/edit/nuxt-image-ipx-repro?file=app.vue

Thank you!

**Comment by Tofandel** [comment]
I have a very similar issue, I'm trying to instantiate 2 ipx instances but only one is ever setup

With a bit of debug, that's because the providerSetup is made using the name of the provider instead the `provider` key of the provider

```const setup = input.setup || providerSetup[input.name];```

**Comment by MickL** [comment]
I also cant use ipx as a secondary provider. I use cloudflare as my main provider for images hosted on Cloudflare Images but I want to use ipx occasionally for static images:

Nuxt config:
```
image: {
    provider: 'cloudflare',
}
```

Component:
```html
<NuxtImg src="/static-image.jpg" provider="ipx" />
```

Error:
```
[nuxt] [request error] [unhandled] [500] Unknown provider: ipx
```

**Comment by nathanchase** [comment]
I found this out recently as well.

If I have this in my nuxt.config:

```js
image: {
   provider: import.meta.env.NUXT_PUBLIC_IMAGE_PROVIDER,
}
```
it doesn't matter what I set that env var to - `ipx` will never run or work correctly in production.

If I do this instead:
```js
image: {
   provider: import.meta.env.NUXT_PUBLIC_IMAGE_PROVIDER || 'ipx',
}
```
then that seems to signal to the production build that ipx is needed, and then it seems to actually install what's necessary to have ipx running on the built production server.

**Comment by MickL** [comment]
Is there any news on this? @danielroe

**Comment by mrleblanc101** [comment]
Same issue for me, I want to default to `prismic` and use `ipx` as secondary

**Comment by Tofandel** [comment]
If anyone wants to make a PR for this, feel free, just fixing this particular issue wouldn't take a huge change, as it's only necessary to change the condition for setting up IPX I mentionned, I do not have the time right now to work and finish my PR

**Comment by whatcould** [comment]
I added a pull request just to fix the first issue mentioned — that IPX is not initiated if it is not the default. It does not fix the issue @Tofandel has with setting up multiple instances of the same provider. As Tofandel said, it just required checking to see if you've specified ipx in the options (as reporter @mupinnn does above).

Doesn't seem to be any workaround without the PR.

**Comment by MickL** [comment]
Thanks, I hope it will get merged!

**Comment by Smef** [comment]
I'm not exactly sure what is supposed to be fixed or what config is required, but I've found that I was still getting errors generating images using `pnpm run generate`. I had to add 

```
image: {
        // @nuxt/image
        provider: "ipx",
    }, 
```

and this seemed to stop the nondescript 500 errors when running `generate`.

**Comment by mrleblanc101** [comment]
I still can't manage to make it work... 
Even on 2.0.0 :(

If I have this in my `nuxt.config.ts`:
```js
image: {
    provider: 'ipx',
    domains: ['static.swapcard.com'],
    quality: 70,
    format: ['webp'],
},
```
This won't work: 
```html
<NuxtImg provider="prismic" :src="speaker.img.url" :alt="speaker.img.alt" width="322" height="375" />
```

I'll get:
> Unknown provider: prismic

---

If I have this in my `nuxt.config.ts`:
```js
image: {
    provider: 'prismic',
    domains: ['static.swapcard.com'],
    quality: 70,
    format: ['webp'],
},
```
This won't work: 
```html
<NuxtImg provider="ipx" width="128" height="128" :src="speaker.photoUrl" alt="" />
```

I'll get:
> Unknown provider: ipx

**Comment by MickL** [comment]
It works for me. Of course have to declare providers as written multiple times above. Nuxt Image will not scan all your components to see if you used a different providers prop anywhere...

> As Tofandel said, it just required checking to see if you've specified ipx in the options (as reporter @mupinnn does above).

Should work like this:

```
image: {
    provider: 'prismic', // <-- default provider
    domains: ['static.swapcard.com'],
    quality: 70,
    format: ['webp'],
    providers: {
       ipx: {}
       prismic: {}
   }
},
```

**Comment by mrleblanc101** [comment]
@MickL 
> as written multiple times above

Multiple time, really ?
I've re-read the whole thread and it's not mentioned anywhere...
The closest is `provider: import.meta.env.NUXT_PUBLIC_IMAGE_PROVIDER || 'ipx'`, where `NUXT_PUBLIC_IMAGE_PROVIDER` would be `prismic` and it didn't work....

How am I supposed to know that it won't scan for the `provider` props ?
Not only is this not mentioned anywhere in the docs, but if you only have on provider you don't need to list it twice:
```js
provider: 'prismic', // <-- default provider
providers: {
   ipx: {}
}
```
