### ISSUE TITLE
Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by simonmaass** [nuxt/image#143]
I installed as documented in setup and created provider for cloudinary:

![image](https://user-images.githubusercontent.com/32599710/103882232-c8b07700-50db-11eb-825c-d597327889b5.png)

If i now use it:
![image](https://user-images.githubusercontent.com/32599710/103882265-d665fc80-50db-11eb-9a59-8a018219174e.png)

I get the following error:
![image](https://user-images.githubusercontent.com/32599710/103882293-e087fb00-50db-11eb-9d0a-9ae69e6f4ec9.png)

**Comment by pi0** [comment]
This should be gone since as latest we don't try to get image meta
