### ISSUE TITLE
Latest release is missing `NuxtOptions` extension

### ISSUE THREAD

**Issue by cjpearson** [nuxt/image#1449]
The following exists in `dist/types.d.ts` for 1.7.0 but is missing in the same file for 1.7.1

```ts
import type { ModuleOptions } from './module'

declare module '@nuxt/schema' {
  interface NuxtConfig { ['image']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['image']?: ModuleOptions }
}

declare module 'nuxt/schema' {
  interface NuxtConfig { ['image']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['image']?: ModuleOptions }
}
```

This causes a type error when a setup function tries to modify the Nuxt Image config.

```ts
async setup(options, nuxt) {
  nuxt.options.image = {...} // error TS2339: Property 'image' does not exist on type 'NuxtOptions'.
}
```

**Comment by flav-code** [comment]
I don't know if it's related, but in 1.7.1 my images no longer have the width and height attributes.

**Comment by danielroe** [comment]
This was removed from `@nuxt/module-builder` output and should be added instead by `.nuxt/types/schema.d.ts`. What version of Nuxt are you on?

**Comment by cjpearson** [comment]
The error occurs in an app-local module, so I've made a small reproduction app with a local module.

https://github.com/cjpearson/nuxt-image-types

The type error is in `modules/my-module/index.ts` and disappears once `@nuxt/image` is downgraded to 1.7.0
