### ISSUE TITLE
Object is possibly 'undefined'

### ISSUE THREAD

**Issue by 9mm** [nuxt/image#1453]
I'm getting a lot of errors for typescript in nuxt image. I am using nuxt v4 compatibility mode if that makes a difference

```
 ERROR(vue-tsc)  Object is possibly 'undefined'.
 FILE  /Users/zesty/Code/xxx-frontend/node_modules/.pnpm/@nuxt+image@1.7.1_ioredis@5.4.1_magicast@0.3.5_rollup@4.21.1/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue:20:16

    18 |       :src="sources[lastSourceIndex].src"
    19 |       :sizes="sources[lastSourceIndex].sizes"
  > 20 |       :srcset="sources[lastSourceIndex].srcset"
       |                ^^^^^^^^^^^^^^^^^^^^^^^^
    21 |     >
    22 |   </picture>
    23 | </template>
```

**Comment by danielislas3** [comment]
I’m hitting the same issue, and I believe it’s related to the [latest release v3.13.0](https://github.com/nuxt/nuxt/releases/tag/v3.13.0). It seems that there were changes in the types, which might be causing this problem. I found this [Vue TypeScript Changes](https://github.com/nuxt/nuxt/releases/tag/v3.13.0) that mentions updates to TypeScript handling, but I’m still unsure how to resolve the issue.

**Comment by danielroe** [comment]
it's not an upstream issue, but it was resolved in https://github.com/nuxt/image/commit/917242a567ffbbb3cd6cf467322252a5cf9194f4.

thanks for investigating! ❤
