### ISSUE TITLE
[Vercel] Image Sizing Broken

### ISSUE THREAD

**Issue by jaketig** [nuxt/image#1455]
index.vue:
```vue
<NuxtImg src="/img/logo.png" height="130" alt="Bee Line Parks" />
```

1.7.1 on Vercel in Production:

Generated HTML:
``` html
<img onerror="this.setAttribute('data-error', 1)" data-v-a22f9b78="" src="/_vercel/image?url=%2Fimg%2Flogo.png&amp;w=2560&amp;q=100">
```

Screenshot:
![image](https://github.com/user-attachments/assets/4d502180-6e2a-460e-90a0-7248b92a7d77)

vs 1.7.0 on Vercel in Production

Generated HTML:
``` html
<img onerror="this.setAttribute('data-error', 1)" height="130" alt="Bee Line Parks" data-nuxt-img="" srcset="/_vercel/image?url=%2Fimg%2Flogo.png&amp;w=2560&amp;q=100 1x, /_vercel/image?url=%2Fimg%2Flogo.png&amp;w=2560&amp;q=100 2x" class="" src="/_vercel/image?url=%2Fimg%2Flogo.png&amp;w=2560&amp;q=100" data-v-a22f9b78="">
```

Screenshot:
![image](https://github.com/user-attachments/assets/e3815712-425f-40e9-9f24-ac60345954c0)

**Comment by tomsdob** [comment]
Facing the same issue, as you can see in your code, the `alt` attribute is also not generated.
