### ISSUE TITLE
Can no longer import runtime providers (in 1.8.0)

### ISSUE THREAD

**Issue by remihuigen** [nuxt/image#1474]
I was using this configuration, which broke in v1.8.0, since ``@nuxt/image/dist/runtime/providers/cloudinary`` is no longer found.

```ts
image: {
    provider: 'cloudinary',
    cloudinary: {
      baseURL: baseConfig.api.cloudinary + '/image/upload/',
      modifiers: {
        quality: '80',
      }
    },
    providers: {
        video: {
            provider: '@nuxt/image/dist/runtime/providers/cloudinary',
            options: {
                baseURL: baseConfig.api.cloudinary + '/video/upload/'
            }
        }
    }
  }
```

```
Pre-transform error: Failed to resolve import "/Users/remihuigen/local-projects/clients-onderwijsin/onderwijsin-nuxt/@nuxt/image/dist/runtime/providers/cloudinary" from "virtual:nuxt:/Users/remihuigen/local-projects/clients-onderwijsin/onderwijsin-nuxt/.nuxt/image-options.mjs". Does the file exist?  
```

Up until 1.7.0 this worked fine

Basically, what I'm trying to achieve is having an alt cloudinary provider with ``/video/upload/`` in it's baseUrl, so I can use images for video files by  using the alternate provider.

Any suggestions?

**Comment by Baroshem** [comment]
Hmm, strange. I can still see this file in the node modules:
`node_modules/@nuxt/image/dist/runtime/providers/cloudinary.js`

Maybe you need to add an extension `.js`? Not sure as I have not done things like these.

If this won't work, could you create a reproduction link? :)

**Comment by remihuigen** [comment]
Adding the .js extension doesn't resolve the issue unfortunately

Here's a reproduction:
https://stackblitz.com/edit/github-xuh6accr


Note that if you set @nuxt/image to 1.7.0, everything works. But upgrading to ^1.8.0 results in an import error

**Comment by danielroe** [comment]
we do not expose the providers individually via subpath exports.

you should be able to specify `provider: 'cloudinary'` though - is there a reason this isn't working?

**Comment by remihuigen** [comment]
Didn't know you could do that! Thanks, that works :)
