### ISSUE TITLE
Unable to set fallback image & failed, reason: socket hang up

### ISSUE THREAD

**Issue by treboryx** [nuxt/image#148]
Unlike the <img> tag, I'm unable to use @error and use a method to set a fallback image in case the image that's loaded is broken, is there a way of doing this?

Also, on my development environment I often get the following error

```
failed, url-of-image-here reason: socket hang up
```

Which doesn't seem to be the case in a production environment.

**Comment by pi0** [comment]
Hi @treboryx. Can you please try behavior with `0.2.0-alpha.7`? We no longer fetch placeholder images

**Comment by treboryx** [comment]
> 0.2.0-alpha.

new error occurred

```
[Vue warn]: Unknown custom element: <nuxt-image> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

is there something that I'm missing? With the 0.0.4 version this error doesn't not appear.

**Comment by pi0** [comment]
You need to change `nuxt-image` to either `nuxt-picture` or `nuxt-img`. 

Sorry for this docs are still outdated. And image-module is marked as WIP because api changes can happen until we finally announce module.

**Comment by treboryx** [comment]
> You need to change `nuxt-image` to either `nuxt-picture` or `nuxt-img`.
> 
> Sorry for this docs are still outdated. And image-module is marked as WIP because api changes can happen until we finally announce module.

Yes that seems to work. However, I must mention that I no longer see that smooth lazy loading animation anymore. But like you said it's WIP.

We can wrap this up once you review PR https://github.com/nuxt/image/pull/153 since it's part of the second issue I mentioned here.

**Comment by pi0** [comment]
Closing this as hang-up is resolved. We can follow feature request in #153 :)
