### ISSUE TITLE
Plans to support Prismic as a provider?

### ISSUE THREAD

**Issue by asencis** [nuxt/image#150]
As the title suggests, are there any plans to support images delivered via Prismic.io as a content provider?

**Comment by f3ltron** [comment]
Hello, I don't know if there is a plan to implement it right now but you can easily integrate it by creating a custom provider for now.

**Comment by pi0** [comment]
Hi @asencis. Googling about prismic image optimization, i found [this article](https://user-guides.prismic.io/en/articles/3309829-image-optimization-imgix-integration) and they seem to use [imgix](https://www.imgix.com/) which we already have [provider](https://github.com/nuxt/image/blob/dev/src/runtime/providers/imgix.ts) for it so with proper baseURL, below config should work: 

```js
  image: {
    providers: {
      imgix: {
        baseURL: 'images.prismic.io'
      }
    }
  }
}
```

Would be nice if can try (preferrably on v0.2.0 with alpha tag) and give feedback :)

**Comment by asencis** [comment]
@pi0 @f3ltron Hi all, many thanks for your answers. It seems from pi0's comment that we can use imgix as the base provider, which is excellent news! So there's no need for integration. As always, I will have a look at what I need to do my side and get things integrated. When I do - I'll post up something here for anyone to have a look at.
