### ISSUE TITLE
Custom Provider not working

### ISSUE THREAD

**Issue by JohannesSchwegler** [nuxt/image#152]
Hello, I can`t register a custom provider. The setup provided in the documentation is not working.

`image: {

    providers: { 
      strapi: {
        name: 'strapi', // optional value to overrider provider name
        provider: '~/providers/strapi', // Path to custom provider
        options: {
          baseURL: 'http://localhost:1337/uploads/',
          // ... provider options
        },
      },
    },
  },
`

My provider file under /providers/strapi/index.js

`export default function (providerOptions) {
  return {
    runtime: require.resolve('./runtime'),
    runtimeOptions: providerOptions,
  }
}
`

The error is: "Cannot find module 'strapi'     "

**Comment by reslear** [comment]
work is change `~/` to `./`

**Comment by JohannesSchwegler** [comment]
Nope, unfortunately, this isn`t working either

**Comment by pi0** [comment]
This workaround should work:

```js
  image: {
    provider: 'strapi',
    providers: {
      strapi: {
        provider: require.resolve('./providers/strapi')
      }
    }
  },
  ```
  
  BTW i confirm this issue. Should fix in next release

**Comment by istreetec** [comment]
Use below git repository to resolve your provider paths [Custom Nuxt Image Providers](https://github.com/nuxt/image/tree/dev/src/runtime/providers)
