### ISSUE TITLE
Hi, I am trying to get NuxtImg going with CloudFlare images. https://image.nuxt.com/providers/cloudflare

### ISSUE THREAD

**Issue by ICTLAYER** [nuxt/image#1546]
Hi, I am trying to get NuxtImg going with CloudFlare images. https://image.nuxt.com/providers/cloudflare
It says on the docs about baseURL `Your deployment's domain (zone).` meaning I have to connect my website domain to CloudFlare, like zones?

I am using Vercel's automatically assigned domain name for now. It is not possible to change DNS afaik. So does it mean I can't test my website on local or just dev environment?

Or is it just `https://imagedelivery.net/<account_id>`? Even if I do this, for some reason, the image url becomes: /https://imagedeliver... It adds a '/'. 

Also on docs, it shows only the image name as src: `src="/burger.jpeg"`, does it mean this part: /<account_id>/<image_id>/public`?

Is there an example?

If possible, and if this gets resolved I want to open a PR for docs.

_Originally posted by @onurusluca in https://github.com/nuxt/image/discussions/1491_

**Comment by ICTLAYER** [comment]
**### ### More as example an to example prove to myself:** prove myself with respect:

**Not Working:** https://nuxtimgtest.pages.dev/cdn-cgi/image/7mnVjFJmJT6C1-RIIlFtQg/cf0cac91-0a0e-4c86-c376-60597e37e700/public

**Working:** https://nuxtimgtest.pages.dev/cdn-cgi/imagedelivery/7mnVjFJmJT6C1-RIIlFtQg/cf0cac91-0a0e-4c86-c376-60597e37e700/public

@oritwoen @danielroe @renovate-bot @pi0 @atinux

**Comment by onurusluca** [comment]
Thanks for pointing this out again. This needs to be cleared up. I searched about this for 2 days and I gave up. Hopefully someone knows. Cloudflare's docs aren't good. It's says you need to create a namespace, connect domain or something. I was so lost.

**Comment by nafiz6629** [comment]
I found certain sections challenging to follow, which may impact the ease of implementation for users. Specifically, it seems that some concepts and instructions could benefit from further elaboration or examples. **Improving the clarity and structure would greatly enhance the user experience and reduce potential confusion.** 
Like what **type of image source is required** to use this provider. Is it **third-party** image source or my own **Cloudflare's images** ?

**Comment by masud-ictlayer** [comment]
https://image.nuxt.com/providers/cloudflare
Cloudflare
Nuxt Image has first class integration with Cloudflare.
This documentation does not provide proper information about Cloudflare integration with nuxt image

**Comment by tahirmahmudzade** [comment]
> Hi, I am trying to get NuxtImg going with CloudFlare images. https://image.nuxt.com/providers/cloudflare It says on the docs about baseURL `Your deployment's domain (zone).` meaning I have to connect my website domain to CloudFlare, like zones?
> 
> I am using Vercel's automatically assigned domain name for now. It is not possible to change DNS afaik. So does it mean I can't test my website on local or just dev environment?
> 
> Or is it just `https://imagedelivery.net/<account_id>`? Even if I do this, for some reason, the image url becomes: /https://imagedeliver... It adds a '/'.
> 
> Also on docs, it shows only the image name as src: `src="/burger.jpeg"`, does it mean this part: /<account_id>/<image_id>/public`?
> 
> Is there an example?
> 
> If possible, and if this gets resolved I want to open a PR for docs.
> 
> _Originally posted by [@onurusluca](https://github.com/onurusluca) in [#1491](https://github.com/nuxt/image/discussions/1491)_

hey did you find a solution on this? i spent my whole day to find a way to make it work, nothing worked

**Comment by ymansurozer** [comment]
Here is how I was able o resolve this, hope it helps: https://github.com/nuxt/image/issues/805#issuecomment-2483628222
