### ISSUE TITLE
No hinting for prop types in Webstorm

### ISSUE THREAD

**Issue by TuringJest** [nuxt/image#1556]
Looks like changes have been made which broke type definitions in Webstorm. What is the preferred way to provide prop typings in Nuxt (for a pr)? 

@nuxtImage: 1.8.1
nuxt: 3.12.2

**Comment by TuringJest** [comment]
Nevermind the PR, totally forgot that there is a world without TS 😅

**Comment by Baroshem** [comment]
Hey there,

No worries. Happened to me few times as well! :D 

Do you still run into this issue? I have just tested it and it works correctly in VS Code for me

**Comment by Baroshem** [comment]
Closing as there is no further info.

Feel free to reopen if needed :)
