### ISSUE TITLE
When static, images are not loaded on nuxt router change

### ISSUE THREAD

**Issue by skopz356** [nuxt/image#157]
When using this package in nuxt static mode the images are not loaded on nuxt router change. It works in development mode as it should also when reloading the page by browser refresh it works right as well.

`"nuxt": "^2.14.0",
"@nuxt/image": "0.0.4",
`

**Comment by treboryx** [comment]
I can confirm this issue occurs on the latest alpha version but not on 0.0.4.

On inspection of the img tag, I noticed: 
On alpha, the url is https://website/_img/remote/_/_/image-url-here

and on 0.0.4 it's just the image url.

**Comment by hicreate** [comment]
Has anyone discovered a work around for this yet - its a production issue for me as well.
