### ISSUE TITLE
[feat] Rename images option on production for SEO

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/image#158]
I want to keep the file name of image same as I have saved in my Static folder. But currently it is showing some hash-value in URL after I run generate and start. 

I even used the `fileNames` [option](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#filenames) given in `build` in `nuxt.config.js` file:
`img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[contenthash:7].[ext]',`

I changed this to:
`img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[name].[ext]'`

**But still images are renamed as hash-value only.**
Since, the renamed file name has some path like this "_image/a11cc5.webp", I can assume it is because of nuxt-image module, and thus, above fileNames option will not work.

So,
Is there any option to write inside the `ipx` option inside `image` option provided by nuxt-image module? For e.g., `fileOutput` or `toFile`?
Something like this: 
`image: {ipx: {sharp: fileOutput or toFile: "something here"}}`

P.S. I am new to Nuxt or even Javascript.

**Comment by ManasMadrecha** [comment]
Any update on when will the image renaming option be added, so that image name can be retained for SEO?

~ Thanks in advance for this amazing easy-to-use module.

**Comment by retroriff** [comment]
I am also very interested to customize image filenames. Resized images have hash names such as:

- 484b89.jpeg
- 324234.jpeg

But it would be preferable to keep the original filenames or the alt text:

- filename-484b89.jpeg
- filename-480px.jpeg
- alt-text-484b89.jpeg

**Comment by harlan-zw** [comment]
PR for it here https://github.com/nuxt/image/issues/158 right?

**Comment by danielroe** [comment]
This should be already implemented in https://github.com/nuxt/image/pull/220.
