### ISSUE TITLE
JPEG-XL support

### ISSUE THREAD

**Issue by mbledkowski** [nuxt/image#1607]
Hello,
Is JPEG-XL support on the roadmap?
If so, when can we expect it being added?

Best regards,
Maciej Błędkowski

**Comment by Baroshem** [comment]
Hey Maciej!

I haven't heard about the support for JPEG-XL. I quickly looked at the browser support and it seems that this feature is not supported by any major browsers (Chrome, Firefox) -> https://caniuse.com/jpegxl.

I think we would need to wait some time until further adoption :)
