### ISSUE TITLE
remove duplicate: `xxl` and `2xl` is the same thing

### ISSUE THREAD

**Issue by razbakov** [nuxt/image#1633]
There is a contradiction in [configuration screens](https://image.nuxt.com/get-started/configuration#screens).

```
{
  'xs': 320,
  'sm': 640,
  'md': 768,
  'lg': 1024,
  'xl': 1280,
  'xxl': 1536,
  '2xl': 1536
}
```
> We share the same naming and sizes as [Tailwind CSS](https://tailwindcss.com/docs/responsive-design) and we added the xs property.

Either this message should be adjusted or the extra property should be removed.

There are 2 ways to name sizes:
- xl
- xxl
- xxxl

Or: 
- xl
- 2xl
- 3xl

Counting letters is more difficult than reading the number.
And xxl duplicates the value of 2xl.

**Comment by Baroshem** [comment]
I see. Thanks for clarification!

Then I think it makes sense but I wonder if it wouldn't be a breaking change? If someone was using current xxl size? @danielroe what do you think?

**Comment by danielroe** [comment]
I think having an extra screen property is useful for backwards compatibility.

I don't think it harms anything to keep it, though we can remove it from the docs if it is there. It's a superset of Tailwind.

**Comment by razbakov** [comment]
@Baroshem sure, can you show me how to make it deprecated?

**Comment by Baroshem** [comment]
As this is an object and not a type, maybe we could add a note in the documentation instead in the TS code?

Something like https://nuxt-security.vercel.app/utils/remove-console-loggers#alternative-method-deprecated

**Comment by razbakov** [comment]
@danielroe the point 2 is not done

**Comment by danielroe** [comment]
I think let's not deprecate it for now. It seems harmless.
