### ISSUE TITLE
width or height should be optional

### ISSUE THREAD

**Issue by Atinux** [nuxt/image#18]
I believe using ipx or other module to get the image ratio would be a huge improvement for DX so we could guess the height (if only width given) or width (if only height given)

**Comment by farnabaz** [comment]
Indeed this would be great  
There is another possible way, we can detect the image's original width and height using from IPX and then simulate the behavior of `img` tag.  
Right now we are fetching `lqip` version of all images, modifying IPX middleware to return the actual width/height with `lqip` version will do the trick.
The downside of this behavior is we should drop provider support in `lqip` version and just use `local` provider.

**Comment by Atinux** [comment]
I think it is worth it :)

**Comment by farnabaz** [comment]
width/height are optional in tha current version and it will be improved performance and usage in https://github.com/nuxt/image/pull/55
