### ISSUE TITLE
Docs missing nav

### ISSUE THREAD

**Issue by shadow81627** [nuxt/image#186]
Current docs from pull request #183, [preview link](https://deploy-preview-183--nuxt-image.netlify.app/)

![deploy-preview-183--nuxt-image netlify app_](https://user-images.githubusercontent.com/21211734/107755577-bd9dd600-6d6e-11eb-82b5-9fb64726a218.png)

Previous docs pull request #180, [preview link](https://deploy-preview-180--nuxt-image.netlify.app/)

![deploy-preview-182--nuxt-image netlify app_](https://user-images.githubusercontent.com/21211734/107755597-c42c4d80-6d6e-11eb-80c0-1b74140f9054.png)

**Comment by farnabaz** [comment]
Seems it is an incompatibility between Docus and Componets@v2. Reverting `nuxt-edge` version will resolve the issue.
[Template components](https://github.com/nuxtlabs/docus/tree/main/theme/components/templates) did not registered globally.

**Comment by corybagozzi** [comment]
Anyone happen to have the direct links to each section?

**Comment by pi0** [comment]
Thanks @farnabaz for checking. Will make issue to mention migration requirements.

@corybagozzi You can browse via https://github.com/nuxt/image/tree/main/docs/content/en

**Comment by pi0** [comment]
Fixed in last docs.
