### ISSUE TITLE
document $img util

### ISSUE THREAD

**Issue by pi0** [nuxt/image#192]
Progress: https://github.com/nuxt/image/pull/221

**Comment by shadow81627** [comment]
Will the docs include how to use the [getSizes function](https://github.com/nuxt/image/blob/main/src/runtime/image.ts#L134-L192) and how to get a list of responsive image urls?

I am using the getSizes function with [vuetify image component and to generate preload meta](https://github.com/nuxt/image/issues/105#issuecomment-826454174).

**Comment by pi0** [comment]
PR welcome @shadow81627 (only a caution there is a chance getSizes being renamed in a major version to getVartiants to support other variant selectors not yet even planned)
