### ISSUE TITLE
Presets don't seem to be working

### ISSUE THREAD

**Issue by corybagozzi** [nuxt/image#193]
I have setup a preset and get the TypeError "presets.reduce is not a function"

Here is my nuxt.config setup

```js
  image: {
    presets: {
      galleryThumb: {
        modifiers: {
          width: 256,
          fit: "cover",
          height: 256,
        }
      }
    },
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
      '2xl': 1536
    }
  },
```

If I remove the preset, everything else seems to be working fine. Any ideas on what might be the issue?

**Comment by pi0** [comment]
Hi @corybagozzi. It seems you are using legacy version of image module which presets option was an array `[ { name, modifiers } ]`. Please ensure using 0.4.0+)
