### ISSUE TITLE
Change opacity transition time for "lazy"

### ISSUE THREAD

**Issue by pkpowell** [nuxt/image#194]
Is it possible to change the opacity transition time? The 800ms seems to slow down my initial page load.

**Comment by pi0** [comment]
Hi. Would you please elaborate more? Which version are you using?  Transition is not used in image module :)

**Comment by pkpowell** [comment]
Hey. When I add `lazy="true"` to `<nuxt-img />` the img tags get a 0.8s opacity transition, `lazy="false"` makes it all go away. I assumed this was part of the lazy loading code. 

<img width="292" alt="Screenshot 2021-02-17 at 19 01 47" src="https://user-images.githubusercontent.com/869936/108247207-a554ff00-7152-11eb-954e-5965acfb46f3.png">

I just checked my own code and I'm pretty sure it's not leaking in from there.

I'm still on 0.0.4 as I (still) can't get the newer versions to work with local images.
I have this in `nuxt.config.js` 
```
    image: {
        // static: {
        ipx: {
            dir: "~/assets/uploads/",
            sharp: {}
       }
   }
```
Anything I can do to make 0.4.1 work with local files?
Thanks

**Comment by pkpowell** [comment]
Looks like the newer versions only load local images from `/static`. Have the options changed for the static/ipx provider? This worked before but seems to be ignored atm.
```
image: {
    static: {
        dir: "~/assets/uploads"
    }
}
```
This almost works, but won't resolve the `~`
```
image: {
    dir: "~/assets/uploads"
}

**Comment by tusamni** [comment]
Having issues here too, would much rather pull from ~/assets vs. ~/static.

Looks like it might be in regards to this line: https://github.com/nuxt/image/blob/81f8dc7ae07cf8e9ce528e9ba697b77ae939746f/src/module.ts#L15

**Comment by pkpowell** [comment]
it works without the `~/`
```

buildModules: [
    ["@nuxt/image",
        {
            dir: "assets/uploads",
            screens: {}
        }
...
```

**Comment by tusamni** [comment]
Confirmed pkpowell, thanks for the fix.
