### ISSUE TITLE
Failing to build responsive images

### ISSUE THREAD

**Issue by dikaio** [nuxt/image#198]
While running `yarn generate` I noticed a bunch of the images weren't getting built but I couldn't any open issues related to this specific error. By chance has anyone else run into this?
 
```log
 ERROR  request to http://localhost:57406/_ipx/images/news/ai/ai-5.jpg?s=640_298 failed, reason: connect ECONNRESET 127.0.0.1:57406                                                                                              @nuxt/image 06:25:39


 ERROR  request to http://localhost:57406/_ipx/images/news/ai/ai-5.jpg?s=750_349 failed, reason: connect ECONNRESET 127.0.0.1:57406                                                                                              @nuxt/image 06:25:39


 ERROR  request to http://localhost:57406/_ipx/images/news/ai/ai-5.jpg?s=826_384 failed, reason: connect ECONNRESET 127.0.0.1:57406                                                                                              @nuxt/image 06:25:39


 ERROR  request to http://localhost:57406/_ipx/images/news/ai/ai-5.jpg?s=1652_768 failed, reason: connect ECONNRESET 127.0.0.1:57406
```

**Comment by AmbroiseCouissin** [comment]
Same issue here. No issue with `npm run dev` but `request to http://localhost:61014/_ipx/images/pharmacy-1.jpg?f=jpeg&s=640_545 failed, reason: connect ECONNREFUSED 127.0.0.1:61014` when doing `npm run generate`.

I'm using "@nuxt/image": "^0.4.1".

**Comment by dikaio** [comment]
Same here @AmbroiseCouissin `"@nuxt/image": "^0.4.1",`.

**Comment by pkpowell** [comment]
I get spurious errors like this running `yarn generate`. The number of errors varies with each build. 
Having `screens` defined in `nuxt.config.js` seems to make no difference.

**Comment by shpfive** [comment]
There needs to be a possibility of throttling the requests to static ipx provider.
I tried it by implementing https://www.npmjs.com/package/promise-parallel-throttle to the generate hook and don't have any issues now.

**Comment by kjkmr** [comment]
This is a quick and dirty work around.
https://github.com/kjkmr/nuxt-image/commit/5b44f6566b41eda21125663c781ddf487303affc

**Comment by dikaio** [comment]
Sweet, thanks for sharing @kjkmr.
