### ISSUE TITLE
Netflify IPX Error while nuxt generate

### ISSUE THREAD

**Issue by Clex1o1** [nuxt/image#211]
I have an error while deploying my site on netlify via `nuxt generate`. The error message in the Netlify console:
```
[error] [@nuxt/image] Unexpected response IPX Error (500)
```

**Comment by messismore** [comment]
Are you by any chance using git lfs? https://docs.netlify.com/large-media/requirements-and-limitations/#limitations

> Files tracked with Large Media are uploaded directly to the Netlify Large Media storage service on push, completely bypassing the site build. This saves build time, but also means that the files are not available to tools that process asset files during the build, such as Hugo’s image processing or the gatsby-image plugin. Depending on your needs, you may be able to replace this functionality with Netlify’s image transformation service.

**Comment by Clex1o1** [comment]
sorry you're right! Was my fault!
