### ISSUE TITLE
Using nuxt/image with nuxt/content

### ISSUE THREAD

**Issue by tusamni** [nuxt/image#223]
Anyone having issues using this with the nuxt/content module?

It's fine in dev, but as soon as I generate or push to Vercel the images break. They're not being generated, and the source isn't updating.

**Comment by benoitdemaegdt** [comment]
Hello @tusamni ,

I'm using **nuxt/image** with **nuxt/content** for a small side project hosted on Netlify.
So far everything is working fine.

Example (sorry, content is in french)
Md file : https://github.com/benoitdemaegdt/monpetitsommet/blob/master/content/articles/parcs-nationaux-france.md
Code : https://github.com/benoitdemaegdt/monpetitsommet/blob/master/pages/blog/_slug.vue
Live example : https://dev.monpetitsommet.fr/blog/parcs-nationaux-france

I guess the problem is related to Vercel 🤔

**Comment by tusamni** [comment]
Thanks! I'm doing something similar as you:

Markdown: https://github.com/tusamni/nuxtjs/blob/master/content/articles/new-camera-and-lenses.md
_Slug: https://github.com/tusamni/nuxtjs/blob/master/pages/blog/_slug.vue

Only difference I can see is that I'm using an image component instead of using <nuxt-img> directly. But even if I test using <nuxt-img> it still won't generate images using "npm run generate" in a local dev terminal.

Seems like you're running Cloudinary as well, I'm using static IPX, so it may have something to do with that.

**Comment by benoitdemaegdt** [comment]
Can you try moving your image from `/assets` to `/static`.
I think this is where your problem comes from.

Doc & example : https://image.nuxtjs.org/providers/ipx

**Comment by tusamni** [comment]
I'll give it a shot, though I do have this line in nuxt.config.js

```
provider: 'static',
dir: "assets/images",
```

Which I assume would cover the change to assets.

**Comment by tusamni** [comment]
I tried moving the folders to the static folder and changing the "dir" config setting, but no luck. 

Page images work fine, but images in the article don't end up getting generated by the image module.

**Comment by ririen** [comment]
This is a global problem with Vercel. This package does not seem to work properly with their edge network in any configuration.

**Comment by tusamni** [comment]
Seems like that is the case with Vercel, I can't get it to work at all unfortunately.

However, the other issue that I'm having is that I can't get the "static" provider (IPX) to generate any images from the .md files.

**Comment by tusamni** [comment]
I'm still trying to diagnose why my /pages/blog/_slug.vue page isn't generating any optimized images with this module.

It has something to do with the _slug.vue. Even if I hardcode an <nuxt-image> into that page, it won't generate the necessary responsive image sizes on the corresponding blog post with the provider set to "static".

I'm stuck.

**Comment by tusamni** [comment]
For those following along, I seem to have fixed the issue. Images from the .md files are now being generated, both in the frontmatter and the markdown content itself.

I'm not entirely sure what fix did it, but I did end up registering my image component as a global component as suggested here: https://nuxtjs.org/blog/creating-blog-with-nuxt-content/#adding-a-vue-component

Also I was trying to use kebab case component names, and was using <picture>. This was causing issues rending in the .md files. I tested <content-image> (all credit to @benoitdemaegdt) and all is working now. Feel free to browse my repository if anyone else is having issues getting static IPX image generation working on dev and production.

https://github.com/tusamni/nuxtjs

**Comment by tusamni** [comment]
Closing this since it seemed to be an issue with my implementation.

**Comment by madsh93** [comment]
Hi @tusamni
I am experiencing the same error. Your repository seems to be missing. Would you be willing to provide your solution again? :-)

**Comment by tusamni** [comment]
> Hi @tusamni
> I am experiencing the same error. Your repository seems to be missing. Would you be willing to provide your solution again? :-)

I'm sorry, but I've moved on from Nuxt for the time being and cleaned out my repositories. I don't have the code anymore.

Can you post your code and I'll be happy to take a browse through it.

**Comment by jovyllebermudez** [comment]
Same on my end. my svg file is 404 in /static/logo.svg

![image](https://user-images.githubusercontent.com/73716444/166093207-16ad10a8-0af2-4785-96b8-4d31f4efbc1e.png)
![image](https://user-images.githubusercontent.com/73716444/166093214-6eb120c8-b148-462b-a8a9-42e1851f7962.png)

**Comment by jovyllebermudez** [comment]
Opps sorry guys. my bad
i ded debug on building on local
i did add @ and it successfully worked
![image](https://user-images.githubusercontent.com/73716444/166094119-ffc299a2-4c6e-46a2-96b5-5ec68d9fa86b.png)
