### ISSUE TITLE
[0.4.6] Crtitical Error: Cannot find module './runtime/providers/static' 

### ISSUE THREAD

**Issue by Tragio** [nuxt/image#226]
Hello 🙂

The latest version, 0.4.6 is generating a critical error.

![Screenshot 2021-04-23 at 10 20 54](https://user-images.githubusercontent.com/5109593/115850252-9e31c200-a41d-11eb-891b-456351ffec63.jpg)

Thank you very much for all the amazing work.

cc: @pi0

**Comment by pkpowell** [comment]
Same here.

```
 FATAL  Cannot find module './runtime/providers/static' 
Require stack:
- /Users/phil/web/boltshauser-new/node_modules/@nuxt/image/dist/module.js
- /Users/phil/web/boltshauser-new/node_modules/@nuxt/core/dist/core.js

  Require stack:
  - node_modules/@nuxt/image/dist/module.js
  - node_modules/@nuxt/core/dist/core.js
```

**Comment by pi0** [comment]
Should be good with `@nuxt/image@0.4.7`. Sorry for regression (please reopen if still broken)

**Comment by petephm** [comment]
@pi0 How was this resolved? I'm getting this fatal error too on my nuxtjs build (although I'm not use nuxt/image).
