### ISSUE TITLE
Document the use of the dir option to define source image location

### ISSUE THREAD

**Issue by tanc** [nuxt/image#237]
This is a minor issue but I'm wondering whether its possible to keep images in say `assets/images` rather than `static/images` and be able to use them with with these components?

The reason I ask is everything in `static` gets put in `dist` and deployed, so my original high resolution source images will end up getting uploaded each time and being publicly available (if the url is known). This increases deployment size and time as source images are generally a few megabytes each. Ideally only the derivative generated images would end up in `dist`

**Comment by tusamni** [comment]
Yeah, that's possible. Here's my nuxt.config.js, keep in mind I'm using IPX static image generation, your success may vary if you're using another provider:

'''
buildModules: [
        // Nuxt Image module https://image.nuxtjs.org/components/nuxt-img
        ['@nuxt/image', {
            dir: 'assets/images',
            provider: 'static',
            staticFilename: '[publicPath]/images/[name]-[hash][ext]',
            screens: {
                xs: 400,
                sm: 640,
                md: 768,
                lg: 1024,
                xl: 1280,
                '2xl': 1536,
            },
        }],

**Comment by pi0** [comment]
PR welcome for both option and tip. Only this option should be used with caution only with ipx provider and also mentioning dynamic generated sizes not crawled during generate will be 404 with static target.

Most of providers (including vercel static) depend on original asset being accessable on production so they can do optimization on demand instead of taking build time.

**Comment by tanc** [comment]
Can you explain this a little bit more:

> dynamic generated sizes not crawled during generate will be 404 with static target

I’m happy to update the docs but I need to know that I’m writing the correct thing

**Comment by pi0** [comment]
With the image's static provider we can collect every image request/variant used during SSR rendering paths when crawling and generating. But there are situations it won't happen. Uncrawled pages, modals and tabs, client-only components. Normally static provider fallbacks to original source url. If it is not available users will get a 404 error.

**Comment by tanc** [comment]
@pi0 thanks for the clarification! I'll try to write something today

**Comment by tanc** [comment]
@danielroe thanks for the reminder! I’ve issued a PR, hopefully that covers it but feel free to change if I’ve misunderstood anything.
