### ISSUE TITLE
Issue with cropping in 0.4.7?

### ISSUE THREAD

**Issue by tusamni** [nuxt/image#238]
I was on 0.4.5 and cropping seems to be fine, however on 0.4.7 suddenly the crops are all way off. I rolled back to 0.4.5 and confirmed that the bug is gone.

I'm using static IPX.

**Comment by tusamni** [comment]
On 0.4.5, my image URL's in dev look like: 
```"/_ipx/posts/out-with-the-batis-on-to-zony/ice-metallic-green-930.jpg?f=webp&amp;s=1000_667"

On 0.4.7, they change to :
```/_ipx/posts/out-with-the-batis-on-to-zony/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=1500&amp;s=1000_1333"

**Comment by tusamni** [comment]
It's something to do with the "sizes" attribute, but I haven't been able to figure it out yet.

**Comment by tusamni** [comment]
Well, I'm still not sure of the issue, but I think it's got to do with the height property on srcset, for some reason they're all set to "1333" which is the original height.

```<img src="/_ipx/posts/new-camera-and-lenses/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=1500&amp;s=2000_1333" width="2000" height="1333" alt="Ice Metallic Green 930 Turbo" sizes="(max-width: 320px) 100vw, (max-width: 640px) 100vw, (max-width: 768px) 100vw, 1000px" srcset="/_ipx/posts/new-camera-and-lenses/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=480&amp;s=320_1333 320w, /_ipx/posts/new-camera-and-lenses/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=960&amp;s=640_1333 640w, /_ipx/posts/new-camera-and-lenses/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=1152&amp;s=768_1333 768w, /_ipx/posts/new-camera-and-lenses/ice-metallic-green-930.jpg?f=webp&amp;_cHeight=1500&amp;s=1000_1333 1000w" class="transition-all ease-in-out shadow-lg hover:shadow-xl transition-1000">

**Comment by pi0** [comment]
Hi @tusamni. Can you please try 0.4.8?

**Comment by tusamni** [comment]
Hey @pi0 thanks.

Still having issues. If I include the "sizes" attribute on an image it's giving me a weird crop. In the attached image below, I have the "sizes" attribute on the first image, but the other two don't have it and show correctly.

<img width="928" alt="Screenshot_1" src="https://user-images.githubusercontent.com/9271145/116432072-f564d780-a80d-11eb-95c6-ef424ab11f1a.png">

The generated code for that image is:

```
<img src="/_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=525&amp;s=350_2000" width="1333" height="2000" alt="Singer 911 in LA" sizes="(max-width: 320px) 100vw, (max-width: 640px) 100vw, (max-width: 768px) 300px, (max-width: 1024px) 350px, (max-width: 1280px) 350px, 350px" srcset="/_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=480&amp;s=320_2000 320w, /_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=960&amp;s=640_2000 640w, /_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=450&amp;s=300_2000 300w, /_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=525&amp;s=350_2000 350w, /_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=525&amp;s=350_2000 350w, /_ipx/pages/photography/recent02.jpg?f=webp&amp;_cHeight=525&amp;s=350_2000 350w" class="transition-all ease-in-out shadow-lg hover:shadow-xl transition-1000">

**Comment by tusamni** [comment]
I'm no expert at this, but it looks like it's the "?s=" attribute on the image URLs. The width is set correctly, but the height is the original height.

**Comment by tusamni** [comment]
So I can provide a little more insight here.

I have two identical images, just slightly different sizes: one is 1000x667 and one is 2000x1333.

My sizes option looks like this:
```
sizes: "md:100vw lg:510px"
```

The 1000px image crops fine, the 2000 one retains the original height.

1000px: dodge-demon-rear-wheel-Custom.jpg?f=webp&_cHeight=512&s=768_667
2000px: dodge-demon-rear-wheel.jpg?f=webp&_cHeight=512&s=768_1333

**Comment by danielroe** [comment]
I believe this has been resolved (see https://github.com/nuxt/image/commit/682b674809c2105283ba6896690454735f0a149a). If not, do let me know and I'll happily reopen
