### ISSUE TITLE
IPX fails for static site generation on GitHub Actions but works locally

### ISSUE THREAD

**Issue by JanHett** [nuxt/image#250]
First off: I love that automatic image optimisation is in development for nuxt!

On to my issue: when I build my project locally with either `nuxt` (dev server) or `nuxt generate` (static site generation) everything works perfectly. However, the `nuxt generate` command throws the error shown below on GitHub actions and does not produce optimised images.

```
Error:  [@nuxt/image] Unexpected response IPX Error (500)
```

The relevant pipeline is [here](https://github.com/JanHett/brotzeit-engineering/runs/2482421162?check_suite_focus=true).

Since I can't reproduce the issue locally and wasn't able to find related info in the documentation or discussions here, I'm at a bit of a loss as to where to start the search for the bug. Is it possible to make this error more verbose so I can get the context of the failure?

Side note: I believe errors like this should result in a non-zero exit code to make pipelines fail.

**Comment by JanHett** [comment]
Through some back-and-forth between GitHub and GitLab I figured out the source of the issue: a problem with GitHub's LFS meant the source images weren't there, i.e. the problem was entirely unrelated to nuxt/image or indeed IPX.

However, I would still suggest exiting generation with a non-zero exit code to make pipelines fail (to avoid accidentally merging sites without their images).

Since this isn't really a potential bug report anymore but rather a suggestion I'll close the issue now.

Thanks again for developing this module!

**Comment by Saltibarsciai** [comment]
Would like to see in pipeline which image fails to be optimized

**Comment by surgiie** [comment]
Wondering what work around or fix was found on your end? Im having this issue currently.

**Comment by MarioAda** [comment]
My issue was that the filename was `image.PNG`, but I used `image.png` in the code. Windows does not differentiate between uppercase and lowercase letters so it worked locally. However, `image.png` doesn't exist in a Linux environment. **rename your images.**
