### ISSUE TITLE
Sizes option with Cloudinary not working

### ISSUE THREAD

**Issue by MielPoule** [nuxt/image#262]
Hey !

When I use the sizes option on nuxt-img with Cloudinary provider, the urls that are generated are broke.

For example : 
`<nuxt-img
    src="anyimage.jpg"
    provider="cloudinary"
    sizes="sm:100vw"
    width="500"
    height="500"
  />`

Will generate urls like this one :
https://res.cloudinary.com/myaccount/image/upload/w_640,h_500,_cHeight_640/anyimage.jpg

**_cHeight** is not a valid parameter for Cloudinary and therefore urls are broken.

Thank you for this great plugin !

**Comment by pi0** [comment]
Thanks for issue. Should be fixed in next release.
