### ISSUE TITLE
Nuxt generate caching

### ISSUE THREAD

**Issue by lucadalli** [nuxt/image#270]
Is it possible to leverage the `nuxt.generate` caching behavior using checksums to avoid wastefully regenerating unchanged images?

**Comment by pi0** [comment]
Hi @lucadalli unfortunately not since generate is a runtume operation (fetching image from remote sources and providers may vary without source chance). But we might add local cache for ipx provider back (it is removed for now to maximize serverless support where fs isn't available)

**Comment by pi0** [comment]
Moved to https://github.com/unjs/ipx/issues/30
