### ISSUE TITLE
imagekit provider docs

### ISSUE THREAD

**Issue by riderx** [nuxt/image#271]
Hello i use imagekit i'm wondering if any one have already done the connector ?
@imagekit-developer

**Comment by pi0** [comment]
We already have [imagekit provider](https://github.com/nuxt/image/blob/main/src/runtime/providers/imagekit.ts). Testing and adding documentation would be cool!

**Comment by dosstx** [comment]
Hey @pi0 , I didn't see this thread yet, but I did pass the nuxt image link over to imagekit dev team and they are looking into it. I don't know if they even know you had already done something. I use imagekit.io and would love to see this in the next release. I'll send this link over to imagekit team. Thanks for all your work in the Nuxt universe!
