### ISSUE TITLE
<nuxt-img> versus static/image/logo.icon/png

### ISSUE THREAD

**Issue by jmonagas** [nuxt/image#285]
Hello:

I have tried to create my own folder/directory with the optimized images for my logo/icon (stored at static images (.png) along with the icon file. 

However, every time I run the command NPM RUN DEV the folder with my images (saved at .nuxt >> dist\client >> icons is fully replaced/overwritten by the Nuxt.Js logos (and I can't get rid of them).

Only my icon file is shown as my icon/favicon/shortcut (stored at static) at the tab of the pages(index, services, contact), but not the 512px512px logo whenever I check my SEO/social/image/meta-index (which is the base image for facebook, twitter, etc)

I checked the documentation and videos, and it says that I just need to add/store my 512x512px .png at static.

To test this, I saved my logo in assets >> images and voila, it worked.

Can you help me with this one? What is missing?

I also installed >> npm install -D @nuxt/image

and added it to my nuxt.config.js

```js
 image: {
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
      '2xl': 1536,
    },
  },
```

as indicated at https://image.nuxtjs.org/components/nuxt-img 

But it did not work, So, the Nuxt.Js logos (different sizes) keep showing at .nuxt/dist/client/icons

Cheers,

Jose G. Monagas
https://jmonagas-portfolio.ml/

=============

The manifest reads as follows:

```json
{
  "name": "webdevelopment",
  "short_name": "webdevelopment",
  "icons": [
    {
      "src": "/_nuxt/icons/icon_64x64.780b31.png",
      "sizes": "64x64",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_120x120.780b31.png",
      "sizes": "120x120",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_144x144.780b31.png",
      "sizes": "144x144",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_152x152.780b31.png",
      "sizes": "152x152",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_192x192.780b31.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_384x384.780b31.png",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_512x512.780b31.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "any maskable"
    }
  ],
  "start_url": "/?standalone=true",
  "display": "standalone",
  "background_color": "#ffffff",
  "lang": "en"
}
```

**Comment by pi0** [comment]
Hi @jmonagas. `static/icon.png` and `assets/icon.png` are handled by [pwa module](https://pwa.nuxtjs.org/). You can specify desired sizes using [icon.sizes](https://pwa.nuxtjs.org/icon#options)

If you need resized version URL of icon, there are two ways:

- Using pwa module, use `$icon(512)` to get URL (considering it is included in `pwa.icon.sizes[]`) 
- Using image module, use `$img('/icon.png', { width: 512 })` to get URL (considering `icon.png` is in `static/` directory)
- Using image module, use `<nuxt-img src="/icon.png" width="512">` to display 512px version of icon as a `<img>` tag.

**Comment by jmonagas** [comment]
Hi Pooya:

Thanks for the documentation/references.

Please see one PDF attachment. I tried all the tricks I could, but in the end, it did not work.

Every time I enter NPM RUN DEV or NPX NUXT GENERATE or NPX NUXT START, the folder/directory with the icons that I created/sized/saved manually, is deleted/replaced by the same Nuxt.Logo shown in the PDF.

So, I saved one copy of the logos/icons, then I ran the commands => NPM RUN DEV and NPX NUXT GENERATE and NPX NUXT START one by one, then I manually replaced the images/icons/ in the DIST folder/directory generated via NPX NUXT GENERATE.

Please note, the server is running with the [ DIST \ ] folder/directory, and ignores the [ DIST ].

I am going to create a github repo, then I will clone the repo to my apache2 server. My next question is --> Which folder/directory should I run in my server? Is it the .nuxt/dist or the created DIST generated via NPX NUXT GENERATE ?

This is very confusing right now.

Thank you kindly for your help!

---
Jose G. Monagas

________________________________

**Comment by pi0** [comment]
> Which folder/directory should I run in my server? Is it the .nuxt/dist or the created DIST generated via NPX NUXT GENERATE ?

If `target: static` is set, `nuxt generate` and top level `dist/`. If `target` is not set or is `server`, `nuxt start`.


PDF attachment is not available in GitHub but waiting for repository to check.

**Comment by jmonagas** [comment]
Hi Pooya:

I forwarded the pdf attachment to your account == ***@***.******@***.***>

The github repo that I just created is at == https://github.com/jmonagas/My-First-Nuxt-Project.git

I think the default configuration for static/icon.png is ignoring the logos/icons that I intend to use on my website. Please take a look at the pdf attachment with full details.

Cheers,

Jose G. Monagas
***@***.***
Calgary, Canada

---
Jose G. Monagas

________________________________
