### ISSUE TITLE
dist folder missing

### ISSUE THREAD

**Issue by mickaelchanrion** [nuxt/image#287]
Hey 👋 ,

I installed the module (v0.4.10) and updated my nuxt config. After running  the dev server, I get this error:

`Error: Cannot find module '/home/[PATH_TO_PROJECT]/node_modules/@nuxt/image/dist/module.js'. Please verify that the package.json has a valid `

If I `ls` the `@nuxt/image` folder in the node_modules, the dist folder is actually missing

**Comment by pi0** [comment]
Hi. Can you please try recreating `node_modules` and lockfiles? (seems not missing in [unpkg](https://unpkg.com/browse/@nuxt/image@0.4.10/))
