### ISSUE TITLE
static target points original path when route by vue-router

### ISSUE THREAD

**Issue by comfuture** [nuxt/image#297]
I just replaced image resize module to @nuxt/image from @pivale/nuxt-image-loader-module.
`nuxt generate` to generates html files for each route and `<nuxt-img />` component points resized image properly but when route to another page by using vue-router, It renders img tag with original image url.

Am I missed anyting?

https://github.com/comfuture/changkyun.kim/blob/master/nuxt.config.js#L102-L142
https://github.com/comfuture/changkyun.kim/blob/master/pages/index.vue#L4

## Step to reproduce:
- open https://changkyun.kim/ renders well,
- move to /about by clicking "about" on top navigation menu and see broken image.
- reload page and found fixed image path again.

**Comment by pkpowell** [comment]
This started with v0.4.11. v0.4.10 works as expected.
