### ISSUE TITLE
omit dist/_nuxt/img for static build

### ISSUE THREAD

**Issue by pkpowell** [nuxt/image#308]
Is it possible to omit the `dist/_nuxt/img` directory when running `nuxt generate`? 
This directory seems to contain the original images, which in our case amounts to about 2G (we have lots of hirez images). The `dist/_nuxt/images` dir by contrast is only 87ish MB, and as far as I can tell these images aren't used in prod.

**Comment by pkpowell** [comment]
Seems this might be related to the webpack rule `test: /\.(png|jpe?g|gif|svg|webp|avif)$/i,`
I guess jpeg and png are handled by nuxt/image and svgs are being handled by webpack/file-loader which is grabbing all images.
Weirdly this doesn't happen on another site with a very similar setup.
Any tips on how to stop this from happening?

**Comment by pkpowell** [comment]
You're right. We have a mix of jpg, png and svg files, and I import the svgs in a separate img tag. If I remove that the `dist/_nuxt/img` dir goes away.
Earlier on nuxt/image displayed svgs (which was awesome) but atm it seems to only convert them to jpeg/webp, which I want to avoid. 
I can't move the svgs to their own folder which I assume would help, as the cms puts all media in the same location and moving stuff would "break" the cms (forestry.io).
Is there a way to dynamically import the svgs without grabbing the other content? 
```
<img
            v-if="src.ext('svg')"
            type="image/svg+xml"
            :loading="lazy"
            :src="require(`~/assets/uploads/${src}`)"
            :alt="alt"
            :class="[...imgClass]"
            @load="loaded"
            :style="{...opacity, ...displaySize}"
/>

```

**Comment by danielroe** [comment]
This may work:
```
:src="require(`~/assets/uploads/${src}.svg`)"
```

**Comment by pkpowell** [comment]
Perfect, that worked. Thanks for clearing up webpack/require, I've been bitten by that before...
Having a "pass thru" option for svgs or even svgo optimisation would be handy, but I can easily live with this solution.
