### ISSUE TITLE
CSS class on <nuxt-picture> is appended to <picture> and not <img>

### ISSUE THREAD

**Issue by lucien144** [nuxt/image#317]
CSS classes on `<nuxt-picture>` goes to HTML element `<picture>`, however, it should go to `<img>` element. Current solution pretty much blocks devs from using utility classes/frameworks.

### Code
```vue
<nuxt-picture
	:src="post.featured_media"
	width="600"
	height="300"
	class="w-100 br-8"
/>
```

### Actual result
```html
<picture class="w-100 br-8">
	<source type="image/webp" srcset="...">
	<img src="....">
</picture>
```

### Expected result
```html
<picture>
	<source type="image/webp" srcset="...">
	<img src="...." class="w-100 br-8">
</picture>
```

**Comment by LukaHarambasic** [comment]
I disagree with this even if I have similar problems. What if `webp` is the right format to display? Then all your styling would be useless? And as `<nuxt-picture> is a drop-in replacement for the native <picture> tag` this works as expected ([docu](https://image.nuxtjs.org/components/nuxt-picture)).

**Comment by dannyalder88** [comment]
@LukaHarambasic I think the <img> tag inside a <picture> tag is always used to render the image and so its class list would apply no matter which source is used. But you are right, there may be times when you would want to target the <picture> container with a class as well. 

@lucien144 Maybe an `img-class` prop might help in this case to apply classes directly to the <img> tag? Otherwise, you could target it in the CSS with `.picture-class img {}`. This could get annoying for CSS frameworks using utility classes though.

**Comment by LukaHarambasic** [comment]
> @LukaHarambasic I think the img tag inside a picture tag is always used to render the image and so its class list would apply no matter which source is used. But you are right, there may be times when you would want to target the picture container with a class as well.

You are right, thanks! I wasn't aware of this.

> The browser will consider each child <source> element and choose the best match among them. If no matches are found—or the browser doesn't support the <picture> element—the URL of the <img> element's src attribute is selected. The selected image is then presented in the space occupied by the <img> element.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture


> @lucien144 Maybe an `img-class` prop might help in this case to apply classes directly to the img tag? Otherwise, you could target it in the CSS with `.picture-class img {}`. This could get annoying for CSS frameworks using utility classes though.

This could be also used as a workaround for an issue I opened: https://github.com/nuxt/image/issues/320

**Comment by dannyalder88** [comment]
@LukaHarambasic Yeah it would be a work around for #320. However, you can also use a deep selector to solve your issue:

```
<nuxt-picture class="image" ... />

<style lang="sass" scoped>
    .image
        // Styles for picture tag
        ::v-deep img 
            // Styles for img tag
</style>
```

**Comment by hmaesta** [comment]
> you can also use a deep selector to solve your issue

That's a workaround, but definitely _not_ a solver for people using utility classes like Tailwind CSS.

**Comment by shadow81627** [comment]
Would adding an img slot to nuxt-picture help? I can look at making a PR for it tomorrow.

**Comment by shadow81627** [comment]
related #309

**Comment by Nik96i** [comment]
Why don't fix such an easy but critical issue? I have the same problem and don't want to do forking, etc. 
I have to write a custom component from scratch.
thanks.
