### ISSUE TITLE
[Feature request] Minify/Compress images

### ISSUE THREAD

**Issue by LukaHarambasic** [nuxt/image#321]
Hi,
I already love this package and I haven't found an issue about this: 
What about minifying/compressing images within this package? 
So, not only resizing but getting rid of unused information by having the same quality. Basically, a build in version of https://tinypng.com/. 

I would be happy to contribute this if you agree that it's worth it. Something like https://github.com/semiromid/compress-images/ could be used.

Cheers,
Luka

**Comment by pi0** [comment]
Hi @LukaHarambasic

You can use `quality` property/modifier to reduce the size of images. (default for IPX/Sharp is %80 for jpeg, png and webp). Only SVG modification is not supported at the moment.

Do you have some benchmarks that `compress-images` can perform better than sharp for reducing size?

**Comment by LukaHarambasic** [comment]
> Do you have some benchmarks that compress-images can perform better than sharp for reducing size?

Thank's for this question, I did some tests and the outcome of nuxt-img is already perfect, not sure why my last tests showed something different.
