### ISSUE TITLE
Animated images don't work

### ISSUE THREAD

**Issue by IgnisDa** [nuxt/image#351]
As an example,

```html
 <nuxt-img
        src="/team/images/image.gif"
        height="200px"
        width="200px"
      />
```
does not work. But

```html
  <nuxt-img
        src="https://media3.giphy.com/media/Jzxgefavt2aB2/giphy.gif"
        height="200px"
        width="200px"
      />
```
works fine. This is probably some problem on part of the default provider `ipx`. Is there a way to fix this?

**Comment by shadow81627** [comment]
https://github.com/unjs/ipx/issues/35

**Comment by IgnisDa** [comment]
@shadow81627 I looked at the issue, but could not figure out how to use it with `@nuxt/image`. Could you please tell me?

**Comment by shadow81627** [comment]
I haven't tried it myself but ipx appears to support an animated option https://github.com/unjs/ipx#modifiers. If `@nuxt/image` doesn't pass the modifier to ipx properly we may need to make a PR to add support for it.

**Comment by IgnisDa** [comment]
I noticed that this works for `@nuxt/image@0.5.0`

```html
<nuxt-img
        :src="`/team/gifs/${image}.gif`"
        :alt="`GIF for ${image}`"
        :modifiers="{ animated: true }"
      />
```
`height` and `width` modifiers don't work at all.

But there is no documentation for this. Should I add it?

**Comment by shadow81627** [comment]
> But there is no documentation for this. Should I add it? I can make a PR.

yeah try making some docs, it seems like a feature worth mentioning.

**Comment by pi0** [comment]
Thanks, @IgnisDa sure is worth mentioning. It is undocumented since it only works by converting `gif` to `webp` and without doing resize operations (feature pending for underlying sharp library improvement that we can include as a note to the docs :)

**Comment by IgnisDa** [comment]
@pi0 Made a PR, could you please check?
