### ISSUE TITLE
feat: unsplash support

### ISSUE THREAD

**Issue by productfrontenddeveloper** [nuxt/image#353]
https://unsplash.com/developers

Can you add support for this?

**Comment by shadow81627** [comment]
I would love to try and find some time to contribute a unsplash provider following this documentation https://unsplash.com/documentation#dynamically-resizable-images

**Comment by shadow81627** [comment]
@productfrontenddeveloper while developing a first party unsplash provider I discovered the ipx provider has support for using an alias and the example uses unsplash. https://image.nuxtjs.org/api/options#alias

**Comment by shadow81627** [comment]
@pi0 I am trying to understand the IPX alias options better, is it possible to use an external provider eg. unsplash and then use IPX to generate static images? I want to statically generate external images to be used offline.

**Comment by productfrontenddeveloper** [comment]
@shadow81627 thank you, wow :)
