### ISSUE TITLE
IPX crashes with ERR_INVALID_CHAR (Invalid character in statusMessage)

### ISSUE THREAD

**Issue by phof** [nuxt/image#375]
[x-posted from unjs/ipx/issues/42, as requested by @pi0]

**Steps to reproduce (with Nuxt sandbox):**
1) Spin up sandbox, `https://codesandbox.io/s/github/nuxt/image/tree/main/example`
2) Send request (manually of via built-in browser), e.g.: `GET https://7wy70.sse.codesandbox.io/_ipx/images/%01`
3) See console error:
![Screenshot 2021-07-29 at 09 02 27](https://user-images.githubusercontent.com/37412/127446815-1928d61f-14ec-4246-abb1-3a13e5969fee.png)

**Steps to reproduce (with IPX):**
1) Start IPX, `npx ipx`
2) Submit a request such as `GET /test/%00`, or `GET /test/%01`, etc
3) IPX crashes with error:

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_CHAR]: Invalid character in statusMessage
    at new NodeError (node:internal/errors:363:5)
    at ServerResponse.writeHead (node:_http_server:323:11)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:764:9)
    at ServerResponse.end (node:_http_outgoing:853:5)
    at /ipxissue/node_modules/ipx/dist/cli.js:543:11 {
  code: 'ERR_INVALID_CHAR'
}
```

This successfully crashes my Nuxt app.

**Comment by pi0** [comment]
Should be solved in latest IPX release. Thanks for reporting.
