### ISSUE TITLE
IPX crashes with ERR_INVALID_CHAR (Invalid character in header content ["Content-Type"])

### ISSUE THREAD

**Issue by phof** [nuxt/image#376]
**Steps to reproduce (with Nuxt sandbox):**
1) Spin up sandbox, `https://codesandbox.io/s/github/nuxt/image/tree/main/example`
2) Send request (manually of via built-in browser), e.g.: `GET https://7wy70.sse.codesandbox.io/_ipx/images/mountains.jpg?f=%0d`
3) See console error:
![Screenshot 2021-07-29 at 10 51 55](https://user-images.githubusercontent.com/37412/127462416-26510280-3245-43c9-b620-ca2ff9c13386.png)

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Type"]
      at ServerResponse.setHeader (_http_outgoing.js:564:3)
      at /ipxissue/node_modules/ipx/dist/index.js:508:13
```

Likely related to nuxt/image/issues/375 (and unjs/ipx/issues/42)

**Comment by pi0** [comment]
Should be solved in latest IPX release. Thanks for reporting.
