### ISSUE TITLE
npm run generate never exits process when using @nuxt/image

### ISSUE THREAD

**Issue by ElnuDev** [nuxt/image#381]
I'm having an issue where `npm run generate` never exits the process even after it is done generating all the static images and the rest of the site. I didn't have this issue before using `@nuxt/image`. What can one do to fix this? Thank you!

**Comment by AamirAlam** [comment]
I found the solution to this issue , 

this is happening because you mist be connecting to a db in your server , you need to close the db connection using nuxt hooks inside `nuxt.config.ts`. file 


`  hooks: {
    close: async (go: Nuxt) => {
      await mongoose.disconnect();
    },
  },`

**Comment by Baroshem** [comment]
Closing as the solution was provided :)
