### ISSUE TITLE
Change letterbox color

### ISSUE THREAD

**Issue by darthf1** [nuxt/image#388]
Images with `fit="contain"` get a black letterbox which I would like to change.

```html
<nuxt-img src="/sample.png" height="40" width="125" fit="contain" />
```

Is it possible to change the letterbox color from black to something else?

**Comment by stuible** [comment]
I also require this feature in order to be able to use contain

**Comment by jeanmatthieud** [comment]
It seems to work with the modifier 'b' with IPX as provider.
eg: `<nuxt-img src="/sample.png" height="40" width="125" fit="contain" :modifiers="{ b: '#FFFFFF' }" />`

I found it in the [github ipx repo](https://github.com/unjs/ipx/issues/33)

I think that it's linked to [this source code](https://github.com/nuxt/image/blob/main/src/runtime/providers/ipx.ts):
```js
const operationsGenerator = createOperationsGenerator({
  keyMap: {
    format: 'f',
    fit: 'fit',
    width: 'w',
    height: 'h',
    resize: 's',
    quality: 'q',
    background: 'b'
  },
  joinWith: ',',
  formatter: (key, val) => encodeParam(key) + '_' + encodeParam(val)
})
```
