### ISSUE TITLE
Couldn't find any versions for "commander" that matches "^2.20.3"

### ISSUE THREAD

**Issue by MMMikeM** [nuxt/image#390]
Hi there

I'm aware this is not entirely the correct scope here, but was hoping that I might be able to get suggestions as to a possible workaround.

I am getting build pipelines failing after adding nuxt-image, by way of

nuxt image > ipx > xss > commander^2.20.3

This version seems to be unpublished though, with the latest 2. version being 2.20.1.

Can anyone perhaps suggest a workaround? I'd love to implement nuxt image in our project, but it's also important to keep our build pipeline working.

Thanks

**Comment by danielroe** [comment]
This is no longer relevant.
