### ISSUE TITLE
Image source is not working when having random array of url images 

### ISSUE THREAD

**Issue by BennaceurHichem** [nuxt/image#394]
I want to have a random image from an array of images, where each image has : `url`, `author`, `authorUrl `and `unsplashUrl`, 
``` 
private images = [
    {
      url:
        'https://images.unsplash.com/photo-1605478328994-f93e98217da7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
      creditUrl:
        'https://unsplash.com/@pawel_czerwinski?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
      author: 'Pawel Czerwinski2',
      unsplashUrl:
        'https://unsplash.com/s/photos/backgrounds-violet?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
    },
    {
      url:
        'https://images.unsplash.com/photo-1579792773782-79ddd1c4e6c1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
      creditUrl:
        'https://unsplash.com/@pawel_czerwinski?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
      author: 'Pawel Czerwinski',
      unsplashUrl:
        'https://unsplash.com/s/photos/backgrounds-violet?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
    },
.
.
.
  ];
```

I created a function that returned one of these images randomly to show it in the screen 
` 
   this.selectedImage = this.images[Math.floor(Math.random() * this.images.length)];
`
then I attributed the url of selected image into nuxt-img src 
`      <NuxtImg  :src="selectedImage.url" class="w-full h-screen" />
`

and also the author and their URL credit to the page to look like that 
![image](https://user-images.githubusercontent.com/31354135/130770702-e642deb1-7352-4cf7-8040-dfe551fb9b3e.png)

### Problem
the problem is that a weird behavior occurred which is that an image is shown but the credit and the author of this image is not the convenient author, it shows rapidly an image that is not the same as the selected image object

after I checked the nSrc attribute in devtool I saw that the url is referred to as an image and nuxt-img show another one! 

is there any explanation and how can this works ?

P.S: I tried to choose the selected image from the array in `mounted()` and `created() `and none of them works

**Comment by danielroe** [comment]
Two things might cause this:

1. You are rendering one URL on server and another on client. (To fix, set the image in mounted or use `useState` to persist the random image.)
2. You are generating a static site and Nuxt can only optimise the image it knows about at generate time.
