### ISSUE TITLE
How to add dynamic CDN to 'domains'

### ISSUE THREAD

**Issue by jonathanmelville** [nuxt/image#396]
I am trying to transform remote images from a CDN. I can get back dynamic hostnames from my requests, such as `https://scontent-atl3-2.cdninstagram.com /....`

How do add a dynamic hostname to `domains`? I tried a wildcard and it doesn't work.

**Comment by Graff1406** [comment]
Hello. Did you resolve the problem?
I have the same problem. If did you resolve can help me?

**Comment by jonathanmelville** [comment]
@Graff1406 It looks like there currently isn't a way to use dynamic urls.

However as a workaround I ended up rewriting the dynamic URL in my component before outputting it, so `https://scontent-atl3-2.cdninstagram.com` would be re-written as `https://scontent.cdninstagram.com`. This seems to work in my case.

**Comment by Baroshem** [comment]
Closing as the workaround was provided.

Feel free to reopen if needed :)
