### ISSUE TITLE
File format conversion performance impact server

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/image#399]
Hello, i would like to clarify if image format conversion is done on the client side or node server side?

If it is done in the server then, will it be a huge performance hog since it won't be caching converted images for reuse?

I have a lot of images and user uploaded images all in webp and i need to convert to png or jpg for apple devices or safari users

**Comment by Baroshem** [comment]
All optimizations are done on the server side :)

Closing as it is a really old issue.

Please feel free to reopen if needed :)
