### ISSUE TITLE
Using google cloud storage bucket

### ISSUE THREAD

**Issue by msoler75** [nuxt/image#408]
Hi, I am using Google Cloud Storage to store media files in a bucket.

¿Is there any config to use with IPX provider to get these remote images work?

¿Or maybe need a new provider?

**Comment by msoler75** [comment]
Ok, I see that if i put in nuxt.config.js this configuration it works!

nuxt.config.js:

```
image: {
    domains: ['https://storage.googleapis.com']
},
```

It implies using remote images. 

My question is: the IPX server get the remote image and locally do the transforms. Is it true?

**Comment by smilburn1990** [comment]
Does this work for you then @msoler75 - I've tried adding this for my s3 bucket 

```
  image: {
    domains: ["anddinestorage.s3.eu-west-2.amazonaws.com"],
  },
```

and I still get this in my dev tools on localhost

`<img src="/_ipx/w_1000/Images/logos/logo-white.webp" width="1000" alt="logo">`

```
        <nuxt-img
          src="/Images/logos/logo-white.webp"
          alt="logo"
          width="1000"
          @click.native="
            $router.push({
              path: '/',
              query: { discount: $route.query.discount },
            })
          "
        />
```

**Comment by Baroshem** [comment]
Closing as the solution was provided :)
