### ISSUE TITLE
[Docs] Homepage light theme text color

### ISSUE THREAD

**Issue by HZooly** [nuxt/image#409]
It seems that homepage text colors are broken using light theme.

`Optimized images` spam has `text-white` class whereas I'm using light theme.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/7328625/132770684-31f2382e-094a-4d6e-8ef6-b1c1e5006f29.png">

**Comment by damisparks** [comment]
> Hi, even with #410, light theme doesn't seem to be fixed.
Right @HZooly the light theme has not changed even till now.

**Comment by the94air** [comment]
Same over here, it haven't been fixed since the last time I visited the docs which was weeks ago if not months 😂. It's out of control!!!

**Comment by the94air** [comment]
Pushed a PR #471

**Comment by marekbrze** [comment]
I don't think that it works well right now... 

The text is dark on the dark image. 

![Zrzut ekranu 2022-01-28 o 15 28 46](https://user-images.githubusercontent.com/1033055/151565668-931c8492-616d-4ba0-8151-48becdf942e7.png)

**Comment by damisparks** [comment]
Haha looks like we are messing with the page 😂
Time for another PR.

**Comment by marekbrze** [comment]
Yup, there is a need for an conditional background SVG for light/dark themes;)

**Comment by marekbrze** [comment]
Maybe previously there was just a problem with loading the background SVG?

**Comment by pi0** [comment]
https://github.com/nuxt/image/commit/22d0235baefafc9c23d71dcb9af1ce3a21d41704

Thanks for noticing the issue. We will replace docs soon with a much better package.
