### ISSUE TITLE
Storyblok Provider doesn't handle of SVG's as expected

### ISSUE THREAD

**Issue by mrillusion** [nuxt/image#415]
Current Behaviour
When using the Storyblok provider with the base URL set to "https://img2.storyblok.com" to get SVG assets they are transformed into .png assets rather than the original .svg format.

Expected Behaviour
When using the Storyblok provider to get assets that could be either vector or raster asset types there should be a way to preserve vector (.svg) assets. This would stop these vector assets from using the base URL "https://img2.storyblok.com" and instead use "https://a.storyblok.com" with no image transformation parameters. This would ensure .svg assets are not transformed into .png assets rather than the original .svg

**Comment by Schascha** [comment]
I run in the same issue today. All my SVG assets looked blurry. As a quick fix you can disable the Stoyblok provider for SVGs only.

**Comment by Baroshem** [comment]
Closing as the workaround was provided :)
