### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by CavalcanteLeo** [nuxt/image#417]
Is avif supported?

Can it be the first option, with fallback to webp, then fallback to jpg/png

**Comment by shadow81627** [comment]
Image format support depends on the image provider being used. I can see in the code that ImageKit supports avif.

https://github.com/nuxt/image/blob/main/src/runtime/providers/imagekit.ts#L103

**Comment by CavalcanteLeo** [comment]
Amazing
