### ISSUE TITLE
It doesn't say in the documentation that to make nuxt-image work 'ssr' needs to be true

### ISSUE THREAD

**Issue by ctwhome** [nuxt/image#418]
I have been wondering why it wasn't working at all nuxt image after running `yarn generate`  
It could be great if the documentation mentions it, as well as examples of using different providers.

Thanks

**Comment by shadow81627** [comment]
I believe ssr is only needed for the default IPX static provider to be able to transform images. Other image providers shouldn't require ssr.

A pull request to update the docs is welcome.
