### ISSUE TITLE
Does not work image optimization on an external website

### ISSUE THREAD

**Issue by Graff1406** [nuxt/image#419]
Can't optimize images on the fly from a remote website.
Example:
```
<nuxt-img src="https://upload.wikimedia.org/wikipedia/ru/b/b7/Enterthematrix.jpg" format="webp" />

// nuxt.config.js
export default {
  image: {
    domains: ['https://upload.wikimedia.org']
  }
}
```
What am I doing wrong?

**Comment by nathanchase** [comment]
You'll want to ensure you have `nuxt-image` in your `modules` and NOT your `buildModules` if you aren't using some external image provider.

So in your `nuxt.config.js`:
```
export default {
  modules: [ // <--- use this if you want to just use the built-in image processing
    '@nuxt/image',
  ]
}
```
NOT
```
export default {
  buildModules: [  // <--- only if you are using some outside image vendor
    '@nuxt/image',
  ]
}
```

See https://image.nuxtjs.org/providers/ipx for more information using the default ipx provider.
