### ISSUE TITLE
How to optimize Nuxt Img for Bootstrap grid columns?

### ISSUE THREAD

**Issue by dosstx** [nuxt/image#425]
If you use Bootstrap's grid system to lay out your pages, and there are [six breakpoints](https://getbootstrap.com/docs/5.1/layout/grid/#grid-options):

![image](https://user-images.githubusercontent.com/6342102/134321904-4fced27a-3d4d-493b-9b8d-8ba95eb237bb.png)

Do I try to configure the nuxt-img sizes to match the column sizes for each breakpoint? In my case, I am just using the `md`  columns to keep things simple like so:

```
<div class="container">
    <div class="row>
        <div class="col-md-8>
            <nuxt-img
            provider="cloudinary"
            :src="post.publicId"
            width="2450"
            height="3600"
            class="img-fluid card-img-top"    // <----- 'img-fluid' tells image to take width of its container
            sizes="XXXX" //<--- I am not sure what sizes to put here???
              />
        </div>
        <div class="col-md-4">
            ....etc....
        </div>
    </div>
</div>
```

Can someone provide some guidance on how I can tailor the Nuxt-img component best for Bootstrap grid columns? Thank you!

**Comment by dosstx** [comment]
Alright, think I found some ideas: 

Bootstrap has the following breakpoint sizes:

![image](https://user-images.githubusercontent.com/6342102/134330816-3636f0c1-677d-409a-8f74-37c980bc41ae.png)

So, I updated my `<nuxt-img>` component like so:

```
          <nuxt-img
            provider="cloudinary"
            :src="post.publicId"
            :width="post.width"
            :height="post.height"
            class="img-fluid card-img-top"
            sizes="sm:576px md:768px lg:992px xl:1200px xxl:1400px"
          />
```

It seems to work good....but it would be great if I could get a second pair of eyes here. Thanks!

**Comment by dosstx** [comment]
No, I am still not understanding how "sizes" attribute works. I have my code like so:

```
<template>
  <main class="container mt-5">
    <div class="row mb-3">
      <div class="col-md-8">
        <nuxt-img
          provider="imagekit"
          class="img-fluid"
          width="2048"
          height="1365"
          src="/12909467_553362454846586_5546587330991507170_o_LHb_mTBdV.jpg"
          sizes="xxl:100vw xl:100vw lg:100vw md:100vw sm:100vw xs:100vw"
        />
      </div>
      <aside class="col-md-4 mh-100 bg-secondary">
        <p>.col-md-4 sidebar</p>
      </aside>
    </div>
  </main>
</template>
```

And `nuxt.config.js` like so:

```
    screens: {
      xs: 0,
      sm: 576,
      md: 768,
      lg: 992,
      xl: 1200,
      xxl: 1400
    }
```

And then with a hard refresh, I reload my page and see that I am still being served a 1400 width image despite the client viewport being only `1070` pixels wide. Shouldn't I get served a smaller/less-wide image and NOT a 1400 wide image?

![image](https://user-images.githubusercontent.com/6342102/134535789-e5a087b3-c139-4c5e-97e6-a7cbbebe6f5a.png)

Codesandbox repo (using Bootstrap classes, btw!):

https://codesandbox.io/s/elastic-shadow-k3yo2?file=/pages/index.vue

**Comment by dosstx** [comment]
Btw, for those wondering, the free tier with Imagekit is more generous than Cloudinary's (almost double)

**Comment by abhinavr4** [comment]
Hey @dosstx, is your device's DPR (device pixel ratio) more than 1?
For example if device's DPR is 2 and viewport width is 1070, the browser would pick image from srcset (you can check out sizes+srcset of the image in the Elements tab) that is closer to width = 1070 x 2, ie. 2140px, which in this case is `w-1400`.

If you are confused about how `sizes` and `srcset` work, you may want to give [this](https://imagekit.io/responsive-images/) a read.

**Comment by dosstx** [comment]
> Hey @dosstx, is your device's DPR (device pixel ratio) more than 1?
> For example if device's DPR is 2 and viewport width is 1070, the browser would pick image from srcset (you can check out sizes+srcset of the image in the Elements tab) that is closer to width = 1070 x 2, ie. 2140px, which in this case is `w-1400`.
> 
> If you are confused about how `sizes` and `srcset` work, you may want to give [this](https://imagekit.io/responsive-images/) a read.

My device's pixel ratio is 1. 

Here's another screenshot. Notice the image width is set to about 625px but the downloaded image is coming in at width of 1200. 

![image](https://user-images.githubusercontent.com/6342102/134803586-69585025-18f9-4ac8-86d6-ccb0acbdef30.png)

**Comment by dosstx** [comment]
Adding `{ 'http-equiv': 'Accept-CH', content: 'DPR, Viewport-Width' },` to the nuxt config file seems to have resolved it.
