### ISSUE TITLE
Is it possible to use (runtime) ipx provider with target:static site?

### ISSUE THREAD

**Issue by gabrielsze** [nuxt/image#437]
Hello, I noticed the static generation of images is cool, but for my use case if I'm generating thousands of images on my site, it doesn't seem too feasible to be generating all the responsive images at generate time.

I'm still using a `target:static` site, and I'm wondering if I could call the ipx middleware on runtime, but I noted here in the documentation that

https://image.nuxtjs.org/providers/ipx

> You don't need to follow this section if using target: 'static'.

But it also mentions here (https://image.nuxtjs.org/getting-started/providers) that

> The default provider for Nuxt Image is ipx or static (for target: static). Either option can be used without any configuration.

I'm wondering if I could still setup the IPX provider section for my static site, or even better, decide when the nuxt-img are provided on the IPX runtime, and also select which to generate statically (I believe it's with `provider="static"` inside the nuxt-img tag). 

I have followed the ipx middleware setup as seen here: https://image.nuxtjs.org/providers/ipx, but my images are still statically generated when running `npm run generate`.

- adding `@nuxt/image` to my modules, 
- installing ipx,
- creating a middleware,
- adding /_ipx to serverMiddleware

I'm a bit confused about whether I can be using the IPX runtime config for my static site. I tried using `provider="ipx"` inside the nuxt-img tag and it doesn't seem to work, throwing some "Error: Unknown provider: ipx". How should I go about using runtime IPX in static mode?

**Comment by elglogins** [comment]
Any updates here?

**Comment by danielroe** [comment]
This is possible if you have a custom IPX server and wish to deploy a static site. You can configure the `baseURL` for this purpose.
