### ISSUE TITLE
Latest fixes have not been pushed to npm

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/image#443]
As the title says, image events are really needed, but they are not available because a new tag hasn't been pushed.

**Comment by creazy231** [comment]
@pi0 any updates on this? 👀

**Comment by MurmeltierS** [comment]
**For everyone struggling:**
We've forked and published with the current changes: https://www.npmjs.com/package/@brandboostinggmbh/image

If you want u can use the following for now.

`npm i @nuxt/image@npm:@brandboostinggmbh/image`

This will use our forked version under the alias @nuxt/image.

**Comment by danielroe** [comment]
This is no longer relevant - published npm package is kept up-to-date.
