### ISSUE TITLE
Expose $Img for external Testing

### ISSUE THREAD

**Issue by ferdynator** [nuxt/image#448]
We have a component that uses direct access to `$img.getImage` to generate image URLs. To test this component we write simple jest snapshot tests. Unfortunately I have not been able to inject `$img` into our component to run tests without mocks. This is our current approach:

```js
describe('OurImageComponent', () => {
  function buildWrapper () {
    return mount(
      OurImageComponent,
      {
        propsData: { // ...
        },
        mocks: {
          $img: {
            getImage (url, options) { // some mock implementation
            },
          },
        },
```
( Inspired by https://github.com/nuxt/image/blob/main/test/unit/utils/mount.ts )
This works well but with mocking the actual call we generate unclean snapshot files and not really exact URLs.
Is there a way to create an instance of `$Img` manually in a test environment or would it be an option to expose the  
[`createImage`](https://github.com/nuxt/image/blob/f22ae016912470c083c7b565fd67947a8f441093/src/runtime/image.ts#L8) function so one could create an instance manually?

**Comment by Baroshem** [comment]
Closing as not planned due to lack of traffic on this issue.

Feel free to reopen if needed :)
