### ISSUE TITLE
Multiple formats

### ISSUE THREAD

**Issue by CavalcanteLeo** [nuxt/image#451]
Avif is better than webp, but some of modern browser doesn't support avif yet, like safari.

Would be great if we could use multiple formats, something like:

```vue
 <nuxt-picture
    src="image.png"
    provider="static"
    :formats="['avif','webp']"
/>


 <nuxt-picture
    src="image.png"
    provider="static"
    :formats="['svg']"
/>
 ```

then returns 

```vue
<picture>
    <source srcset="image.avif" type="image/avif">
    <source srcset="image.webp" type="image/webp">
    <source srcset="image.png" type="image/png">
    <img src="image.png">
</picture>
```

this way, all modern browser will have the best options to display

**Comment by realandrew** [comment]
+1 for this. Really surprising it's not a feature yet, part of the benefit of `picture` over `img` is the ability to specify many formats, so being limited to 2 (preferred and fallback) for `nuxt-picture` really stinks.

**Comment by vedmant** [comment]
+1 isn't this implemented yet? This should be one of the most common usages when serving multiple formats from API.

**Comment by Rekryt** [comment]
+1

**Comment by agracia-foticos** [comment]
same issue

**Comment by CavalcanteLeo** [comment]
@pi0 have you seem this?

**Comment by CavalcanteLeo** [comment]
finally 🚀👏🏼
