### ISSUE TITLE
File(s) not found on linux build (target: static)

### ISSUE THREAD

**Issue by fleshgordo** [nuxt/image#468]
**Setup**

nuxt: 2.15.8
@nuxt/image: 0.6.0
target static

nuxt.config.js
```
buildModules: ['@nuxt/image'],
 image: {
      domains: ['http://127.0.0.1:8000'],
    },
```

including images like below
`<nuxt-img v-if="article.image" :src="article.image" />`

**Problem**
Builds fine on osX (with `npm run generate`) but when building on linux debian I am getting file not found errors on images that were included via nuxt-image (same node versions on both systems):

` ERROR  Unexpected response IPX: File not found: /home/user/vue-nuxt/static/imagefolder/screenshot.png `

On darwin the build outputs:

`✔ Generated static image dist/_nuxt/imagefolder/screenshot.png                                          @nuxt/image 15:09:29`

**Comment by iamandrewluca** [comment]
Try to add in nuxt-config, `dir` property for image module

```ts
export default {
  image: {
    dir: 'dist'
  }
}
```

**Comment by Baroshem** [comment]
Closing as the workaround was provided :)
