### ISSUE TITLE
Latest changes still not released

### ISSUE THREAD

**Issue by creazy231** [nuxt/image#473]
Documentation is updated but since the last merge there was no new release to NPM etc.
Really would like to use some of the new features without using patcher 😞

**Comment by MurmeltierS** [comment]
**For everyone struggeling:**
We've forked and published with the current changes: https://www.npmjs.com/package/@brandboostinggmbh/image

If you want u can use the following for now.

`npm i @nuxt/image@npm:@brandboostinggmbh/image`

**Comment by pi0** [comment]
The latest changes were just released as `0.6.1`. Sorry for the late release.
