### ISSUE TITLE
Storyblok provider does not update image url format for new storyblok image service

### ISSUE THREAD

**Issue by gavmck** [nuxt/image#474]
The new storyblok image service, https://a.storyblok.com, appears to have a new url format.

https://www.storyblok.com/docs/image-service#migrating-from-the-previous-version-of-the-service

The storyblok image provider does not appear to update the url for this format and the image returns a 403 as if it wasn't there.

**Comment by madebyfabian** [comment]
Yes, seems that nuxt/image still does not provide support for it, found this issue from a few months ago with basically the same problem. As a workaround, we can create our own Providers and just add the url manually. #450

**Comment by studiolathe** [comment]
@gavmck I'm facing the same issue – were you able to resolve with with @madebyfabian suggestion? 

Unfortunately, I can't seem to get a custom provider working..

Thanks!

**Comment by gavmck** [comment]
@studiolathe I used the old baseUrl, which seemed to work.

```js
image: {
      domains: ['a.storyblok.com'],
      storyblok: {
        baseURL: 'https://img2.storyblok.com',
      },
},
```

**Comment by jorgemartins-uon** [comment]
[PR](https://github.com/nuxt/image/pull/497) created to use the new Image Service API syntax.
