### ISSUE TITLE
imgAttrs is not working in nuxt-picture 

### ISSUE THREAD

**Issue by vadim-kor** [nuxt/image#478]
imgAttrs seem to be ignored when rendering. 
It renders this property to html, but the value is "[Object, object]" instead of string, and it's apliet to the picture tag instead of the imge tag.

**Comment by ddegooijer** [comment]
Have the same issue, any update?

**Comment by ddegooijer** [comment]
Made a PR for the fix, hopefully it will be merged asap.

**Comment by Khezcute** [comment]
Maybe @pi0 can help us pls, I have the same issue

**Comment by chrisRodgersAirpos** [comment]
Experiencing this issue too, has anyone found a fix for it?
