### ISSUE TITLE
External hosted IPX

### ISSUE THREAD

**Issue by jeanmatthieud** [nuxt/image#483]
Hi,

I want to be able to use an IPX provider, but with an IPX instance hosted on another server than the one running Nuxt.
Currently, the IPX provider source code uses the nuxt `context.base` URL, and cannot be changed :

*/src/runtime/providers/ipx.ts:29*
```js
url: joinURL(nuxtBase, baseURL, params, encodePath(src))
```

I would like to be able to change the base URL (http(s)://xxxx) of the server running the IPX instance.

**Comment by jeanmatthieud** [comment]
Moreover, the `base` property doesn't exists on `nuxtContext`
cf. https://nuxtjs.org/docs/internals-glossary/context/

**Comment by treboryx** [comment]
Hosting your own IPX instance (https://github.com/unjs/ipx) means you're creating a custom provider, therefore you might need to take a look at https://image.nuxtjs.org/advanced/custom-provider

**Comment by jeanmatthieud** [comment]
I believe that after merging ma correction, it will be possible to use the existing IPX provider, but with an external baseURL.

**Comment by jeanmatthieud** [comment]
This is linked to #339
