### ISSUE TITLE
IPX: Forbidden host: localhost

### ISSUE THREAD

**Issue by mohsenMJ** [nuxt/image#486]
I am using @nuxt/image package to serve my images on my project. here is my package information

package.json file
```
"@nuxt/image": "^0.6.0",
 "nuxt": "^2.15.8",
"ipx": "^0.9.2",
```

nuxt.config.js
```
build:{
    '@nuxt/image',
},
image: {
      domains: ['http://localhost:8000']
},
```

as mentioned inside docs. 

my nuxtjs projects is served on localhost:4000 and my backend which is in Laravel is served on localhost:8000 port number.
when I try to get images from my server it returns 

`IPX: Forbidden host: localhost`

Please help me

thank you

**Comment by AntoineAA** [comment]
Hi,
Same error here, using `"@nuxt/image": "^0.6.1"`.

Best regards,
AA

**Comment by narduin** [comment]
Same with `"@nuxt/image": "^0.6.2"`

**Comment by julioglobal100** [comment]
same!

**Comment by alejosky** [comment]
Bump!

**Comment by makadiwa** [comment]
Any one resolved the IPX Error: Error: Forbidden path Issue?

**Comment by pi0** [comment]
Would you please provide a reproduction of your setup? 🙏🏼

**Comment by filippodicostanzo** [comment]
same issue

**Comment by narduin** [comment]
> Would you please provide a reproduction of your setup? 🙏🏼

I tried to create a simple reproduction [here](https://github.com/narduin/nuxt-image-ipx).  
I hope it helps!

**Comment by narduin** [comment]
Thanks @pi0, I can't believe I did not try that…

**Comment by makadiwa** [comment]
@narduin Thanks for the reply, I tried your solution but still I get forbidden error at <nuxt-img src="/oui.jpg" />, however adding localhost to the src ( <nuxt-img src="http://localhost:3003/oui-express.jpg" />) works.

@pi0 I tried your suggestion as well but that doesn't work for me

image: {
    domains: ['localhost']
  },

**Comment by pi0** [comment]
@makadiwa Do you also get "Forbidden Host" error by removing port from config?

**Comment by makadiwa** [comment]
@pi0 I'm getting Forbidden path error after removing port from config.

_Failed to load resource: the server responded with a status of 403 (IPX: Forbidden path)_

**Comment by sa-rang** [comment]
GET http://localhost:3006/_ipx/s_328x224/homepage/apple.png 403 (IPX: Forbidden path)

**Comment by pi0** [comment]
Can you please try with 0.7.1 and fresh lock? If issue persists, would be happy to reopen and track.

**Comment by Ahrorbek7** [comment]
Error while using nuxt-img 0.7.1:
Failed to load resource: the server responded with a status of 404 (Not Found)

nuxt.config:
 buildModules: ["@nuxtjs/tailwindcss","@nuxt/image",],
 image: {
    domains: ['localhost'] 
  },
usage:
<nuxt-img :src="item.image_beverage_left_url" alt="leftImg" format="webp" />
