### ISSUE TITLE
Pass options to custom providers

### ISSUE THREAD

**Issue by Alphability** [nuxt/image#49]
After reading nuxt/image's core code (and especially the **loadProvider function**), the only way I found to pass options to a custom provider is by **setting its name as the provider's path**.
By using this method we won't be able to use the provider's name when setting the nuxt-image component's src attribute.

I could be nice to **have an easier way to give arguments to the provider**, instead of hardcoding things within it.

<img width="433" alt="Capture d’écran 2020-10-22 à 18 49 44" src="https://user-images.githubusercontent.com/37068300/96904407-5c888480-1497-11eb-8ba1-7dcec32b293e.png">

**Comment by farnabaz** [comment]
The documentation is not completed yet, You can define your provider using the object notation:  
```js
image: {
  providers: {
    custom: {
      name: "custom", // optional
      provider: "~/provider/path",
      options: {
        // ... options here
      }
    }
  }
}
```

**Comment by farnabaz** [comment]
I've update provider docs: https://image.nuxtjs.org/custom-provider#register-provider
