### ISSUE TITLE
Cannot create property '_img' on boolean 'true'

### ISSUE THREAD

**Issue by FalkoJoseph** [nuxt/image#493]
<img width="1482" alt="Schermafbeelding 2022-02-28 om 18 12 59" src="https://user-images.githubusercontent.com/556086/156027504-8b89436c-813e-464a-bd48-538e4edbb85c.png">

Hi guys,

When adding `"@nuxt/image",` to my `buildModules` I receive the following error:

> Cannot create property '_img' on boolean 'true'

Here's the versions of the packages I'm using:

* "@nuxt/image": "^0.6.2"
* "nuxt": "^2.15.8"

```
buildModules: [
    "@nuxtjs/eslint-module",
    "@nuxtjs/stylelint-module",
    "nuxt-windicss",
    "nuxt-font-loader",
    "@nuxt/image",
  ],
```

Any idea how I can fix this? When I remove this line from the `buildModules` the error disappears. 🤔

**Comment by pi0** [comment]
Can you please provide a reproduction? 🙏🏼  

`_img` is being accessed from `ssrState.nuxt` and payload data. Both shouldn't be `true` it is strange...

**Comment by Baroshem** [comment]
Closing as this is quite old issue and there is no reproduction.

Feel free to reopen it if needed :)
