### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by pi0** [nuxt/image#500]
Currently working on a local branch to prepare an image module for Nuxt 3. It was unfortunately too early state to open PR but will do it ASAP and meanwhile use this PR as an informative announcement. Intial support for Nuxt 3 is hopefully in April.

Changes:
- Use Nuxt Kit
- Fix nitropack issues with ipx/sharp bundling
- Support static generation with Nuxt 3 via nitropack and align image module with it
- Migrate tests to vitest and new framework test-utils

**Comment by Baroshem** [comment]
This is great @pi0!

I would be more than happy to help as I really liked the experience of the image module.
If you can divide the work on this module so that I could pick some of the work from you, I am in it 100% :)

**Comment by pi0** [comment]
Certainly! There is an undividable migration phase but we surely need to iterate over for an ideal Nuxt 3 integration! Will make subtasks if you like to pick.

**Comment by Rigo-m** [comment]
Can't wait! I'm on it for some subtasks as well.

**Comment by nathanchase** [comment]
> * Fix nitropack issues with ipx/sharp bundling

This is what I've been waiting for. If this and the Nuxt auth-module both get updated and are working with Nuxt Bridge, I think I'd be able to finally use Nuxt Bridge with my Nuxt 2 project successfully and serve the app with Nitro - and perhaps have a stepping stone towards a full migration to Nuxt 3.

**Comment by stafyniaksacha** [comment]
What about using https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite ? 

It has a small issue: when building, it output url as:
```ts
const _imports_1$4 = "/__NUXT_BASE__/myjpeg.3ad25e08.webp";
```

instead of
```ts
const _imports_1$4 = buildAssetsURL("/__NUXT_BASE__/myjpeg.3ad25e08.webp".replace("/__NUXT_BASE__", ""));
```

using:
```ts
import { defineNuxtConfig } from 'nuxt3'
import { imagetools } from 'vite-imagetools'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  vite: {
    plugins: [imagetools()],
  },
})
```

**Comment by Rigo-m** [comment]
> What about using https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite ?
> 
> It has a small issue: when building, it output url as:
> 
> ```ts
> const _imports_1$4 = "/__NUXT_BASE__/myjpeg.3ad25e08.webp";
> ```
> 
> instead of
> 
> ```ts
> const _imports_1$4 = buildAssetsURL("/__NUXT_BASE__/myjpeg.3ad25e08.webp".replace("/__NUXT_BASE__", ""));
> ```
> 
> using:
> 
> ```ts
> import { defineNuxtConfig } from 'nuxt3'
> import { imagetools } from 'vite-imagetools'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   vite: {
>     plugins: [imagetools()],
>   },
> })
> ```

How is this relevant with this issue? `vite-imagetools` is a completely different package.

**Comment by stafyniaksacha** [comment]
> How is this relevant with this issue? `vite-imagetools` is a completely different package.

Hum, I was wondering if we can combine both usage, like:
```html
<nuxt-picture
  src="/images/mountains.jpg?format=webp&grayscale"
  width="3750"
  height="2500"
  sizes="xs:200px md:500px lg:1024"
/>
```

**Comment by pi0** [comment]
> What about using https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite ?

Image module, unlike webpack, vite plugins, is not a build-time image optimizer :)

**Comment by stafyniaksacha** [comment]
> Image module, unlike webpack, vite plugins, is not a build-time image optimizer :)

Oh yes, I get it, though it was!

**Comment by kubo6472** [comment]
I'm like: just why does it error out. Then I thought about it not supporting nuxt, but quickly and swiftly dismissed that thought. Welp, should probably add a disclaimer into the docs.

**Comment by kstraszewski** [comment]
Is releasing in April still on track?

**Comment by anchorDev** [comment]
Any updates, i'm still getting this error.
![image](https://user-images.githubusercontent.com/25384840/164506473-3455b0a3-a5fb-490d-a941-826da100b70e.png)

**Comment by KahrLu** [comment]
When will nuxt3 support this repo?

**Comment by amirnbcode** [comment]
Yes plz update us. any new news for nuxt-image?

**Comment by JsusMillan** [comment]
when would it have compatibility with nuxt3 ?

**Comment by mrnasil** [comment]
@pi0 @antfu Any uptade?

**Comment by Atinux** [comment]
Image is part of our next tasks, like mentioned by Pooya in the issue description, we will keep you updated as soon as we are on it 😊

**Comment by megazoor** [comment]
> Any updates, i'm still getting this error ? ![image](https://user-images.githubusercontent.com/25384840/164506473-3455b0a3-a5fb-490d-a941-826da100b70e.png)

I am also getting this - any ideas?

**Comment by pi0** [comment]
Intial Nuxt 3 support started: https://github.com/nuxt/image/discussions/548
