### ISSUE TITLE
Fit inside not working as expected

### ISSUE THREAD

**Issue by nagman** [nuxt/image#506]
I have this image:
![image](https://user-images.githubusercontent.com/16116486/164034106-d9aee04b-fef0-4ba9-a52d-a156eb841493.jpg)

Which, when resized through this url: `http://localhost:3000/_ipx/f_jpg,fit_inside,s_1800x2700/img/test.jpg`, outputs like this:
![7a2a0360-bd2d-4c2d-a5b2-811819cb422d](https://user-images.githubusercontent.com/16116486/164034466-f0e1e17d-d967-467a-bbd9-414c15c4d901.jpeg)

Note that it's using `fit_inside` and `s_1800x2700`.

I don't understand why, but I wonder if it's related to how the `inside` fit is calculated.  
Because no matter how many zeros I add to the size, it'll stay at 111 x 38 in the output image.

**Comment by Baroshem** [comment]
Closing as it is a really old issue.

Please feel free to reopen if needed :)
