### ISSUE TITLE
Vuetify Image Component Support?

### ISSUE THREAD

**Issue by shadow81627** [nuxt/image#51]
I am using [Vuetify Image component](https://vuetifyjs.com/en/components/images) and [nuxt-optimized-images module](https://marquez.co/docs/nuxt-optimized-images/). I am considering changing from using local image assets to using cloudinary but unfortunately [nuxt-optimized-images does not support this](https://github.com/juliomrqz/nuxt-optimized-images/issues/223). I have a hero image component that I am considering changing to use cloudinary and this module looks promising. Is there a way to use vuetify `v-img` component with this module? Would it be possible to add a slot to the `nuxt-image` component and use slot props on the `v-img`?

Here is how I am using `nuxt-optimized-images` and `vuetify` in my hero image component.

```vue
<template>
  <v-container class="pa-0 hidden-print-only" style="max-width: 1785px">
    <v-row no-gutters align="center" justify="center">
      <v-col cols="12" align-self="center">
        <v-card :color="color || backgroundColor(src)[0]" flat dark tile>
          <v-img
            :lazy-src="_src(src).placeholder"
            :src="_src(src).src"
            :srcset="_src(src).srcSet"
            :height="height"
            width="1785"
            sizes="(max-width: 1785px) 100vw, 1785px"
            :gradient="gradient"
          >
            <slot>
              <v-container
                class="fill-height align-items-end justify-start"
                fluid
              >
                <v-row align="center" justify="center">
                  <v-col class="text-center" cols="12">
                    <h1 v-if="heading" class="mb-4 text-shadow">
                      {{ heading }}
                    </h1>
                    <h2 v-if="subheading" class="subheading text-shadow">
                      {{ subheading }}
                    </h2>
                  </v-col>
                </v-row>
              </v-container>
            </slot>
          </v-img>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  props: {
    heading: { type: String, default: null },
    subheading: { type: String, default: null },
    gradient: {
      type: String,
      default: 'rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)',
    },
    height: { type: [Number, String], default: 500 },
    color: {
      type: String,
      default: null,
    },
    src: {
      type: String,
      default: './header-bg.jpg',
    },
  },
  methods: {
    backgroundColor: require.context(
      '~/assets/img?lqip-colors',
      true,
      /\.(png|jpe?g).*$/,
    ),
    _src: require.context(
      `~/assets/img?resize&sizes[]=320&sizes[]=600&sizes[]=900&sizes[]=1785&sizes[]=4686&placeholder&format=webp`,
      true,
      /\.(png|jpe?g).*$/,
    ),
    cover: require.context(
      `~/assets/img?resize&size=1200&format=jpg`,
      true,
      /\.(png|jpe?g).*$/,
    ),
  },
  head() {
    return {
      meta: [
        {
          hid: 'og:image',
          property: 'og:image',
          content: `${this.$config.BASE_URL}${this.cover(`${this.src}`).src}`,
        },
        {
          hid: 'og:image:width',
          property: 'og:image:width',
          content: this.cover(`${this.src}`).width,
        },
        {
          hid: 'og:image:height',
          property: 'og:image:height',
          content: this.cover(`${this.src}`).height,
        },
      ],
    };
  },
};
</script>

```

**Comment by farnabaz** [comment]
> Is there a way to use vuetify v-img component with this module?

The module injects a utility into Vue context. This utility could be used to resize and optimize images using specific provider. For now it has general functionality and you may need to rewrite most of `nuxt-image` login by yourself. But in the near future this utility will be rich enough to support your needs.

> Would it be possible to add a slot to the nuxt-image component and use slot props on the v-img?

Could explain why do you require a slot in the image components? I believe you can design your layout without the slot.

**Comment by shadow81627** [comment]
@farnabaz sorry I couldn't see the utility in the documentation. If I can get the optimized src and set from the utility then I wouldn't need the slot. Could you please provide an example of the utility in use or add it to the docs usage page?

I am looking for a simple way to get the srcset for optimized images. The slot usage I was looking for was something like this:

```vue
<nuxt-image sets="300,300:600,600:900" format="webp" src="/nuxt-icon.png">
    <template v-slot="{placeholder, src, set, height, width, sizes}">
      <v-img :lazy-src="placeholder"
            :src="src"
            :srcset="set"
            :height="height"
            :width="width"
            sizes="sizes" />
    </template>
</nuxt-image>
```

Or maybe for optimizing a background image:

```vue
<nuxt-image sets="300,300:600,600:900" format="webp" src="/nuxt-icon.png">
      <template #default="{ src }">
        <div
          :style="`
          position: relative;
          overflow: hidden;
          background-size: cover;
          background-image: url('${src}');
        `"
        />
      </template>
    </nuxt-image>
```

**Comment by farnabaz** [comment]
As you may notice, the module is under development and the feather set of utility does not complete. That's why we don't mention it in docs.  

> I am looking for a simple way to get the srcset for optimized images   

The utility will be the solution for it

Please wait for the first alpha release of the module. It will be anounced by [Nuxt official account ](https://twitter.com/nuxt_js).  Until then do not use image module in production.

**Comment by shadow81627** [comment]
@farnabaz Thanks, I am looking forward to the alpha release.

**Comment by jmarshall9120** [comment]
Is a utility for this use case now present?  I am trying to integrate images with vuetify and nuxt-image right now.

**Comment by MrDizzystick** [comment]
> Is a utility for this use case now present? I am trying to integrate images with vuetify and nuxt-image right now.

I think what you're looking for is here — there's an example using Vuetify, too:
https://image.nuxtjs.org/api/$img

**Comment by shadow81627** [comment]
@jmarshall9120

I am using `@nuxt-image` and `vuetify` in my personal website [here is a link to my config file](https://github.com/shadow81627/daim/blob/master/nuxt.config.js#L212-L216) that sets the responsive image breakpoints to be the same as vuetify. If there are any issues or hard to use thing you come across while using `@nuxt-image` and `vuetify` together I would love to hear your feedback. I would love to make the integration better.
