### ISSUE TITLE
Segementation Fault when @nuxt/image is installed in project?

### ISSUE THREAD

**Issue by rabbitfufu** [nuxt/image#512]
I have been @nuxt/image (0.6.2) with nuxt on node 14 for a long time with great results.

I have not made any changes to my development environment recently.

However, starting today, when I run 'npx nuxt', my project seems to compile fine, but as soon as I navigate to localhost, nuxt exits with a segmentation fault.

> ℹ Waiting for file changes                                                                                               11:44:12
> ℹ Memory usage: 389 MB (RSS: 537 MB)                                                                                     11:44:12
> ℹ Listening on: http://localhost:3000/                                                                                   11:44:12
> zsh: segmentation fault  npx nuxt

After some experimentation, I have discovered that removing @nuxt/image from the project fixes this problem.  So that is somehow related.

I have already tried deleting the entire node_modules folder and running npm install again -- however the problem recurs.

I am not sure how to go about troubleshooting this from here.  Has anyone else encountered this?

**Comment by rabbitfufu** [comment]
Okay, so it looks like downgrading to 0.5 of @nuxt/image fixed the issue for me.
Would still be good to have some insight into this if anyone has an idea.

**Comment by Amar1432** [comment]
any updates on this issue??

**Comment by jeanmatthieud** [comment]
Same issue going from nuxt@0.6.0 to nuxt@0.6.2; I didn't try 0.6.1

I'm using internal IPX.

**Comment by stuible** [comment]
I am also running into this issue on Node 14.  I am not able to upgrade to 16 at this time because doing so appears to break sass compatibility.

**Comment by Baroshem** [comment]
Closing as the solution was provided by Pooya and there is no further traffic on this issue.
