### ISSUE TITLE
adding support for uploadcare provider

### ISSUE THREAD

**Issue by theopaolo** [nuxt/image#513]
[Uploadcare](https://uploadcare.com/) comes pre-configured with Netlify CMS, popular for managing a Nuxt websites.

Trying to follow the doc to create a custom provider but it's a bit too obscure for my skill level.

Any help is welcome

Cheers,

**Comment by luc122c** [comment]
Hi @theopaolo, did you make a start on this? I'd be happy to help, as their [URL API is well documented](https://uploadcare.com/api-refs/url-api/#tag/Image-geometry).
