### ISSUE TITLE
Importing components directly

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/image#515]
Is there a way I can import the `nuxt-img` and `nuxt-picture` components explicitly? I have a helper which I need to pass components to, but the global components aren't available there.

I.e. `import { NuxtImg } from '@nuxt/image'`

**Comment by andresespinosapc** [comment]
Did you solve it? I have the same problem, I need this to type a component's props.

**Comment by davestewart** [comment]
I solved it with:

```
import NuxtImg from '../../node_modules/@nuxt/image/dist/runtime/components/nuxt-img.mjs'
```

**Comment by danielroe** [comment]
This should be possible with `import { NuxtImg } from '#components'` in Nuxt 3.
