### ISSUE TITLE
AVIF Support via ipx (native SSR provider)

### ISSUE THREAD

**Issue by nathanchase** [nuxt/image#517]
https://image.nuxtjs.org/components/nuxt-img#format indicates that .avif files are not supported, yet they're supported in sharp (https://sharp.pixelplumbing.com/api-output#avif) and in ipx (https://github.com/unjs/ipx).

I tried `format="avif"` on nuxt-img, but that didn't work. It just reverted to the incoming format with no format change.

Is this planned?

**Comment by lumos94** [comment]
i would also like to know

**Comment by pi0** [comment]
It is already landed in latest sharp and ipx and also in the docs.
