### ISSUE TITLE
Getting ipx error when running in dev/prod mode

### ISSUE THREAD

**Issue by olegdon** [nuxt/image#519]
I installed latest @nuxt/image module, set everything for _imgix_ provider, but when running dev/prod getting this error
`[@nuxt/image] ipx is an optional dependency for local image optimization and is not properly installed. Please try npm install or yarn install again.`

What could be wrong here?

**Comment by pi0** [comment]
Hi @olegdon. It is an open bug (#379) that provider will be always loaded. Let's track it there.
