### ISSUE TITLE
Support for other units than px

### ISSUE THREAD

**Issue by theolavaux** [nuxt/image#522]
It would be nice if we could use `em`s for `image.screens` as well as `rem`s for `sizes`. The current code is hardcoded in pixels for `image.screens` and `sizes` only allows `px` and `vw`.

**Comment by Baroshem** [comment]
Closing due to no traffic on this feature and the fact that Nuxt Image is designed in a similiar way as TailwindCSS responsive Design that uses PX -> https://tailwindcss.com/docs/responsive-design
