### ISSUE TITLE
Using `@nuxt/image` with `ipx` with a local middleware as endpoint

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/image#539]
Hello, I have a question. 

I want to use a proxy in a middleware (it takes care of adding the request header in the fetch of the resource, it is an async call: token query).

But now I have the problem that I don't know how to define the `alias` for an endpoint that runs with a **random** port on generate. I need an alias that addresses the generate port or the possibility to define the generate port.

Currently I get the port in the `listen` event, but this is too late to configure `@nuxt/image` with `ipx`.

Thanks! 🙂

**Comment by Baroshem** [comment]
Hey,

This is a rather old issue but maybe you can try to use a certain Nuxt lifecycle hook?

https://nuxt.com/docs/guide/going-further/hooks
