### ISSUE TITLE
Sanity provider doesn't recognise CDN paths

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/image#544]
I'm running a server rendered version of Nuxt.js and I've got the Sanity provider set up like so:
- `@nuxt/image` version 0.6.2 in `modules`
- `image.provider` set to `sanity`
- `image.sanity.projectId` set to my project ID (is correct, since same variable used for fetching data)

Before setting Sanity as the provider, everything worked fine. Now I'm getting a terminal warning on every image:
> An invalid image asset ID was passed in: https://cdn.sanity.io/images/[project-id]/production/[random-image-id]-691x869.png

And all images are broken, showing just the image size in the path like so: https://cdn.sanity.io/images/[project-id]/production/.1790x1629.png?auto=format. It's almost like this module isn't expecting the original path to include the size attributes, but haven't had too much time to dive into the source code!

A few things I've tried:
- Moving the module to `buildModules`, but now realising that's for static builds
- Explicitly setting the provider on the component instances, but that doesn't make sense since it's clearly using Sanity hence the bug

Have I set something up incorrectly?

**Comment by adamchipperfield** [comment]
Right, figured this one out. It's expecting the image reference and not the full CDN path.

Do we see a use case for allowing the full path to be passed? Looks like it could be factored into the `getMetadata` method.

**Comment by EmilyFlocc** [comment]
@adamchipperfield please could you provide an example of how you got this working? I am also getting the urls like https://cdn.sanity.io/images/%5Bproject-id%5D/production/.1790x1629.png?auto=format which are erroring

**Comment by treboryx** [comment]
> @adamchipperfield please could you provide an example of how you got this working? I am also getting the urls like https://cdn.sanity.io/images/%5Bproject-id%5D/production/.1790x1629.png?auto=format which are erroring

use the ref id instead, the random string between prodution and the dimensions

sanity returns image object that was a ref inside

**Comment by Baroshem** [comment]
Closing as the solution was provided.
