### ISSUE TITLE
@load not working

### ISSUE THREAD

**Issue by EmilyFlocc** [nuxt/image#570]
My @load method isn't being triggered, even though the image has loaded? Anyone know why this might be?

My images are coming from Sanity.

`
<template>
  <nuxt-img
    :loading="lazy ? 'lazy' : 'eager'"
    format="webp"
    :src="src"
    @load="handleLoad"
  />
</template>

<script>
export default {<br>
  props: {<br>
   image: {<br>
      type: Object,<br>
      required: true,<br>
    },<br>
    lazy: {<br>
      type: Boolean,<br>
      default: true,<br>
    },<br>
  },<br>
  computed: {<br>
    src() {<br>
      return this.$imgUrl(this.image).auto('format').url()<br>
    },<br>
  },<br>
  methods: {<br>
    handleLoad() {<br>
      console.log('Image loaded!')<br>
    },<br>
  },<br>
}<br>
</script>
`

**Comment by SleepiestAdam** [comment]
+1 - running into the same issue when using CloudFlare as a provider.

**Comment by danielroe** [comment]
This should now be resolved.
