### ISSUE TITLE
fallbackImage will not work when with a own placeholder image

### ISSUE THREAD

**Issue by Quineone** [nuxt/image#577]
```js
<nuxt-img
  v-bind="$attrs"
  placeholder="/images/loading.svg'"
  @error="setFallbackImage"
/>
```

maybe:
```js
mounted() {
    if (this.nPlaceholder) {
      ...
      img.onerror = () => {
        this.$refs.img.src = this.nMainSrc
        this.placeholderLoaded = true
      }
    }
    ...
  }
```

**Comment by Atinux** [comment]
Happy to give a reproduction? 🙏

**Comment by Atinux** [comment]
@jibbewillem I just tested locally and it works without prefixing with `/_ipx/_`

Do you use a specify provider as default @jibbewillem ?

**Comment by jibbewillem** [comment]
Thanks for the reply @Atinux . I checked again and, I'm not sure what changed, but it works fine now. Must have made a typo or a restart of the dev server helped or something.

**Comment by Atinux** [comment]
No worries!
