### ISSUE TITLE
[nuxt-img] support responsive attribute

### ISSUE THREAD

**Issue by pi0** [nuxt/image#58]

**Comment by farnabaz** [comment]
fixed in https://github.com/nuxt/image/commit/7e3f80ba798eee2c267d77fb68b8b4cd16704866 & https://github.com/nuxt/image/commit/845579bf9d7b324712bf11f54d89a205853fd7a3#diff-b4219a2e94c622f8a0ae7bb03a3d86f799a1344e59d5f7c4dd4f66200ffda908
