### ISSUE TITLE
Double folder structure in .output folder

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/image#581]
Hello,

I remarked that I had twice my image folder structure when I was building my app. See below :

Under `_nuxt` folder I have an empty folder structure :

![Capture d’écran 2022-08-04 à 11 59 57](https://user-images.githubusercontent.com/85166574/182820869-916a5d64-502a-4466-9b48-61ce10235a35.png)

and under the `public` folder I have the complete folder structure with the images :

![Capture d’écran 2022-08-04 à 12 00 16](https://user-images.githubusercontent.com/85166574/182821462-dd73364d-d515-4161-8325-6a0ed53fcd85.png)

here is the config I am using in my `nuxt.config.js` file :

```js
import path from 'path'
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: [
    '@nuxt/image-edge'
  ],
  image: {
    provider: 'ipx',
    screens: {
      sm: '576',
      md: '768',
      lg: '992',
      xl: '1200',
      '2xl': '1680'
    }
  }
})
```

**Comment by danielroe** [comment]
I believe this will be fixed in the next Nuxt RC which will ship with Vite 3 (or you can try the edge channel now: https://v3.nuxtjs.org/guide/going-further/edge-channel/).

**Comment by BenjaminOddou** [comment]
@danielroe it's resolve with rc-7. Thank you for the update 😄
