### ISSUE TITLE
$img utility for Composition API

### ISSUE THREAD

**Issue by ijkml** [nuxt/image#594]
I know this is still a WIP, but the docs only show how to use the utility on Options API. Is there currently a way to import the utility directly? Or better still,  grab it from `useNuxtApp`?

**Comment by Diizzayy** [comment]
>  Or better still, grab it from useNuxtApp?

@ijkml You, you can access it via `const { $img } = useNuxtApp()`

**Comment by ijkml** [comment]
Awesome!

Hovering over it showed `any`, that made me hesitate.

Thank you for pointing it out.
