### ISSUE TITLE
Unexpected response IPX: Forbidden host 

### ISSUE THREAD

**Issue by miraclebanks** [nuxt/image#596]
I am using @nuxt/image package to serve my images on my project. here is my package information

package.json file

"@nuxt/image": "^0.6.0",
 "nuxt": "^2.15.7",
"ipx": "^0.9.10",
nuxt.config.js

build:{
    '@nuxt/image',
},

I've tried adding   '@nuxt/image', to both build and other modules and still get this answer

Unexpected response IPX: Forbidden host 

Any help would be greatly appreciated

**Comment by Baroshem** [comment]
I think this issue can be related to having additional `ipx` package in package.json but it is a rather old issue.

Closing but feel free to reopen if needed :)
