### ISSUE TITLE
Using Imagekit.io provider with custom external storage (Firebase Storage) -- issue with URL path

### ISSUE THREAD

**Issue by dosstx** [nuxt/image#599]
I am using imagekit.io as provider for Nuxt3 version of this image module. I have set the nuxt config like so:

```js
    image: {
       provider: 'imagekit',
       imagekit: {
           baseURL: 'https://ik.imagekit.io/XXX'
       },
domains: ['firebasestorage.googleapis.com'],
```
The full image URL path at Firebase Storage after upload is: 

`https://firebasestorage.googleapis.com/v0/b/XXX/o/users%2FIdAUJMiswJajH8bnxdLrFpMhfTt1%2Fposts%2Fasdfsd_JMc7?alt=media&token=5e28334f-09c6-40e5-b64a-3381df2beb42`

I am using the above URL with NuxtImg component like so:

```js
          <NuxtImg
            provider="imagekit"
            :src="post.data.imageURL" // https://firebasestorage.googleapis.com/v0/b/XXX/o/users%2FIdAUJMiswJajH8bnxdLrFpMhfTt1%2Fposts%2Fasdfsd_JMc7?alt=media&token=5e28334f-09c6-40e5-b64a-3381df2beb42
```

The problem is that the full `https://firebasestorage.googleapis.com/v0/b/XXX/o` baseURL from storage is kept in the image URL, causing the image fetching to not work:

`https://ik.imagekit.io/XXX/https://firebasestorage.googleapis.com/v0/b/XXX/o/users%2FIdAUJMiswJajH8bnxdLrFpMhfTt1%2Fposts%2Fasdfsd_JMc7?alt=media&token=5e28334f-09c6-40e5-b64a-3381df2beb42?tr=dpr-auto,q-auto:best,e-sharpen-10,w-780,h-559`

It needs to be like so:
`https://ik.imagekit.io/XXX/users%2FIdAUJMiswJajH8bnxdLrFpMhfTt1%2Fposts%2Fasdfsd_JMc7?alt=media&token=5e28334f-09c6-40e5-b64a-3381df2beb42`

When I direclty paste the above URL into browser, it works.

Is there a way to "strip out" that Firebase storage when using this Nuxt Image module and/or is there a way I need to configure the `baseURL` property in `nuxt.config` ?

**Comment by rizkysyazuli** [comment]
@dosstx why did you close this? did you managed to find a solution? I'm on Nuxt 2 with Nuxt Image v0. but currently using a custom helper/plugin and likely will NOT use Nuxt Image at all.

```js
// plugins/imagekit.js
export default ({ app, $config }, inject) => {
  inject('imagekit', (src, transformation) => {
    const imagekitURL = $config.imagekitURL
    const assetsURL = $config.assetsURL // could be your firebase storage

    if (src) {
      // replace asset host with imagekit URL
      const pattern = new RegExp(`${assetsURL}`, 'gi')
      const path = src.replace(pattern, '')

      // image transform param
      // https://docs.imagekit.io/features/image-transformations
      const param = transformation ? `?tr=${transformation}` : ''

      // transforms this:
      // https://assets.mysite.com/path/to/image.jpg
      // into this:
      // https://ik.imagekit.io/xxx/path/to/image.jpg?tr=f-auto
      return `${imagekitURL}${path}${param}`
    } else {
      // returns a placeholder image if no source is provided
      return 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
    }
  })
}

```

And using it like this:

```vue
<picture>
  <source media="(min-width: 768px)" :srcset="$imagekit(image.medium.src, 'q-80')" />
  <img
    :src="$imagekit(image.small.src, 'q-80')"
    :alt="image.alt"
  />
</picture>
```

It's works fine.. But it would be great to have a built-in solution from Nuxt Image.

**Comment by dosstx** [comment]
I don't quite remember the details on this, but I was using Firebase Storage for storing images and then using ImageKit to fetch them for dynamic transformations. What I had to do to get it to work was strip the Firebase base url from the URL using `replace()` and then whitelist the domain name in Nuxt config for the image provider. 

I ended up actually not using Imagekit because Nuxt Img was providing the transformations I needed. 

Here's the basic level code for clarity (Nuxt 3):

```
<template>
    <div>
        <NuxtImg :src="fixedUrl" />
    </div>
</template>

<script setup lang="ts">
const url = ref('https://firebasestorage.googleapis.com/v0/b/bedtimeapp-stories/o/kRUx8ZxLoUd0y7kTcxgPfwTiGu13%2Fstory-images%2FfileNameHere.png?alt=media&token=400246d4-d7ea-4169-a420-e837fefe040a')

const splicedImgUrl = url.value.replace('https://firebasestorage.googleapis.com/v0/b/bedtimeapp-stories/o/', '')

console.log('splicedImgUrl: ', splicedImgUrl)

const encodedImagePath = encodeURIComponent(splicedImgUrl)

console.log('encodedImagePath: ', encodedImagePath)

const fixedUrl = 'https://firebasestorage.googleapis.com/v0/b/bedtimeapp-stories/o/' + encodedImagePath

</script>

**Comment by rizkysyazuli** [comment]
hmm. interesting. so you simply use the default provider? and what's the purpose of doing `encodeURIComponent` on the image path? @dosstx

**Comment by dosstx** [comment]
Yes, using the default provider (IPX) because Nuxt provides the basic transformations I need. I don't need all the other features from Imagekit. As for encoding...I needed to do that to the FIrebase paths because some of the characters are not "URI" safe on the browser when using Nuxt default provider. However if you do use Imagekit, I believe they have this taken care of and you shouldnt have to worry about this issue.
