### ISSUE TITLE
Signed URLs Imagekit provider

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/image#601]
Hello 👋,

I'd like to use the [Signed URLs](https://docs.imagekit.io/features/security/signed-urls#generating-signed-urls-on-your-own) from ImageKit provider in a Nuxt App. Do you know if that's possible to incorporate this functionality along with Nuxt Img ?

Thank you in advance

**Comment by Baroshem** [comment]
Hey there,

I know this is an old issue but I think that you could utilize something similar that I have created in Nuxt Cloudinary :)

https://cloudinary.nuxtjs.org/components/clduploadwidget#signed
