### ISSUE TITLE
Nuxt Image is not compatible with RC9

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/image#604]
It seems that `"@nuxt/image-edge": "^1.0.0-27703737.6f2a430"` and `"nuxt": "^3.0.0-rc.9"` produces an error. It was working fine on RC8

```sh
[Vue warn]: Component NuxtImg is missing template or render function.
ReferenceError: useNuxtApp is not defined
```

**Comment by BenjaminOddou** [comment]
After testing a bit, it seems this modules has the same problem as the one described in this [issue](https://github.com/nuxt/framework/issues/7196). Version `"@nuxt/image-edge": "^1.0.0-27657146.da85542"` with `rc-9` is throwing me the following :

```sh
 WARN  Module @nuxt/image is disabled due to incompatibility issues:                                                                                                              20:11:16
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`
 ```

**Comment by pi0** [comment]
Can you please try latest edge version of image module? It was a regression of a recent big refactor (https://github.com/nuxt/image/pull/571) which should be fixed by https://github.com/nuxt/image/commit/db0934c1afb124c579c7c272c0f8c103e360baf5

**Comment by BenjaminOddou** [comment]
Hello @pi0, I just tested your last version `"@nuxt/image-edge": "^1.0.0-27703825.db0934c"` and it fixed the issue. Thank you !

**Comment by massimans** [comment]
Hi,
i got the same issue with nuxt-RC13 and nuxt image `"@nuxt/image-edge": "^1.0.0-27769790.4b27db3"` like you suggested
it may be some kind of regression
