### ISSUE TITLE
Module @nuxt/image is disabled due to incompatibility [^3.0.0] to [3.0.0-rc.9]

### ISSUE THREAD

**Issue by matifanger** [nuxt/image#609]
Module @nuxt/image is disabled due to incompatibility issues:

 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`

**Comment by hartmut-co-uk** [comment]
-> `npm install -D @nuxt/image-edge`
ref https://v1.image.nuxtjs.org/get-started

**Comment by RedChops** [comment]
I'm getting this as well, installed using `yarn add @nuxt/image-edge` I verified it's v1 but it wont build

**Comment by RedChops** [comment]
It looks like specifying anything other than `yarn add --dev @nuxt/image-edge:1.0.0-27719579.87dcdf2` (or any other explicit version) causes the very old `1.0.0-testing` version to be pulled down.

**Comment by rikzwarthoff** [comment]
Still broken, using ```"@nuxt/image-edge": "^1.0.0-27719579.87dcdf2"```:
```
 WARN  Module @nuxt/image is disabled due to incompatibility issues:                                                                                                                                                                                                                                                                                       
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.11`
```

**Comment by binodnepali** [comment]
This warning still appears while using nuxt `3.0.0-rc.12`

```
WARN  Module @nuxt/image is disabled due to incompatibility issues:                                                                                                                                                                                                                                                                                       
 - [nuxt] Nuxt version `^3.0.0` is required but currently using 
```

When i use specify version: `yarn add --dev @nuxt/image-edge@1.0.0-27840416.dc1ed65`

Then warning goes away.

**Comment by Baroshem** [comment]
Closing as this issue is related to the edge version of nuxt image with rc.12.
