### ISSUE TITLE
nuxt3 with cloudflare images not showing up in production.

### ISSUE THREAD

**Issue by ricky11** [nuxt/image#611]
The docs say i can keep them in assets/image and change the config in nuxt.config by 

image: {
  dir: 'assets/images',
}

this works locally in dev mode.

But when deploying to cloudflare pages, the images are not displayed (cloudflare runs npm generate) for static hosting.

But another part of the docs say to deploy them to /public folder..

I have tried both and when deployed images are not showing up when deployed.

**Comment by jimhlad** [comment]
@ricky11 This may be happening because static image generation is not supported yet: #548

**Comment by Baroshem** [comment]
Closing as it already works for SSG apps :)
