### ISSUE TITLE
Statamic Provider

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt/image#616]
Statamic is a flat-file Open Source CMS built upon Laravel. They offer an image service as well and there is already a Vue package handling the provider: https://www.npmjs.com/package/vue-statamic-image. Maybe this one can be integrated to nuxt-image as well.

**Comment by pi0** [comment]
PR Welcome to add provider 👍🏼

**Comment by Baroshem** [comment]
Closing as there was no traffic here for more than 2 years.

Feel free to reopen if have time to work on it :)
