### ISSUE TITLE
Optional blur animation transition

### ISSUE THREAD

**Issue by Larsklopstra** [nuxt/image#62]
By default the image transitions the blur when the image is fully loaded. There should be an option to opt in/out of this behaviour. The transition will cause lag in some cases because blur transitions are resource hungry.

**Comment by Frondor** [comment]
I don't think that should be responsability of this package. I'd rather wrap it.

**Comment by farnabaz** [comment]
The image module uses CSS to create image transitions and can be simply modified or changed using CSS.

**Comment by Larsklopstra** [comment]
@farnabaz I'd prefer to not edit existing CSS. How about exposing some API similar to `Transition`? eg:

```
<NuxtImage
  ...
  loading-active-class="transition duration-200 ease-in-out"
  loading-from-class="blur-16"
  loading-to-class="blur-0"
/>
```
