### ISSUE TITLE
FATAL  Invalid or unexpected token    

### ISSUE THREAD

**Issue by vedmant** [nuxt/image#627]
When I'm trying to add this module to my app I have following error:

 FATAL  Invalid or unexpected token                                                                                                                                           10:02:35

  const ext = input.split(".").pop()?.split("?")[0];
  ^
  
  SyntaxError: Invalid or unexpected token
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)

   ╭──────────────────────────────────────────────╮
   │                                              │
   │   ✖ Nuxt Fatal Error                         │
   │                                              │
   │   SyntaxError: Invalid or unexpected token   │
   │                                              │
   ╰──────────────────────────────────────────────╯

error Command failed with exit code 1.

Node v16.17.1
Nuxt 2.14.7

**Comment by CojocariIon** [comment]
@vedmant install @nuxt/image@0.6.0, me helped

**Comment by Ariwf3** [comment]
Hello min versions are 12.x 14.x or 16.x https://image.nuxtjs.org/getting-started/installation#troubleshooting

In my case I had to updgrade node version then remove your node_modules folder and your package-lock.json/yarn.lock and update your dependencies again it should works
