### ISSUE TITLE
How do I specify in <nuxt-picture> multiple formats from the backend?

### ISSUE THREAD

**Issue by vedmant** [nuxt/image#628]
Hi, I have an object from the backend that returns me image in multiple formats, like jpg, webp.
I need then to create a tag like:

```
<picture>
  <source type="image/webp" :srcset="image.webp_format">
  <source type="image/jpeg" :srcset="image.jpg_format">
  <img :src="image.jpg_format" alt="">
</picture>
```

How I can do this with <nuxt-picture> ?

I also want to be able to use lazy loading and preload features when needed.

**Comment by agonzalez0515** [comment]
bump!

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/image/issues/309.
