### ISSUE TITLE
Cover image on website broken

### ISSUE THREAD

**Issue by Jeromche** [nuxt/image#63]
The cover image in the Introduction section of the website https://image.nuxtjs.org/ is broken.

<img width="666" alt="Screen Shot 2020-10-31 at 12 28 26" src="https://user-images.githubusercontent.com/778293/97787008-ffff2680-1b74-11eb-8ee8-685d40d9b66b.png">

**Comment by farnabaz** [comment]
Thank you for the issue ❤️   
This is fixed in latest version.
