### ISSUE TITLE
Use provider, such as Sanity to create placeholder image url

### ISSUE THREAD

**Issue by toddpadwick** [nuxt/image#633]
At the moment, from what I understand, the provider can generate the transformed image for the main src. But not the placeholder. what I'd like to achieve, is something like this:
```
<nuxt-img 
    provider="sanity" 
    :src="entry.heroImage.asset._ref" 
    :modifiers="{ quality:80 }" 
    :width="600" 
    :placeholder="entry.heroImage.asset._ref"  // New feature to accept sanity image refs just like the src does
    :placeholder-modifiers="{ quality:25, blur:100 }" // new feature
/>
```
So it would be great to have a second modifiers param, specific to the placeholder, to transform the placeholder version of the image – a common use case would be to lower the quality and blur the placeholder. May also need more parameters to adjust the placeholder width and height.

**Comment by Baroshem** [comment]
This can be now done in current version of Nuxt Image -> https://image.nuxt.com/usage/nuxt-img#placeholder

Closing the issue.

Feel free to reopen if needed :)
