### ISSUE TITLE
images return 404 when using `nuxt generate` + vercel preset

### ISSUE THREAD

**Issue by fayazara** [nuxt/image#638]
Using nuxt-img with local images and they dont seem to work when the pages are prerendered. They throw a 404 error.
<img width="1436" alt="Screenshot2022-10-29 at 21 23 51@2x" src="https://user-images.githubusercontent.com/15716057/198841014-4475a5a0-d1e6-46af-8a61-d6139d1c4303.png">

The images are displayed locally in dev environment. 
![image](https://user-images.githubusercontent.com/15716057/198841026-d1fff6ec-5309-4e5a-b2de-9b3652a980d1.png)

Reproduction - https://github.com/fayazara/nuxt-image-issue-reproduction

Deployed on Vercel - https://nuxt-image-issue-reproduction.vercel.app/
Deployed on Netlify - https://wondrous-medovik-574c06.netlify.app/

A remote image URL work btw. Happens only with local static images. 

Build command was set to `yarn generate`

**Comment by jimhlad** [comment]
I believe this may be another one related to the WIP on static generation #614

**Comment by fayazara** [comment]
Anyboyd found a temporary fix to this yet?

**Comment by MilenaPetkanova** [comment]
> Anyboyd found a temporary fix to this yet?

I didn't, so I just migrated my whole project to Nuxt2. 
In the meantime, I'm subscribed to the repo to stalk when [#614](https://github.com/nuxt/image/pull/614) is gonna be ready.

**Comment by dosstx** [comment]
I believe I am seeing this issue too. It works fine when I do `npm run dev` but once I deploy to produciton, the local images are 404. 

`IPX Error: Error: File not found (/public/images/avatar-placeholder.svg)`

**Comment by wadclapp** [comment]
Just started using this package and swapped out all my images, and is broken for me too. Using Nuxt v2 and nuxt-image v0.7.1, but it works fine on localhost dev/build

**Comment by mctweb** [comment]
This is also the case for me when using `<nuxt-img>` and local images. It works in dev, but not with `build` or `generate`. Tried on both linux and windows without success.

**Comment by Teo3tc** [comment]
hello i clone your projet and in nuxt config i add the path  like this  (is work for me)
```js  
image: {   staticFilename: '[publicPath]/[name]-[hash][ext]'  } 
```
[doc](https://v1.image.nuxtjs.org/configuration)

**Comment by djmtype** [comment]
Even after the nuxt-img@edge update 1.0.0-27954023.4cee565 it still remains broken.

**Comment by Maximus1000** [comment]
Now working config yet for me with Netlify provider whereas works locally.

**Comment by andysay** [comment]
same problems some files return 404

**Comment by mplno** [comment]
I have been following the vercel-static Nitro preset discussion and just gave that new preset a shot. I'm unable to get images working in a static build on Vercel. I've made a minimal reproduction.

Repo: https://github.com/mplno/nuxt-vercel-image-example
Site deployed on Vercel: https://image-example-aebof1cnt-color-camp.vercel.app/

My steps to init this repo:

```sh
npx nuxi init nuxt-vercel-image-example
cd nuxt-vercel-image-example
yarn add --dev @nuxt/image-edge
```

I have the Vercel project build step overwritten to `yarn generate`. I am seeing "Nuxt 3.5.2 with Nitro 2.4.1" logged in the Vercel build, confirming that I am on the updates that support vercel-static.

Have I made an error in setting up a vercel-static project? If not, I'm happy to help debug further.

**Comment by TheoParkos** [comment]
Just to chime in. We have the same issue hosting it via NGINX and NGINX Ingress via K8s.

Turns out when you build the NUXT project, the static folder was not transferred, so we got 404s, but the output on our deployed instances did not have anything as NUXT does not package static during it's build process.

After that was fixed, no more 404s and everything started working.

**Comment by victorraji** [comment]
> Just to chime in. We have the same issue hosting it via NGINX and NGINX Ingress via K8s.
> 
> Turns out when you build the NUXT project, the static folder was not transferred, so we got 404s, but the output on our deployed instances did not have anything as NUXT does not package static during it's build process.
> 
> After that was fixed, no more 404s and everything started working.

how did you fix this  [TheoParkos](https://github.com/TheoParkos) ?

**Comment by oooFreaKooo** [comment]
So we cant have local images when we use nuxt generate? Is that what i get from this discussion?

**Comment by danielroe** [comment]
you absolutely can. this is a very old issue.

just make sure not to set `ssr: false`

**Comment by oooFreaKooo** [comment]
> you absolutely can. this is a very old issue.
> 
> just make sure not to set `ssr: false`

The only way i got this to work is to manually add the path in nitro prerender and set the provider to ipxStatic in production:

```ts
    ssr: false,

    nitro: {
        prerender: {
            routes: [
                '/_ipx/f_webp&q_80/icons/logo-weiss.png',
                '/_ipx/s_150x150/images/loader.gif',
                '/_ipx/s_300x300/images/loader.gif',
            ],
        },
    },

    $production: {
        runtimeConfig: {
            public: {
                EXTERNAL_API_BASE_URL: process.env.EXTERNAL_API_BASE_URL,
            },
        },
        image: {
            provider: 'ipxStatic',
        },
    },
```

Thank god I get 99% of the Images from the external API.
If there is a way to avoid this, i would be very thankful.

I will try to deploy again without ssr: false
