### ISSUE TITLE
nuxt image disabled on v3.0.0-rc.13

### ISSUE THREAD

**Issue by massimans** [nuxt/image#643]
Hi,
i tried installing `@nuxt/image-edge` but got this error, is there a way around it ?

```ps
Module @nuxt/image is disabled due to incompatibility issues:                                                 10:08:06
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.13`
```
my package.json
```json

{
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/image-edge": "^1.0.0-27769790.4b27db3",
    "nuxt": "v3.0.0-rc.13",
    "sass": "^1.54.0",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "@directus/sdk": "^10.1.4",
    "@popperjs/core": "^2.11.6",
    "@vue/compiler-sfc": "^3.2.37",
    "@vueuse/core": "^9.0.2",
    "bootstrap": "^5.2.0",
    "circletype": "^2.3.0",
    "moment": "^2.29.4",
    "vee-validate": "3"
  }
}
```

**Comment by nate998877** [comment]
Guessing here, but you probably need to use nuxt `3.0.0-rc.10`

https://github.com/nuxt/framework/discussions/7513

**Comment by massimans** [comment]
Hi,
what i found i was that for some reason the latest version of the package was pulling the very old `"1.0.0-testing"` release (maybe some yarn issue since it appears to be good on the registry)
i managed to fix it for me by going to [https://classic.yarnpkg.com/en/package/@nuxt/image-edge](https://classic.yarnpkg.com/en/package/@nuxt/image-edge) and trying out the previous release and it worked!

this is working for RC-13
```
yarn add --dev @nuxt/image-edge@1.0.0-27768165.4b0219a
```

**Comment by pascalwengerter** [comment]
@massimans do you mind closing the issue since it worked out for you (and now work with the official Nuxt `v3.x.x`/`@nuxt/image-edge`)? :)

**Comment by massimans** [comment]
All right
