### ISSUE TITLE
defu is not a function: from nuxt image to rc9 to defu > defu 6.1.1 breaks the build of nuxt v2

### ISSUE THREAD

**Issue by Billybobbonnet** [nuxt/image#649]
Hi all!

With nuxt v2 + nuxt image latest version (0.7.1), there is a build fatal error. Nuxt image has a dependency with [`"rc9": "^1.2.2"`](https://github.com/nuxt/image/blob/v0/package.json#L36), which uses [`"defu": "^6.1.1"`](https://github.com/unjs/rc9/blob/main/package.json#L27) which breaks Nuxt build with a ` defu is not a function`.

![image](https://user-images.githubusercontent.com/8236816/202173532-76203c19-a8a2-44ee-9d14-bcf61df41e6a.png)

**Comment by widdydev** [comment]
Any news/eta on that?

**Comment by NozomuIkuta** [comment]
Ref: https://github.com/unjs/defu/issues/55#issuecomment-1374062483

**Comment by NozomuIkuta** [comment]
@pi0 

I believe it's already resolved, and can be closed.
I have closed https://github.com/unjs/defu/issues/55 just before.

**Comment by Baroshem** [comment]
Closing as the solution was provided.
