### ISSUE TITLE
'image' does not exist in type 'NuxtConfig' [TS]

### ISSUE THREAD

**Issue by nathanchase** [nuxt/image#650]
Getting this TypeScript error when attempting to add an `image` configuration section to my `nuxt.config.ts` in Nuxt 3:
` Object literal may only specify known properties, and 'image' does not exist in type 'NuxtConfig'.ts(2345)`

Using:
```
"@nuxt/image-edge": "1.0.0-27809804.194d2d6",
"nuxt": "latest",
```
<img width="705" alt="image" src="https://user-images.githubusercontent.com/5963574/202781208-0c3b6219-af7c-4328-b407-fb460f28d1fe.png">

**Comment by danielroe** [comment]
Does it still do this after you run `nuxi prepare` or `nuxi dev`?

**Comment by nathanchase** [comment]
Yes. It seems related to Volar and running it in Takeover mode. If I DON'T run it in Takeover mode, there's no error.

At first I thought it might be that VSCode was using a lesser TypeScript version and that was the culprit, but it doesn't matter if I use VSCode's TS version, or the latest TS version.

**Comment by danielroe** [comment]
Would you raise an issue upstream in that case? https://github.com/johnsoncodehk/volar

**Comment by nathanchase** [comment]
> Would you raise an issue upstream in that case? https://github.com/johnsoncodehk/volar

I did more digging and found out it's `@nuxt/test-utils-edge` that's causing the problem! 

Something in that package is causing the error to occur with `@nuxt/image`.

Reproduce steps:
- Clone https://github.com/nathanchase/nuxt-image-edge-error
- run `pnpm install --shamefully-hoist` (may be a pnpm-only issue?)
- Ensure your VSCode & Volar are running in Takeover mode
- You should see the error on the image entry in nuxt.config

<img width="615" alt="image" src="https://user-images.githubusercontent.com/5963574/202924770-20978a40-d9eb-47a9-bdaa-ee20df57ac5f.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/5963574/202924796-b6cdd50b-be6c-4ab0-9b90-e96b3e6db537.png">

Perhaps there's something that's impacting NuxtConfig in `@nuxt/test-utils-edge` ? I don't have access to that repo, so I can't tell.

For now, the solution is to remove `@nuxt/test-utils-edge` from my project.

**Comment by leopoldkristjansson** [comment]
I am getting this error as well, but I am not using `@nuxt/test-utils-edge`

My package.json is

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.2.2",
    "@nuxt/image-edge": "^1.0.0-27827328.bc9ddc0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "nuxt": "3.0.0",
    "prettier": "^2.7.1"
  },
  "dependencies": {
    "@vueuse/core": "^9.5.0",
    "@vueuse/nuxt": "^9.5.0"
  }
}

```

**Comment by nathanchase** [comment]
> I am getting this error as well, but I am not using `@nuxt/test-utils-edge`
> 
> My package.json is
> 
> ```
> {
>   "private": true,
>   "scripts": {
>     "build": "nuxt build",
>     "dev": "nuxt dev",
>     "generate": "nuxt generate",
>     "preview": "nuxt preview",
>     "postinstall": "nuxt prepare"
>   },
>   "devDependencies": {
>     "@nuxt/content": "^2.2.2",
>     "@nuxt/image-edge": "^1.0.0-27827328.bc9ddc0",
>     "@nuxtjs/eslint-config-typescript": "^12.0.0",
>     "eslint": "^8.28.0",
>     "eslint-config-prettier": "^8.5.0",
>     "eslint-plugin-prettier": "^4.2.1",
>     "nuxt": "3.0.0",
>     "prettier": "^2.7.1"
>   },
>   "dependencies": {
>     "@vueuse/core": "^9.5.0",
>     "@vueuse/nuxt": "^9.5.0"
>   }
> }
> ```

If you remove `@nuxt/content` from your package.json and clear out your node_modules and lock file and do a new pnpm install, it might fix it. I think the root cause is some sort of interaction between the first-party modules that is causing the Typescript typing to fail somehow.

**Comment by PrinceAtVidyaMantra** [comment]
I'm not using @nuxt/content or test-utils-edge still the error is there 
```
export default defineNuxtConfig({
  telemetry: false,
  nitro: {
    externals: {
      inline: ["uuid"],
    },
  },
  modules: [
    "@pinia/nuxt",
    "@nuxtjs/tailwindcss",
    "@nuxt/image-edge",
    "nuxt-delay-hydration",
  ],
  image: {
    domains: ["mydomain"],
  },
```
It causes the production to fail whenever there is an update to nuxt

**Comment by vpiskunov** [comment]
This was caused by installing @nuxt/image instead of @nuxt/image@rc for our case. Ensure to `npm install -D @nuxt/image@rc` as in v1 docs([https://v1.image.nuxtjs.org/get-started/](https://v1.image.nuxtjs.org/get-started/)) instead of previous version docs

**Comment by kravenhunter** [comment]
> This was caused by installing @nuxt/image instead of @nuxt/image@rc for our case. Ensure to `npm install -D @nuxt/image@rc` as in v1 docs(https://v1.image.nuxtjs.org/get-started/) instead of previous version docs

No it's not. I installed latest version nuxt 3   and @nuxt/image@rc  but the error  didn't disappear. How to solve it?

**Comment by danielroe** [comment]
@kravenhunter If you could open an issue with a reproduction I'll take a look

**Comment by kravenhunter** [comment]
> @kravenhunter If you could open an issue with a reproduction I'll take a look

I guess there  is no necessary to open a new issue I could fix the problem in my project.   Disabling all  global  extensions  didn't  help, so tried to change    "@nuxt/image": "^1.0.0-rc.2"  to   "@nuxt/image": "rc"   in package.json, run  npm i  and restart  VSCode and it worked. After  I tryed  to install the latest version   "@nuxt/image": "^1.0.0-rc.2"  and the   error didn't  appear.
