### ISSUE TITLE
[nuxt3] Feature Request: config option for default `format` & `quality`

### ISSUE THREAD

**Issue by hartmut-co-uk** [nuxt/image#657]
I'd like to configure a default image _format_ for all images via nuxt config:

```ts
export default defineNuxtConfig({
    modules: [
        '@nuxt/image-edge'
    ],
    image: {
        // 
        format: "webp",
        quality: "80"
    },
}
```

#### Questions
1. According to configuration, this might be possible via provider specific default modifiers?
1. Is this the best choice for such basic props as 'format', 'quality'?
1. Is it also possible (to add) for IPX? ([IPXOptions](https://github.com/unjs/ipx/blob/c8094bce35bee12e04ad167fee983cd7789c97fa/src/ipx.ts#L30))

#### Refs
- https://v1.image.nuxtjs.org/components/nuxt-img/#format
- https://v1.image.nuxtjs.org/configuration/#modifiers
- https://github.com/unjs/ipx/blob/c8094bce35bee12e04ad167fee983cd7789c97fa/src/ipx.ts#L30

**Comment by hartmut-co-uk** [comment]
I've tested with following config:

```ts
export default defineNuxtConfig({
    modules: [
        '@nuxt/image-edge'
    ],
    image: {
    provider: 'ipx',
    ipx: {
      modifiers: {
        quality: '80',
        format: 'webp',
      }
    }
  }
}
```

This works just fine and is applied to all nuxt-img as a default, also can be overwritten if required.

=> So I think it's actually just a missing type def in IPXOptions?

**Comment by sungeunl** [comment]
is it working fine ?

**Comment by hartmut-co-uk** [comment]
at the time of writing it was working, I no longer can confirm the exact version though...

**Comment by madebyfabian** [comment]
I can confirm, still works with `"@nuxt/image": "1.0.0-rc.3"`. But still with a type error.

**Comment by Baroshem** [comment]
Both configuration options are now available https://image.nuxt.com/get-started/configuration#quality
