### ISSUE TITLE
[nuxt3] domains filter doesn't work with port numbers

### ISSUE THREAD

**Issue by roald-di** [nuxt/image#659]
When an external image url contains a port number (say `https://localhost:8080/images/example.png`) then there is no way to whitelist the domain in the configuration option `images.domains`.

this is because the image hostnames and the configured hostnames are parsed differently:

with `parseURL(...).host` here https://github.com/nuxt/image/blob/6e63b203197d8757fa93629527df21de7365f455/src/runtime/image.ts#L77
and with `new URL(...).hostname` here https://github.com/nuxt/image/blob/6e63b203197d8757fa93629527df21de7365f455/src/module.ts#L57

` parseURL('https://localhost:8080/images/example.png').host` gives `localhost:8080`
while
`new URL('http://localhost:8080/').hostname` gives `localhost`

I can make a simple PR to replace `new Url` with `parseURL` if that is ok with you.

**Comment by Krillko** [comment]
I have this problem too, so a fix would be appriciated.
