### ISSUE TITLE
NuxtImg component: `process.env` is undefined

### ISSUE THREAD

**Issue by ijkml** [nuxt/image#663]
The &lt;NuxtImg /&gt; component does not seem to work. An error is logged: `process.env is not defined`. And the debugger points to this line https://github.com/nuxt/image/blob/ab054e4a38e15f421262c47d8952e545ecc18588/src/runtime/components/nuxt-img.ts#L89

Using Nuxt 3.0 and latest nuxt-img (1.0.0-27821548.ab054e4) 
Here is a repro: https://stackblitz.com/edit/github-ytnyej?file=app.vue

Thank you!

**Comment by ErriourMe** [comment]
The same problem

**Comment by gitFoxCode** [comment]
Same problem 😞

**Comment by brunodeangelis** [comment]
This is fixed in #661. We just need to wait for an admin to merge

**Comment by piscis** [comment]
FYI: `@nuxt/image-edge@1.0.0-27827328.bc9ddc0` should contain the fix from #661
