### ISSUE TITLE
Option to update [ipx.BASE_URL] in nuxt/image config

### ISSUE THREAD

**Issue by NeroThroN** [nuxt/image#665]
In [nuxt 3](https://nuxt.com/) there is an option to define a **baseURL** inside **nuxt.config.ts** ([documentation](https://nuxt.com/docs/api/configuration/nuxt-config/#baseurl)) to serve the app from a prefix (like _domains.com/prefix/_)

With [nuxt/image](https://v1.image.nuxtjs.org/) there is no configuration to update this baseURL. This creates an error for each images fetch because it will not add the prefix before the _ipx provider (See reproduction below)

### Create new nuxt project
```bash
npx nuxi init nuxt-app
npm install
```
### Install @nuxt/image(-edge)
```bash
npm install -D @nuxt/image-edge
```
### Edit `nuxt.config.ts`
```ts
const baseURL = "/prefix/";

export default defineNuxtConfig({
  app: { baseURL },
  nitro: { baseURL },
  modules: ["@nuxt/image-edge"],
  image: {
    domains: ["picsum.photos"],
  },
});
```
### Edit `app.vue`
```vue
<template>
  <NuxtImg
    src="https://picsum.photos/id/237/4000/4000"
    sizes="xs:250px"
    :modifiers="{ grayscale: true }"
    format="webp"
  />
</template>

<style>
* {
  margin: 0;
  overflow: hidden !important;
}

img {
  height: 100vh;
  width: 100vw;
  object-fit: cover;
}
</style>
```
### Expected result
![image](https://user-images.githubusercontent.com/38684083/204486379-8574abd4-6077-4a19-b792-e3b86dee8b80.png)

### Reality
**404: Cannot find any route matching /_ipx/grayscale_true,w_250,f_webp/https://picsum.photos/id/237/4000/4000.**
![image](https://user-images.githubusercontent.com/38684083/204486709-8ad268f1-a752-42c9-8d20-2a7c36ff8b45.png)

**Comment by NeroThroN** [comment]
Thanks to [the response of hartmut#1067](https://discord.com/channels/473401852243869706/1046856003246903376/1047075777746837514) on the [Nuxt Discord](https://discord.com/invite/ps2h6QT) I see that the image object property inside the nuxt config has a baseURL attribute inside the _ipx one.

This is not referenced inside the ipx documentation nether nuxt/image or even Typescript.

:warning: **Maybe adding this configuration to the documentation and more importantly to nuxt/image's types**

## Fix
### Edit `nuxt.config.ts`
```ts
const baseURL = "/prefix/";

export default defineNuxtConfig({
  app: { baseURL },
  nitro: { baseURL },
  modules: ["@nuxt/image-edge"],
  image: {
    domains: ["picsum.photos"],
    ipx: {
      baseURL: `${baseURL}_ipx/`, // <= Add this config
    },
  },
});
```
### Resulting Error
![image](https://user-images.githubusercontent.com/38684083/204492446-cb679944-ce00-479b-8362-0eaa73120aaf.png)

### Result
![image](https://user-images.githubusercontent.com/38684083/204492698-601bfa34-b2c9-4de7-bdd1-fa8e68030fa6.png)

**Comment by hubret** [comment]
seems like this is on the roadmap and isn't doable yet
https://github.com/nuxt/image/discussions/548#discussion-4201300
