### ISSUE TITLE
Getting a "Cannot find module './runtime/providers/ipx'" when starting nuxt server, after installing "@nuxt/image-edge"

### ISSUE THREAD

**Issue by MarioC3** [nuxt/image#669]
I followed the [instructions](https://v1.image.nuxtjs.org/get-started) to install `nuxt/image` .  But, when I start the nuxt server, I get this error:
```
Cannot start nuxt:  Cannot find module './runtime/providers/ipx'
Require stack:
- /.../node_modules/@nuxt/image-edge/dist/module.mjs
```

I'm having difficulty reproducing it since the installation goes smoothly on StackBlitz.

Here's my nuxi info, if it helps:
```
- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `nitro`, `typescript`, `modules`, `runtimeConfig`, `build`, `extends`, `tailwindcss`, `css`, `image`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-testing`, `nuxt-lodash@2.4.1`, `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.7`, `@vueuse/nuxt@9.6.0`, `@formkit/nuxt@1.0.0-beta.13-a20e66b`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.6`, `@nuxtjs/fontaine@0.2.3`
- Build Modules:    `-`
```

**Comment by xhayper** [comment]
I was able to reproduce this using `yarn 3`, using `npm` doesn't cause this to happened.

**Comment by xhayper** [comment]
I figured it out for me, `yarn add --dev @nuxt/image-edge` would install `1.0.0-testing` instead of the latest version, causing the weird error.

To properly install it, you can install `yarn add --dev @nuxt/image-edge@1.0.0-27840416.dc1ed65` (latest beta build as of right now)

Don't forget to remove the `^` from the version in `package.json` too.

**Comment by x5hwuk7nc6jsudcc** [comment]
In your `package.json` you can use:
`"@nuxt/image-edge": "<1.0.0-testing"`
Which will get you latest version until version numbering issue is resolved.

**Comment by Baroshem** [comment]
Closing ad this issue is related to NuxtImage Edge
