### ISSUE TITLE
Nitro preset 'Azure' gives 404.

### ISSUE THREAD

**Issue by CedricBaetens** [nuxt/image#675]
When you configure nuxt to use the Nitro preset 'Azure' images using ipx are not working. The requested url throws a 404.

![image](https://user-images.githubusercontent.com/6593158/205674200-61624a84-213e-4d9d-9b47-8c6bce3576ee.png)
![image](https://user-images.githubusercontent.com/6593158/205674364-e6bddb27-c219-4160-ad89-e03b41e93acd.png)

I've added this in the nuxt.config.ts file
`nitro: {
    preset: 'azure'
}`

Start the application with following command:
`pnpm run dev:build && npx @azure/static-web-apps-cli start playground/.output/public --api-location playground/.output/server `

When I try to deploy the app to Azure using 'Static Web Apps' I get the same result.

Any help appreciated, thank you.

**Comment by jeverduzco** [comment]
I have the same problem :(

**Comment by owlnai** [comment]
It might be related to the issue that's also affecting Netlify and other providers (#689). Generating the `_ipx` folder locally and moving it to the `public/` folder worked for me as a workaround.

**Comment by jeverduzco** [comment]
> It might be related to the issue that's also affecting Netlify and other providers (#689). Generating the `_ipx` folder locally and moving it to the `public/` folder worked for me as a workaround.

I will try this solution @smpettit

**Comment by reallymello** [comment]
Is this something I have a do to get it to work on Azure even now @smpettit or has there been news from the dev team on a fix? I get an error using generate locally due to https://github.com/nuxt/image/issues/799 so doing that extra step is a problem

**Comment by reallymello** [comment]
@smpettit This morning I tried adding prerender to the root routeRules based on a post I found. This made the images work for me on Azure, but I am not sure what other implications it may have since I am new to Nuxt and Vue.

```ts
routeRules: {
    '/': { prerender: true },
  },
```

**Comment by moshetanzer** [comment]
@CedricBaetens any updates, still doesnt seem to be working. Quite crazy!

**Comment by moshetanzer** [comment]
@danielroe 

Hope you well

I see a new version of nuxt image was pushed on Friday. Was really hoping a fix for this would have been included. Is there any timeline for this?

Seems to be many are struggling with this;

https://github.com/nuxt/image/issues/1183

https://github.com/nuxt/image/issues/999

https://github.com/nuxt/image/issues/994

https://github.com/nuxt/image/issues/881

Seem to be many more...

**Comment by pi0** [comment]
The issue with Azure static web apps was related to the lack of binary response support (upstream issue: https://github.com/unjs/nitro/issues/100)

The fix has landed in Nitro's main (upstream change: https://github.com/unjs/nitro/pull/2079) and I verified against Nuxt Image deployment locally. 

To have the fix, you can switch to [Nuxt Nightly Channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel) or [Nitro Nightly Channel](https://nitro.unjs.io/guide/getting-started#nightly-release-channel) until next release of Nitro (Estimated end of Jan). (**important:** make sure lockfile is updated to have latest version of Nitro nightly)

If you have encountered any issues regarding Azure, please let me now 👍🏼

**Comment by AamirAlam** [comment]
This issue still persist with firebase hosting , the only solution that works is 

run `yarn generate` then move the _ipx/80/images to the public folder with `mv .output/public/_ipx  public/`

not sure If this is a good solution
