### ISSUE TITLE
[nuxt3] error - nuxt.options.buildModules is not iterable

### ISSUE THREAD

**Issue by mschneekluth** [nuxt/image#688]
I get the following error message when I try to use nuxt-image in my nuxt3 project:

"**ERROR  Cannot start nuxt:  nuxt.options.buildModules is not iterable**"

I installed nuxt-image `npm install -D @nuxt/image-edge`

_nuxt.config.js_
```
import { defineNuxtConfig } from "nuxt";

export default defineNuxtConfig({
  modules: ["@nuxt/image-edge", "@nuxt/content", "@nuxtjs/tailwindcss"],
});
```
**node version: v18.12.1**
**nuxt-edge version: "@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",**

**Comment by danielroe** [comment]
What version of `@nuxt/image-edge` are you using?

**Comment by mschneekluth** [comment]
> What version of `@nuxt/image-edge` are you using?

"@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",

**Comment by danielroe** [comment]
I don't think this is an issue with the image module. Would you provide a reproduction? 🙏
