### ISSUE TITLE
"@nuxt/image-edge": "^1.0.0-27840416.dc1ed65".  still doesn't support static images 

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/image#690]
i find that using.  as Nuxt3 prefers you actually use the assets folder to host your images.
`export default defineNuxtConfig({
  image: {
    dir: "assets/images",
  },
})
`

then using 
` <NuxtImg
          class="desktop"
          src="/website/home/above-fold-illustration.png"
          alt="illustration"
          aria-hidden="true"
        />`
        
doesn't work when deploying static site.   it works on running it on the dev server,  but breaks on the statically built version

"@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",

**Comment by desenvolvimento02jocc** [comment]
Same here.

**Comment by papadi166** [comment]
I'am still waiting for fix xD

**Comment by aleavikraman** [comment]
running into the same issue

**Comment by Intevel** [comment]
Same issue for me!

**Comment by pi0** [comment]
Hi. You should put images to `public/images` directory. assets is a convention for Nuxt to build **build time assets** that get bundled with vite/webpack while image assets are runtime required.

Please let me know if still having issues after moving to public.

**Comment by ibrahim-990** [comment]
i do this but not work with me

export default defineNuxtConfig({
    modules: [
        '@nuxt/image-edge',
    ],
    image: {
        dir: "public/",
    },,    
})

**Comment by ibrahim-990** [comment]
the images shown in mode run nuxt dev but when run nuxt generate the images not shown

**Comment by ibrahim-990** [comment]
and in package.json file 
this
 "dependencies": {
    "@nuxt/image-edge": "^1.0.0-27919678.2f5b64b",
}
