### ISSUE TITLE
Changing fit="contain" fill background

### ISSUE THREAD

**Issue by Birleyici** [nuxt/image#698]
![2](https://user-images.githubusercontent.com/76836381/209628116-3b1c68c7-a259-464a-8220-85b423b774dd.jpg)

Is it possible for me to change the background color for the fit="contain" property? I want to make it white.

**Comment by Birleyici** [comment]
I solved it with background="white"

**Comment by jrodas4044** [comment]
Thanks,  i hav the same problem

**Comment by Baroshem** [comment]
Closing as the solution was provided.
