### ISSUE TITLE
[Bug] Does this plugin not work with Nuxt 3 using TailwindCSS?

### ISSUE THREAD

**Issue by mohsin** [nuxt/image#699]
I'm considering using this plugin for my blog project listing (to show logos of companies that I've worked with) and it needs to be optimized based on different screen sizes. I'm currently tracking it using Netlify LFS and my code is as follows:
```
<nuxt-img format="webp" class="w-full sm:w-[100px]" sizes="xs:512 sm:100" :src="project.src" />
```

However, when I inspect the browser network tab, the request is always:
https://develop.imoz.in/images/triptantra.png?w=512&nf_resize=fit

Shouldn't it make it w=100 since it's currently on a lg screen (my browser).

Reproduction: https://github.com/mohsin/iMoz-Web/commit/2454c866f5a0299a54813b6121ef8fdbad79b960
Demo: https://develop.imoz.in/code/

**Comment by mohsin** [comment]
Oh wait, it doesn't do it when in dev mode and works in production. My bad! Never mind, thanks!

**Comment by pascalwengerter** [comment]
I've tried around requesting different sizes of the used images (e.g. https://develop.imoz.in/images/apiwiz.webp?w=50&h=50&nf_resize=smartcrop) but that doesn't seem to work, and there's no Tailwind (and no NuxtImage) involved. Could you check and confirm that it's not a webp/Netlify problem?
