### ISSUE TITLE
Change IPX Cache-Control max-age

### ISSUE THREAD

**Issue by ziadsarour** [nuxt/image#704]
Hello,

I'm unable to increase the cache max-age of my images.
This is decreasing my Lighthouse score.

<img width="742" alt="Capture d’écran 2023-01-08 à 14 10 43" src="https://user-images.githubusercontent.com/8212468/211197871-a534cfea-2d6d-46e7-b26f-53276f00ea7f.png">

I've tried to define a `routeRules` for `/_ipx/**` but it's not working.

```
build: {
  transpile: [
    /image-edge/,
  ],
},
modules: [
   '@nuxt/image-edge',
],
nitro: {
  routeRules: {
    '/_ipx/**': {
      headers: {
        'Cache-Control': 'public, max-age=31536000',
      },
    },
  },
},
```

The max-age is still 300s.

<img width="737" alt="Capture d’écran 2023-01-08 à 14 23 19" src="https://user-images.githubusercontent.com/8212468/211198364-affcd17d-fd5c-4e98-b9ff-984a4ffd4a30.png">

I know the best thing would be to have an hash in images names to invalidate cache at each build, but for now I just need to have the best Lighthouse score possible.

Thank you for this awesome framework and library 😀

**Comment by yjl9903** [comment]
I have the same issue too.

I config the `maxAge` option in `nuxt.config.ts`, and maybe it forgets pass the maxAge configuration? 

My config:

```ts
export default defineNuxtConfig({
  // ...
  image: {
    provider: 'ipx',
    ipx: {
      maxAge: 2592000,
    },
  },
  // ...
})
```

Related source code:

https://github.com/nuxt/image/blob/dc1ed65613a5e70e72563b91cd21345ca6dd1a9d/src/ipx.ts#L19-L24

**Comment by albertotesoro** [comment]
it seems cache setting are not passed to the function...
anyway i tried to set 

IPX_MAX_AGE="31536000"

in .env file and it worked ^_^

**Comment by randyliugogoout** [comment]
> @albertotesoro Could you tell me where can I find the .env file?

In your nuxt2 project's .env file. If there is no .env file in your project, you can create one or add `IPX_MAX_AGE=<cusomized-max-age>` in your start/build command.

If your project is based on nuxt3. You can directly set maxAge in `nuxt.config.js`:

```
image: {
    provider: 'ipx',
    ipx: {
        maxAge: 3600
    }
},
```
[related PR](https://github.com/nuxt/image/pull/706)

**Comment by yuzu-qroulland** [comment]
Hello mates, my project is based on Nuxt 3 and image@rc.2 but when i set maxAge in ipx settings nothing changes..

**Comment by pi0** [comment]
@yuzu-qroulland Would you mind open a new issue with reproduction? It might be a bug we can fix.
