### ISSUE TITLE
Missing documentation of prop placeholder in v1 docs

### ISSUE THREAD

**Issue by sanderdewinter** [nuxt/image#731]
In the component documentation of `nuxt-img` there is nothing described of the prop `placeholder`. It is being documented in [the old version](https://image.nuxtjs.org/components/nuxt-img#props). Can we move this docs to the new version as well?

**Comment by Baroshem** [comment]
Placeholder docs are available now

https://image.nuxt.com/usage/nuxt-img#placeholder

Closing the issue
