### ISSUE TITLE
<nuxt-img> loading lazy not working

### ISSUE THREAD

**Issue by Kelvin4230** [nuxt/image#737]
<img width="707" alt="螢幕截圖 2023-02-06 下午3 55 42" src="https://user-images.githubusercontent.com/27725227/216915920-5500bb13-3e3e-4b38-aa1d-32f70ddb811f.png">
<img width="344" alt="螢幕截圖 2023-02-06 下午4 00 29" src="https://user-images.githubusercontent.com/27725227/216916668-d53b7be3-3962-4db6-899b-814ecc7c11f8.png">
<img width="528" alt="螢幕截圖 2023-02-06 下午3 55 06" src="https://user-images.githubusercontent.com/27725227/216915926-d9e51702-cef8-45ba-88d6-ef91a94d9db4.png">
what is my miss to track viewport.

**Comment by nasdaq-dubai-dfm** [comment]
Same issue.
loading lazy is not working with cloudinary as provider.

**Comment by kwiat1990** [comment]
I have basic setup according to docs and it seems like lazy loading doesn't work at all. Initially I've used `cloudinary` provider, then simply used the entire URL of the image with with removed provider and then some image from the internet. In all cases I did not see any lazy loading functionality.

**Comment by rudykaze** [comment]
Same issue. Lazy loading is not working with remote images

**Comment by rudykaze** [comment]
Its not working if placeholder is set.

**Comment by redakzter01** [comment]
Hi, 
Im still having this issue on Nuxt 3.8.2 and @nuxt/image 1.3.0
No provider, just local image.

**Comment by redakzter01** [comment]
> Hi, Im still having this issue on Nuxt 3.8.2 and @nuxt/image 1.3.0 No provider, just local image.

Turns out that Chrome is the problem, if the image is positioned after 3000px from top it will work.

https://stackoverflow.com/questions/57753240/native-lazy-loading-loading-lazy-not-working-even-with-flags-enabled

**Comment by onkar-rentomojo** [comment]
Not working for me as well. It is loading all the images at once

**Comment by s1mpLyy** [comment]
Same issue with all images without using provider all images loads at page init

**Comment by danielroe** [comment]
This is browser behaviour, not related to Nuxt image.

**Comment by soylomass** [comment]
Does anyone know a working alternative that doesn't rely on the browser implementation?

**Comment by s1mpLyy** [comment]
> Does anyone know a working alternative that doesn't rely on the browser implementation?

You can use the normal html semantic `<img loading="lazy" />`

**Comment by soylomass** [comment]
> You can use the normal html semantic `<img loading="lazy" />`

But that would be relying on the browser implementation, just as NuxtImg does. And it doesn't work in Chrome (it instantly loads all images y < 3000px, which means all the images, on my site.

**Comment by s1mpLyyyyy** [comment]
This issue is still alive

**Comment by danielroe** [comment]
@s1mpLyy please open a new issue with a reproduction if so 🙏

**Comment by srunrotha604** [comment]
Hey guys, Is there any have the same issue like me i used loading="lazy" with Nuxt-Image but it not work properly all image load immediately after page mounted, i want to use it to optimize page load that why i want to load image only in viewport but it work fine with native img tag
here my code:
<img width="315" height="151" alt="Image" src="https://github.com/user-attachments/assets/84d7180b-4690-4b93-880a-83e726326a39" />

.
and here worked version with native img tag:

<img width="230" height="77" alt="Image" src="https://github.com/user-attachments/assets/2807fcb9-9748-46d3-a142-722297c68ae3" />
