### ISSUE TITLE
[Vue warn]: Failed to resolve component: nuxt-img

### ISSUE THREAD

**Issue by seetpalsingh** [nuxt/image#745]
Please help me on your plugin setup.

I have added "@nuxt/image": "^0.7.1" to my nuxt3 test project.

and i am getting fail to resolve nuxt-img.

see that attachments for configurations and setup:

![Screenshot from 2023-02-15 17-22-02](https://user-images.githubusercontent.com/4477434/219020694-74d1eb84-2710-4874-a943-65d05d6180e6.png)
![Screenshot from 2023-02-15 17-22-27](https://user-images.githubusercontent.com/4477434/219020701-70276652-4455-4c55-8e09-6140b141be63.png)

**Comment by danielroe** [comment]
That's not the right version for Nuxt 3. Instead, use `@nuxt/image-edge` for the moment.

**Comment by richgcook** [comment]
I'm still getting this Nuxt 3.6.5

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
