### ISSUE TITLE
Vercel deployment issue

### ISSUE THREAD

**Issue by Croodo** [nuxt/image#751]
I want to disable vercel image optimization. But I can't find any configuration. 
Is there any way to simply use nuxt image as it is without vercel optimization?

**Comment by pi0** [comment]
Hi. You can explicitly set `image.provider` to `ipx` in `nuxt.config`

**Comment by Croodo** [comment]
Thanks, pi0  You just saved my day 😀.
 I was trying to set ipx as middleware.
