### ISSUE TITLE
Module does not work with Netlify

### ISSUE THREAD

**Issue by ikovac** [nuxt/image#758]
When I run `npm run generate` command locally everything works as expected but it does not work on Netlify.
I get the following error:

![Screenshot 2023-02-27 at 14 29 22](https://user-images.githubusercontent.com/26693037/221576595-64891428-85a1-497d-9943-84303054a8e4.png)

I am using default settings (no custom provider)

I am using nuxt version: 3.1.1 and "@nuxt/image-edge": "^1.0.0-27919678.2f5b64b".

**Comment by gregoirepuget** [comment]
install working for me with 'npm run build' but images not generated in static folder...
