### ISSUE TITLE
`useImage()` return type is `any`

### ISSUE THREAD

**Issue by guy-confetti** [nuxt/image#764]
Seems to be working in the playground, but when used in a Nuxt project the generated `composables.d.ts` on `@nuxt/image-edge` is incorrect:
```ts
export declare const useImage: () => any;
```

example: https://stackblitz.com/edit/github-qw2cmn?file=composables%2FuseImageFix.ts

**Comment by danielroe** [comment]
This issue is now resolved: https://unpkg.com/browse/@nuxt/image-edge@1.0.0-28092791.682b674/dist/runtime/composables.d.ts
