### ISSUE TITLE
Adding a second BaseUrl?

### ISSUE THREAD

**Issue by izzygld** [nuxt/image#767]
When using Cloudinary as a provider:

Can we add another baseURL?

i.e.
```
  image: {
    provider: 'cloudinary',
    cloudinary: {
      baseURL: 'https://res.cloudinary.com/<cloud_name>/image/fetch/',
      baseURL2: 'https://res.cloudinary.com/<cloud_name>/image/upload/'
}
```

**Comment by Baroshem** [comment]
The idea for `baseUrl` is to have only one. I think if you need additional one, the better approach would be to create a custom provider for the second one.

Closing as it is a quite old issue.
