### ISSUE TITLE
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'dir')

### ISSUE THREAD

**Issue by ibrahim-990** [nuxt/image#780]
### Environment

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'dir')

### Reproduction

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'dir')

### Describe the bug

![error generate](https://user-images.githubusercontent.com/65185082/227225201-3a530032-cb6d-4e4c-a780-577d457417a5.png)

i work on nuxt 3 project and i get this error on npm run generate

**Comment by mathsgod** [comment]
I think you are using IPX provider. You need to provide runtimeConfig options in nuxt.config.ts for ipx dir

For example my images are store at assets folder, you need to provide options belows:
```
export default defineNuxtConfig({
    modules: [
        '@nuxt/image-edge',
    ],
    runtimeConfig: {
        ipx: {
            dir: '../../assets',
        }
    },
    image: {
        dir: 'assets',
    }
})

```

**Comment by hfte** [comment]
Solves the error, but with loosing the intended functionality: full static output.

**Comment by Smef** [comment]
It looks like, for SSG at least, some of the config options which before were in `image` are now required in `runtimeConfig.ipx`

For me, the default `dir` value of `public` no longer seemed to be active and required manual configuration. The `domains` configuration needed to be moved to the new location as well.

Before 3.3:
```
export default defineNuxtConfig({
    image: {
        domains: [
            'assets.mycompany..com',
        ]
    },
})
```

After 3.3:
```
export default defineNuxtConfig({
    runtimeConfig: {
        ipx: {
            dir: path.resolve('./public'),
            domains: [
                'assets.mycompany.com',
            ]
        }
    },
})
```

**Comment by ibrahim-990** [comment]
anyone know how improve performance with nuxt3

**Comment by damieng** [comment]
Also running into this issue.

I'm using `nuxt generate` to create a fully static site but it seems ipx is expecting to run in runtime mode and so it's complaining about its missing `dir` setting - I don't want to add this because I don't want a runtime ipx - I want built-time assets generated and deployed like I had with nuxt 2.

**Comment by Smef** [comment]
@damieng  the configuration update described in my previous post will resolve this for you.

**Comment by damieng** [comment]
> @damieng the configuration update described in my previous post will resolve this for you.

No, that isn't working for me here. That just stops the console warning errors - what then happens is it doesn't actually generate the static images at build time.

I feel like the error is in that it's trying to do ipx runtime instead of build time - hence that error and why that makes the error go away - but it's "fixing" the wrong thing.

**Comment by Smef** [comment]
Make sure you do the absolute path as described in my post. The path you have in your existing config is not valid, so you can’t just copy and paste it over. Are you using the “generate” command to generate a static site? I understand the concerns about the runtimeConfig, but this is for SSG.

**Comment by damieng** [comment]
If I try to use path.resolve then I get a bunch of errors about them not being a URL - I suspect this is the usual problem of people using local file paths as URLs which does not work on Windows.

**Comment by tresko** [comment]
A bug was introduced with the following PR: https://github.com/nuxt/image/pull/779/files

This seems to have no effect https://github.com/nuxt/image/blob/main/src/ipx.ts#L33 because the ipx runtime config is undefined https://github.com/nuxt/image/blob/main/src/runtime/ipx.ts#L8.

When I printed out the runtime config I got the following data:

```
  const opts = useRuntimeConfig().ipx

  console.log('IPX options:', opts, useRuntimeConfig())
```

```
IPX options: undefined {                                                                                                                               20:07:51
  app: {
    baseURL: '/',
    buildAssetsDir: '/_nuxt/',
    cdnURL: ''
  },
  nitro: {
    envPrefix: 'NUXT_',
    routeRules: {
      '/__nuxt_error': [Object],
      '/_nuxt/**': [Object]
    }
  },
  public: {}
}
```

**Comment by andremenrath** [comment]
Thank you all for resolving this!

**Comment by Smef** [comment]
I've installed the latest version which is supposed to have this issue resolved. It seems that neither the old config settings nor the new config settings currently work to get local images to generate, either in the public folder or a with the custom `dir` setting.

The errors don't happen any more, but neither does the actual image generation.

Does anyone know what the new config settings are supposed to look like?

**Comment by ibrahim-990** [comment]
My nuxt.config is 
 image: {
    dir: "public/",
  },
  runtimeConfig: {
    ipx: {
      dir: "../../public",
    },
  },
  
  and when (npm run generate) i dont get any images in output folder!

**Comment by ibrahim-990** [comment]
@damieng

**Comment by danielroe** [comment]
Please try with the latest edge release. 🙏

**Comment by ibrahim-990** [comment]
I'm start a new project nut3 and add ("@nuxt/image-edge": "^1.0.0-28004510.a0dc8e8",) to test images
and i get errors
please answer me how to solve this.
![issue-nuxt-image](https://user-images.githubusercontent.com/65185082/229287668-ce808ec8-cdc7-4725-a22f-65471ce9e992.png)

**Comment by ibrahim-990** [comment]
@damieng

**Comment by ibrahim-990** [comment]
@andremenrath Can you help me?

**Comment by danielroe** [comment]
@ibrahim-990 Please open a new issue with a reproduction, and please do not ping people unnecessarily.
