### ISSUE TITLE
Allow per environment provider baseUrl using runtimeConfig

### ISSUE THREAD

**Issue by michael-bouvy** [nuxt/image#782]
We are using `imgix` a image provider and have distinct distributions: one for testing environments, and one for production.

Is there a way a provider's `baseUrl` could be set from an environment variable, at runtime? The same way it can be done using `NUXT_*` variables to override Nuxt's `runtimeConfig`.

I see there is a `NUXT_IMAGE_PROVIDER` environment variable used in the code ; we could create custom providers (based on `imgix`) with distinct names (i.e. `imgix_test` and `imgix_prod`) and set the environment variable accordingly on environments, but not sure how this will behave on client side?

Thanks!

**Comment by or2e** [comment]
@michael-bouvy
I may have misunderstood your question, but in the custom provider you have access to `useRuntimeConfig`
```
import { joinURL } from 'ufo';
import { type ProviderGetImage } from '@nuxt/image';

export const getImage: ProviderGetImage = (src) => {
    console.log('useRuntimeConfig();', useRuntimeConfig().public.cdn.baseURL);

    return {
        url: joinURL(useRuntimeConfig().public.cdn.baseURL, src),
    };
};
```

**Comment by Baroshem** [comment]
Closing as the solution was provided in the comment.
