### ISSUE TITLE
`nuxt generate` Throw error while generate images

### ISSUE THREAD

**Issue by Kobreros** [nuxt/image#790]
I noticed that error starts in version 1.0.0-27991540.2b960c4. Previous versions work fine.
`[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'dir')`
No image files are generated in this case.

@nuxt/images: 1.0.0-28002839.c6a7c9b (latest)
nuxt: "^3.3.2"
node: v18.12.1
npm: 9.1.2

Reproduction repository.
https://github.com/Kobreros/broken-nuxt-images

**Comment by Cedric-ruiu** [comment]
I encounter the same problem with `generate`

@nuxt/images: 1.0.0-28020728.5df24eb (latest)
nuxt: 3.3.2
node: 16.19.0
npm 8.19.3

**Comment by Baroshem** [comment]
Closing as this is a really old issue.
