### ISSUE TITLE
ERROR  [nuxt] [request error] [unhandled] [500] The URL must be of scheme file

### ISSUE THREAD

**Issue by hmingv** [nuxt/image#799]
Hi, everyone.

I've been following issue https://github.com/nuxt/image/issues/780.

I ran into the same problem, but it was fixed by the maintainers later. Great!

However, when I updated to the latest version, it brought me new errors:

When run `npm run generate`:

> ERROR  [nuxt] [request error] [unhandled] [500] The URL must be of scheme file

run `npm run dev` without any errors, everything is fine

My environment is:
System: Windows 11
Node: v16.15.1

Below is the minimal implementation I provided, at least for now it's tested on Windows to get the same error.

[codesandbox](https://codesandbox.io/p/github/hmingv/for-nuxt-image/master?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clg07e2s0000dg3g0hvig7sda%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg07e5r9000x3n6iny3gna3f%2522%253A%257B%2522key%2522%253A%2522clg07e5r9000x3n6iny3gna3f%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clg07e5ra000y3n6itysdeprj%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A24678%252C%2522key%2522%253A%2522clg07ehzr009x3n6ikk7uuqgb%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clg07efpl007c3n6ia2zu17at%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg07e5r9000x3n6iny3gna3f%2522%252C%2522spacesOrder%2522%253A%255B%2522clg07e5r9000x3n6iny3gna3f%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
or 
https://github.com/hmingv/for-nuxt-image

**Comment by hmingv** [comment]
I made some changes to nuxt.config.ts and now running `pnpm run build` gives the same error.

**Comment by hmingv** [comment]
![image 1](https://user-images.githubusercontent.com/57735185/229398710-e83be822-d50a-432e-a5d3-996141c122bd.png)

When running `npm run build` or `npm run generate` on a Linux OS, I don't get any errors and everything seems to work fine.

But in fact, when accessing the packaged URL, the svg image cannot be displayed normally.

Directly accessing the svg address through the browser will get the error in Figure 1.

**Comment by mathsgod** [comment]
I have tested same code in Window and Linux, This error only occur in Window platform.
I think the problem is due to this line of code `new URL(opts.dir, import.meta.url)` in `src/runtime/ipx.ts`.

For Window platform, dir will become `C:/Users/<projects_paths>/assets` folder, it cannot be pass to `new URL` as input and throw `[nuxt] [request error] [unhandled] [500] The URL must be of scheme file` error.

Environment is:
nuxt: 3.3.3
@nuxt/image-edge: 1.0.0-28004510.a0dc8e8

**Comment by m7rlin** [comment]
There's now way to fix this for me in the config file.
I cloned the module locally and changed `nuxt-image\src\runtime\ipx.ts`:

```js
// ..
import { resolve } from 'path'
// ..
const ipxOptions = {
    ...(opts || {}),
    // TODO: Switch to storage API when ipx supports it
    dir: resolve(fileURLToPath(import.meta.url), opts.dir),
}

// ..
```

It seems to be working on Windows.

**Comment by safransatan** [comment]
@m7rlin Thanks for the fix, works the same for me. Works by the way also if you comment out the line

**Comment by hmingv** [comment]
> ![image 1](https://user-images.githubusercontent.com/57735185/229398710-e83be822-d50a-432e-a5d3-996141c122bd.png)
> 
> When running `npm run build` or `npm run generate` on a Linux OS, I don't get any errors and everything seems to work fine.
> 
> But in fact, when accessing the packaged URL, the svg image cannot be displayed normally.
> 
> Directly accessing the svg address through the browser will get the error in Figure 1.

When using the <nuxt-img /> component, if the source file is in svg format, specify format="svg", at this time, the image cannot be seen on the page, check the code here through F12 review element, you will find that / _ipx/f_svg/assets/svg/demo.svg Such a path, interestingly, modify f_svg to f_webp, the image can be accessed.

Vice versa, if you specify the format as webp, a path like /_ipx/f_webp/assets/svg/demo.svg will be generated, and you need to modify f_webp to f_svg to continue accessing.

**Comment by Bumbleboss** [comment]
Are there any updates on this being added to edge?

**Comment by danielroe** [comment]
let's track in #797.

**Comment by reallymello** [comment]
Also suffering here Windows 10

**Comment by lxccc812** [comment]
How to solve the problem that is still there

**Comment by m7rlin** [comment]
> There's now way to fix this for me in the config file. I cloned the module locally and changed `nuxt-image\src\runtime\ipx.ts`:
> 
> ```js
> // ..
> import { resolve } from 'path'
> // ..
> const ipxOptions = {
>     ...(opts || {}),
>     // TODO: Switch to storage API when ipx supports it
>     dir: resolve(fileURLToPath(import.meta.url), opts.dir),
> }
> 
> // ..
> ```
> 
> It seems to be working on Windows.



> How to solve the problem that is still there

**Comment by lxccc812** [comment]
It doesn't seem to work for me  @m7rlin

**Comment by nickHuang1123** [comment]
我也有一樣的問題 QQ
