### ISSUE TITLE
Add console.warn when using ipx without specifying domain

### ISSUE THREAD

**Issue by Baroshem** [nuxt/image#808]
Hey,

One more feature idea from me. What about displaying a simple console.warn when a user uses default IPX provider and the image.domains is not set?

Currently, nothing will happen to the image when domains is not passed in the config so it may be a bit missleading for the users. A simple warn in the console could help users find the solution more easily :)

**Comment by Smef** [comment]
Please correct me if I'm wrong, but I don't believe you don't need to specify a domain to use ipx. The domain is only necessary if you're trying to process images from a source other than your Nuxt app.
