### ISSUE TITLE
Using nuxt-img in nuxt content markdown

### ISSUE THREAD

**Issue by gmsa** [nuxt/image#813]
Hi,
Is there any way to use the <nuxt-img> component inside nuxt content markdown files?

**Comment by codedge** [comment]
It did not work for me using `<nuxt-image>` in Markdown directly. I created an MDC in `components/content/Image.vue`, f. ex.

```html
<script setup>
defineProps(["imgSrc"]);
</script>

<template><nuxt-img provider="cloudinary" :src="imgSrc" /></template>
```

In my Markdown file I can call it via 

```md
::image{imgSrc="path/to/my/image.png"}
```

**Comment by michalskop** [comment]
I just add for future reference link to the documentation: https://content.nuxtjs.org/guide/writing/mdc/

My example:
```vue
<script setup>
defineProps(["imgSrc"]);
</script>

<template><nuxt-img sizes="sm:100vw md:50vw lg:350px" format="webp" loading="lazy" :src="imgSrc" /></template>
```

**Comment by jeannen** [comment]
Would be handy to have an option to auto-parse Nuxt Content images into Nuxt Images!

**Comment by Atinux** [comment]
You can create a Nuxt plugin for this:

```ts
// plugins/content-components.ts
import { NuxtImg } from '#components'

// Add them to main entry (useful for content usage)
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('NuxtImg', NuxtImg)
})
```

Or use it only in the page where you use the `<ContentRenderer>` component:

```vue
<script setup>
import { NuxtImg } from '#components'
</script>

<template>
  <ContentRenderer :value="myContent" :components="{ NuxtImg }" />
</template>
```

**Comment by samuveth** [comment]
> It did not work for me using `<nuxt-image>` in Markdown directly. I created an MDC in `components/content/Image.vue`, f. ex.
> 
> ```
> <script setup>
> defineProps(["imgSrc"]);
> </script>
> 
> <template><nuxt-img provider="cloudinary" :src="imgSrc" /></template>
> ```
> 
> In my Markdown file I can call it via
> 
> ```
> ::image{imgSrc="path/to/my/image.png"}
> ::
> ```

I keep getting the following message on my content pages as soon as I add `Image.vue` to my `/content` folder.

`Document not found, overwrite this content with #not-found slot in <ContentDoc>.`
