### ISSUE TITLE
static generation limited to nuxt image components

### ISSUE THREAD

**Issue by jbreuil** [nuxt/image#820]
When using nuxt image on a static generation you are currently limited by the fact that : 
`prerenderStaticImages(src.value, sizes.value.srcset)`
is only called in both nuxt-img and nuxt-picture which means if you want to use something like  : 
```
<script>
const $img = useImage()
const imgUrl = $img('/img/contact/background.png', {}, { preset: 'cover' })

const urlbackground = computed(() => {
  return `url('${imgUrl}')`
})
</script>
<style>
.form{
  background: v-bind(urlbackground);
  background-repeat: no-repeat;
  background-position: bottom;
  background-size: contain;
}
</style>
```

the url background will lead to 404 because the build will never call the prerender on this url.

To workaround this I tried to call it myself in the script by adding : 
```
import { prerenderStaticImages } from '@nuxt/image-edge/dist/runtime/utils/prerender'
prerenderStaticImages(imgUrl)
```

while it works on a generate, once you start a dev server it ends up killing the build on the import at it fails to resolve 
`import { useRequestEvent } from '#imports'` from [prerender file](https://github.com/nuxt/image/blob/main/src/runtime/utils/prerender.ts)

Is there anyway we could improve the module to support a way to generate additional images outside of components ?

**Comment by Hrishikesh-K** [comment]
I'm facing this too. I was wondering why `npm run generate` is not generating any image unless I use `<NuxtImg>` component. Using `useImage()` doesn't work for Nuxt 3 static generation at the moment.
