### ISSUE TITLE
Nuxt 3 won't start when using @nuxt/image module

### ISSUE THREAD

**Issue by therealokoro** [nuxt/image#821]
Nuxt just doesn't start when this module is registered

Below is a screenshot of the error

![image](https://github.com/nuxt/image/assets/41494675/34320cde-57f0-4ac8-863a-4101243e01fd)

------------------------------

Nuxt project info:

- Operating System: Windows_NT
- Node Version:     v19.3.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.0.0
- Builder:          vite
- User Config:      css, app, srcDir, serverDir, modules, colorMode, imports, unocss, runtimeConfig, vite
- Runtime Modules:  @unocss/nuxt@0.51.8, @vueuse/nuxt@10.1.0, @pinia/nuxt@0.4.9, @formkit/nuxt@0.16.5, nuxt-unhead@1.4.17, @nuxt/devtools@0.4.5, @nuxtjs/color-mode@3.2.0, @nuxt/image@0.7.1
- Build Modules:    -
------------------------------

**Comment by danielroe** [comment]
You are using the Nuxt 2 version of the image module - update to `@nuxt/image-edge` until v1 is released.
