### ISSUE TITLE
Quality degradation when using static loading

### ISSUE THREAD

**Issue by NitkiewiczArtur** [nuxt/image#824]
Any image that I load statically suffers from visible quality degradation. I am experiencing this problem not only in my professional project but also in a new one that I started solely for testing.
`<nuxt-img
        src="/imgs/ufc.jpg"
        height="300"/>`
  ` <img
        src="/imgs/ufc.jpg"
        height="300"/>`
stackblitz: https://stackblitz.com/edit/github-w6cj1g-qxwryb?file=pages/index.vue
Is there any setup not described in the documentation to fix this, or is it possible that no one noticed the problem before?
![image](https://github.com/nuxt/image/assets/52032502/e9f6bdce-fd4e-4c32-8a2f-edb8c9f5ea51)

**Comment by rahulkumarsingh73690** [comment]
Same issue

**Comment by Smef** [comment]
It looks like you're getting some JPG compression here. You can try increasing the jpg quality using the quality setting (https://image.nuxtjs.org/components/nuxt-img#quality) or using a different formatsuch as webp or png (https://image.nuxtjs.org/components/nuxt-img#format).

This will probably be an issue compressing and saving any image as jpg with any platform, as that's just how jpgs work.

**Comment by NitkiewiczArtur** [comment]
If you use quality 100 and webp also doesnt help.. it has nothing to do with jpg. I use only webp in professional project and problem is the same.

**Comment by danielroe** [comment]
I believe this might be fixed with the new automatic support for retina (2x) density. (You can also support greater densities.) Would you try the edge channel to see?

**Comment by NitkiewiczArtur** [comment]
I updated from to rc and nothing changed.

**Comment by NitkiewiczArtur** [comment]
I updated project to rc and it havent helped.

**Comment by hartmut-co-uk** [comment]
PS: `densities` will not be shipped until rc.2
You can go back to `@nuxt/image-edge` (also don't forget to change back `modules: [..]` in nuxt.config.ts).

**Comment by NitkiewiczArtur** [comment]
My project is on image-edge.. Do you have any valid example of that functionality working anytime? We are using this library for 2 years and notkhing changed. If You sure it should work on any version, please explain to me how I should configure, maybe give me exact version number that works?

**Comment by chaderenyore** [comment]
Hello everyone, any solution to this problem yet?
