### ISSUE TITLE
"play online" sandbox is broken

### ISSUE THREAD

**Issue by cain** [nuxt/image#825]
Sandbox on readme is broken 

https://codesandbox.io/s/github/nuxt/image/tree/main/example

![Uploading CleanShot 2023-05-17 at 10.02.38@2x.png…]()

**Comment by danielroe** [comment]
This should now be working 👍 

<img width="1129" alt="CleanShot 2023-05-28 at 16 22 07@2x" src="https://github.com/nuxt/image/assets/28706372/a30417ac-dddb-4958-bbc1-9d90a3ec2ebb">
