### ISSUE TITLE
Got error: Uncaught ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by digitdash** [nuxt/image#845]
Keep getting this error on Cloudflare pages whenever attempting to deploy with this package. I saw others had this same issue. How do I fix this?

**Comment by danielroe** [comment]
This was resolved in the first RC with https://github.com/nuxt/image/pull/840 although until the next release, you will need to add the following line to your `nuxt.config`:

```ts
export default defineNuxtConfig({
  image: {
    none: {}
  }
})
```
