### ISSUE TITLE
bug(cloudflare-pages): unknown provider: none

### ISSUE THREAD

**Issue by oritwoen** [nuxt/image#858]
I wanted to deploy to cloudflare pages but in the default configuration it throws 500.

Everything works fine on Vercel.

If the module doesn't work on environment or there is no provider, it should shut down and return regular images.

![Zrzut ekranu z 2023-06-06 23-48-37](https://github.com/nuxt/image/assets/18102267/bc26f1fa-57e3-4f8c-82b5-f416648a112d)

**Comment by danielroe** [comment]
That is indeed the purpose of the `none` provider.

Would you provide a reproduction? 🙏

**Comment by oritwoen** [comment]
Sure.

Repository: https://github.com/oritwoen/nuxt-image-issue-858
Online version: https://nuxt-image-issue-858.pages.dev/

Local:
```sh
pnpm install
NITRO_PRESET=cloudflare-pages pnpm build
npx wrangler pages dev dist/ 
```

**Comment by Smef** [comment]
We're getting the same thing with SSG on CloudFlare Pages. Here's a link to the test build: https://preview-test-two-images.gearboxgo-static.pages.dev/

The generate process gets 500 errors when run on CloudFlare, though it does complete and deploy, and then the browser gets the "unknown provider: none" error.

**Comment by oritwoen** [comment]
@danielroe fun fact. When i set:

`nuxt.config.ts`
```
image: {
    provider: 'none'
}
```

or env:

`NUXT_IMAGE_PROVIDER=none`


Everything works beautifully. There is no 500, there is no error. Clean images are returned.
So apparently provider none is not imported by default somewhere unless explicitly stated.

**Comment by Smef** [comment]
The image.provider = none seems to just disable all image processing. If your images are available in your public folder or a CMS or something like that you would just see the original sources, not processed and resized images. 

That doesn't seem to be the solution here, but maybe the commit from #860 will help?

**Comment by danielroe** [comment]
Try setting:

```ts
image: {
  none: {}
}
```

**Comment by Smef** [comment]
That seems to work in my local environment, but doesn't do any processing in CloudFlare Pages. In that environment it skips all the image processing completely like the `provider:'none'` option

Here's the full image config with this set:

```
image: {
        none: {},
        screens: {
            xs: 320,
            sm: 640,
            md: 768,
            lg: 1024,
            xl: 1280,
            '2xl': 1536,
            '3xl': 3072
        },
        domains: [
            'assets.mycompany.com',
        ],
        dir: 'assets/images/',
    },
```

**Comment by danielroe** [comment]
You will need to enable a different provider. To be clear, `ipx` only works in a node environment.

**Comment by Smef** [comment]
I believe that Cloudflare Pages is running node directly here when it runs the build process (node 18 in this case). It seems to work fine in CFP with nuxt/image-edge v1.0.0-28059208.2abef1b with same config as above minus the `none: {}`.

**Comment by shmatul** [comment]
The next/image-edge **does** resolve the problem. However, when the server is running in production (CF pages), all the images located in the <nuxt-picture/> tag are not rendered. Moreover, the sizes are set just with the same source (/img/hero1x5.jpg).

Rendered HTML page:

`<img onerror="this.setAttribute('data-error', 1)" class="-hero-image" data-nuxt-pic="" src="/img/hero1x5.jpg" sizes="(max-width: 320px) 320px, (max-width: 640px) 640px, (max-width: 768px) 768px, (max-width: 1024px) 1024px, (max-width: 1280px) 1280px, (max-width: 1536px) 1536px, 1536px" srcset="/img/hero1x5.jpg 320w, /img/hero1x5.jpg 640w, /img/hero1x5.jpg 768w, /img/hero1x5.jpg 1024w, /img/hero1x5.jpg 1280w, /img/hero1x5.jpg 1536w, /img/hero1x5.jpg 2048w, /img/hero1x5.jpg 2560w, /img/hero1x5.jpg 3072w">`

Any solution? It works perfectly on my local environment.

**Comment by Smef** [comment]
I think this was discussed somewhere else, but the issue is that Nuxt-image is defaulting to the `none` provider because it doesn't think node exists in the CFP build process.

If you're getting this error in the build process you should be able to leave off the `none` bit and instead set your nitro node environment to be true, which will force the image generation in CFP's build process to use the regular provider.
``` nuxt.config.ts
export default defineNuxtConfig({
    nitro: {
        node: true,
    },
...
...
```

**Comment by shmatul** [comment]
> I think this was discussed somewhere else, but the issue is that Nuxt-image is defaulting to the `none` provider because it doesn't think node exists in the CFP build process.
> 
> If you're getting this error in the build process you should be able to leave off the `none` bit and instead set your nitro node environment to be true, which will force the image generation in CFP's build process to use the regular provider.
> 
> ```ts
> export default defineNuxtConfig({
>     nitro: {
>         node: true,
>     },
> ...
> ...
> ```

Thanks.
I've already seen that solution but adding it to my config fails the CFP build:

```
...


00:40:29.890 | [success] Server built in 6436ms
-- | --
00:40:29.974 | [success] [nitro] Generated public dist
00:40:30.022 | [log] [nitro]   ├─ /__sitemap__/routes.json (0ms)
00:40:30.032 | [info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
00:40:35.995 | [error] [nitro] Error: Could not load /opt/buildhome/repo/node_modules/unenv/runtime/npm/consola/core.mjs (imported by node_modules/unenv/runtime/npm/consola.mjs): ENOENT: no such file or directory, open '/opt/buildhome/repo/node_modules/unenv/runtime/npm/consola/core.mjs'
00:40:35.995 |  
00:40:35.995 |  
00:40:35.995 | undefined
00:40:35.995 | [error] Could not load /opt/buildhome/repo/node_modules/unenv/runtime/npm/consola/core.mjs (imported by node_modules/unenv/runtime/npm/consola.mjs): ENOENT: no such file or directory, open '/opt/buildhome/repo/node_modules/unenv/runtime/npm/consola/core.mjs'
00:40:35.996 |  
00:40:36.055 | Failed: Error while executing user command. Exited with error code: 1
00:40:36.065 | Failed: build command exited with code: 1
00:40:37.157 | Failed: error occurred while running build command
```

**Comment by shmatul** [comment]
@Smef can you please share your package.json and build instructions?

**Comment by Smef** [comment]
The build command is `npm run generate` which builds the static site. Is that what you're doing? If you're not using SSG you are probably running into a separate limitation, which might be that CFP's workers don't run node and therefore IPX won't work.

Here are the nuxt bits and our scripts, though I'm not sure what help this would be here.
```
    "@nuxt/image-edge": "^1.0.0-rc.1-28135297.08462d1",
    "nuxt": "^3.6.1",
```

```
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxi dev --https",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "cleanup": "nuxi cleanup"
  },
```

**Comment by danielroe** [comment]
This issue is not forgotten. There is an open PR to reintroduce the 'static' preset that will generate images with ipx when generating a site.

**Comment by shmatul** [comment]
@Smef I'm using an SSR site on CFP. Static works OK with image. If CFP doesn't use node, what does it use? 
@danielroe A simple solution would be to pre-generate all the assets in the build phase for other SSR hosting solutions like CFP, that also makes sense caching-wise.

**Comment by shmatul** [comment]
Let me know if I can help with developing that feature somehow. I'd love to do that.

**Comment by danielroe** [comment]
That is what the linked PR makes possible, yes.
