### ISSUE TITLE
Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined. 

### ISSUE THREAD

**Issue by hanpandeng** [nuxt/image#859]
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.18.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.17
- Builder:          vite
- User Config:      app, typescript, css, postcss, modules
- Runtime Modules:  @vant/nuxt@1.0.1, @nuxt/image@0.7.0
- Build Modules:    -
------------------------------

yarn add --dev @nuxt/image@rc

export default defineNuxtConfig({
  modules: [
    '@nuxt/image',
  ]
})

![image](https://github.com/nuxt/image/assets/41031240/e50df200-728a-4f48-af21-bfe30d07da71)

I tried to install @nuxt/image-edge and @nuxt/image , the result is still an error

**Comment by danielroe** [comment]
It seems you have an old version of Nuxt Image installed. (See your environment info - v0.7.0 is not the current RC version, which is 1.0.0-rc.1.)

**Comment by hanpandeng** [comment]
> It seems you have an old version of Nuxt Image installed. (See your environment info - v0.7.0 is not the current RC version, which is 1.0.0-rc.1.)

I useing yarn upgrade @nuxt/image@rc , The highest version is only 0.7.1

![image](https://github.com/nuxt/image/assets/41031240/be09792b-f702-42eb-9655-623537a5dd00)

**Comment by hanpandeng** [comment]
> > It seems you have an old version of Nuxt Image installed. (See your environment info - v0.7.0 is not the current RC version, which is 1.0.0-rc.1.)
> 
> I useing yarn upgrade @nuxt/image@rc , The highest version is only 0.7.1
> 
> ![image](https://user-images.githubusercontent.com/41031240/244570848-be09792b-f702-42eb-9655-623537a5dd00.png)

problem solved

yarn add @nuxt/image-edge
modules: ["@nuxt/image-edge"]

good!
