### ISSUE TITLE
I'm a bit confused regarding densities

### ISSUE THREAD

**Issue by Artem-Schander** [nuxt/image#871]
Firstly thanks for this package and sorry for the noise..

I'm trying to get the densities working (custom provider) but they seem not to be available yet (regardles of beeing [documented](https://image.nuxtjs.org/components/nuxt-img#densities))
I have looked through the existing issues and the [PR#769](https://github.com/nuxt/image/pull/769). As far as I can tell it is not released yet?
could plesase someone elaborate?

**Comment by danielroe** [comment]
That's right - the feature is merged but not yet released. It will be in RC2.

**Comment by Artem-Schander** [comment]
ok, thanks
