### ISSUE TITLE
trouble getting nuxt/image@rc ipx provider to work on azure preset 

### ISSUE THREAD

**Issue by sig9** [nuxt/image#881]
I set up a reproduction at

https://github.com/sig9/swa-nuxt-img
Deployment https://[wonderful-meadow-0d9011810.3.azurestaticapps.net](https://wonderful-meadow-0d9011810.3.azurestaticapps.net/)/

The currently deployed commit produces this error
IPX Error: Error: File not found (/home/site/public/feature/test2.png)
for this this image link
https://wonderful-meadow-0d9011810.3.azurestaticapps.net/_ipx/h_800/feature/test2.png

There are three variations that work locally. Each variation in a different commit in https://github.com/sig9/swa-nuxt-img 
My first attempt was with images in /public , works great locally.
When I deployed I saw that IPX was looking in /home/site/public. That directory does not exist.
After some research, I realized that azure swa manages the static output from output_location: ".output/public". If I'm not mistaken, IPX probably will not have access to those files directly.

So I thought to try an external provider. In this commit I referenced the previously deployed site as an external source. It worked locally. When I deployed to the same deployment url, it didn't work. A bit surprising. Unfortunately SWA doesn't provide much visibility to stdout on deployed sites.
https://github.com/sig9/swa-nuxt-img/commit/38e211e59b592765068f53f3c72d41fdad9f6b72

I tried with an alias, again it worked locally but not on SWA.

Finally, I tried putting images in assets/images. Worked locally but not when deployed.

Are there any additional configurations that might work in azure? I may have missed something.

**Comment by asiz15** [comment]
@sig9 did you find any solution?. Im facing the same issue.

**Comment by moshetanzer** [comment]
What is happening with this. Facing the same issue!

**Comment by pi0** [comment]
Please see https://github.com/nuxt/image/issues/675#issuecomment-1893815902 re binary support.

Issues regarding file path should be already fixed in latest stable releases of Image module.

If you have any other issue regarding Azure and Nuxt Image, feel free to open a new issue with recent reproduction 👍🏼
