### ISSUE TITLE
fit="content black background

### ISSUE THREAD

**Issue by Typ0genius** [nuxt/image#885]
This is the code:
```
<nuxt-img alt="" fit="contain" height="300" src="images/iphone-clay.png" width="100" />
```

And this is the result:
<img width="201" alt="Bildschirmfoto 2023-06-21 um 19 58 57" src="https://github.com/nuxt/image/assets/115214945/aa9d236d-0502-4a7a-8b0c-7abaeb83fe80">

The remaining space is filled with black color. How can I make this transparent?

**Comment by pixelpaulaus** [comment]
did you ever figure this one out? to get it to be transparent

**Comment by Baroshem** [comment]
Closing as the workaround was provided
