### ISSUE TITLE
Nuxt Image module with tailwindcss

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt/image#89]
When I changed tags from <img to <nuxt-image, image file disappeared from the page, when I inspected I realized it had `position: absolute;` which was the reason why images get hidden. It's related to how TailwindCSS works.

<img width="976" alt="Screen Shot 2020-11-12 at 10 01 27 PM" src="https://user-images.githubusercontent.com/23562275/98949804-194a9000-24f0-11eb-8a60-3657ad0f6256.png">

here's my component itself:

```
  <div class="relative flex flex-row items-center justify-center w-3/6 mb-5">
    <div class="absolute top-0 left-0 w-48 h-10 pr-10 -ml-48 " >
      {{ imageCaption }}
      <div>
        <div class="mt-2" >
          <slot></slot>
        </div>
      </div>
    </div>
    <nuxt-image :src="imageSource" width="300" height="169" />
  </div>
```

Tried to overwrite the <nuxt-image css but it affected the div not the image img itself.

Thanks.

**Comment by farnabaz** [comment]
@adhamfarrag Sorry for the late response. You are using `nuxt-image` inside a `flex` display and you need to specify `width` using tailwind class helpers of vanilla CSS.  

To clarify why:  
The component does not use `width/height` prop to specify the size of the element, these props only used for calculating the aspect ratio of the image and preserve the aspect ratio of the element.  
By default, the component width will match the parent element but inside the flex layout you need to specify element width yourself and the component will take care of `height`. (the height automatically calculate and set using the aspect ratio of the image).
