### ISSUE TITLE
Issues with multiple format values & ipx

### ISSUE THREAD

**Issue by Sadarex** [nuxt/image#893]
# Environment
Browser: Chrome
Nuxt-Image: 1.0.0-rc.1
Nuxt: 3.6.0

# Issue
Configuring multiple formats seems not to work with ipx.

# Steps to reproduce
## default settings are ignored
Configuring
```
image: {
    format: ['avif', 'webp']
}
```
inside the nuxt.config.ts file is totally ignored.

## format for nuxt-picture breaks with multiple values
Setting
`<nuxt-picture format="avif" />`
works, but
`<nuxt-picture format="avif, webp" />`
results in jpeg images.

**Comment by danielroe** [comment]
This feature is not yet released. You can try it on the edge channel, or in the next RC (expected soon).
