### ISSUE TITLE
After updating to Nuxt 3.6.1, the images don’t behave as before.

### ISSUE THREAD

**Issue by dev02iggy** [nuxt/image#898]
After deciding to update Nuxt, the images started to behave strangely when using this module. <NuxtImg> and <nuxt-img> make the images not respond as before. For example, if before they dominated the space and it was necessary to set limits, now they are small. While in other cases, but rare, the image increased to what it was before.

**Comment by hartmut-co-uk** [comment]
Hi @dev02iggy, to start with, what version of nuxt-image are you using?
What nuxt version did you upgrade from? (3.6.0? 3.5.x?)

Could you also provide an example on how you use `<nuxt-image>` / `<nuxt-picture>`?

**Comment by dev02iggy** [comment]
Aqui é a versão do nuxt-image:
![Captura de Tela 2023-06-27 às 13 47 51](https://github.com/nuxt/image/assets/83841469/89577ac0-0e45-4b48-95a2-a6341ea5b4b4)

Utilizo o `<NuxtImg>`, `<nuxt-image>` ou o `<nuxt-img>`
A versão do Nuxt é a última : 3.6.1

**Comment by frakkio** [comment]
[Screencast from 12-07-2023 12:56:41.webm](https://github.com/nuxt/image/assets/65660656/ca52691b-2578-4138-9301-75dad9666b7d)
Not sure how to describe this kind of issue but it has started right after updating from version 3.3.1 to 3.6.1
Basically there are some picture tag displayed as block that shrink or enlarge randomly depending on the context
the code looks like this:
`<picture>
     <nuxt-img
        preload
        v-bind="{
          width: 660,
          height: 500
        }"
        quality="100"
        :src="props.src"
        :alt="props.alt"
      />
</picture>`
also tried updating with 3.6.2 and the problem still occur

**Comment by Baroshem** [comment]
Closing as this issue is quite old and I cannot observe this issue in the current version of Nuxt and Image module
