### ISSUE TITLE
Nuxt picture doesn't load correct sources

### ISSUE THREAD

**Issue by hjujah** [nuxt/image#906]
This is how we are using the nuxt-picture inside the vue file:
```
<nuxt-picture
:placeholder="[100, 50, 10]"
sizes="sm:768px md:1200px lg:1920px xl:2200px"
quality="80"
:src="image.url"
:alt="image.alt" />
```

This is what we have in the nuxt.config:
```
image: {
  provider: "prismic",
  screens: {
    xs: 320,
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
    xxl: 1536
  }
}
```

The expected image to be loaded on the mobile should be 768px wide, but it seems to always load the biggest one.
You can see the issue [on this link](https://miq.rbln7.com/) basically on every image if you check the network tab.

<img width="2054" alt="image" src="https://github.com/nuxt/image/assets/769078/d2cf2e0e-2b13-47fe-88c6-e80b5cd73bb7">

Are we doing something wrong, or this is likely some bug?

EDIT: I believe this has to do something with the pixel density, but I don't understand how to overcome that issue and how this should be used then? 
Also it's not a cache issue since we are getting the same results in incognito window with the disabled cache.

Btw to compare you can check how the images are behaving on [this website](https://forner.studio/) for example where we have a custom implementation and where everything is loading and behaving as expected.

**Comment by hjujah** [comment]
Why is this closed, there is no real solution on the other issue neither?

**Comment by dreitzner** [comment]
If you make sure your cache is cleared, than it works as expected.

![image](https://github.com/nuxt/image/assets/30938967/418ec8e3-3d1c-4498-9aa1-799b869689ad)

The browser decides which is the best image to show. If there is already a larger image in cache, it will take that one instead of loading a smaller one.
