### ISSUE TITLE
nuxt-picture tag doesn't respect width and height props

### ISSUE THREAD

**Issue by MikeAltinget** [nuxt/image#908]
We want to use `NuxtPicture` for serving `webp` images and falling back to `jpg`. However when setting the `width` and `height` attributes, the image is not resized properly.

# Reproduction
The `picture.vue` file in this repo is a reproduction. Width and height is set to `500`, however the requested image is 3072x3072.

**Comment by Sadarex** [comment]
Did you set `sizes` too?
In case nothing is configured inside your picture tag, nuxt-image uses it's defaults:
https://image.nuxtjs.org/configuration#screens

**Comment by MikeAltinget** [comment]
> Did you set `sizes` too? In case nothing is configured inside your picture tag, nuxt-image uses it's defaults: https://image.nuxtjs.org/configuration#screens

No. I can't see anything in the docs about needing to set `sizes` for `NuxtPicture`. Maybe this is a docs issue?

However I do think it would be more intuitive just to set the `width` and `height`. I don't need the image to be responsive, but I would like to serve a `webp` format in supported browsers

**Comment by rvalenta4** [comment]
I am facing the same issue.

**Comment by Baroshem** [comment]
From what I understand, the NuxtPicture component does not accept these props. You would need to use the NuxtImg component for that
