### ISSUE TITLE
fit property

### ISSUE THREAD

**Issue by dloused** [nuxt/image#91]
`<nuxt-image fit="contain"....`

It seems the fit property is always set to 'cover' no matter what it is defined

**Comment by na86** [comment]
Hi guys, 

same error here `<nuxt-image fit="contain"....`  output `object-fit: cover;`

any thoughts?

Amazing module btw, thank you for your help!

**Comment by Sananes** [comment]
I can also confirm this is happening.

**Comment by farnabaz** [comment]
The `fit` property does not use to change `object-fit` CSS property, Nuxt image using it to resize and scale the image.

**Comment by na86** [comment]
Anyway @dloused if you still need to fix it, just force it by using css.

**Comment by farnabaz** [comment]
Just to mention, the module still in WIP, and I don't recommend using it in production, The first alpha release will be out soon and it has some BREAKING CHANGES for good reasons 👍

**Comment by na86** [comment]
Thank you @farnabaz , 
can't wait to see the new release and use it in prod
in the meantime thank you!!

**Comment by pkpowell** [comment]
How do I set the image height for the image-resize function (not the css property mentioned above)?
Setting the path to eg `http://localhost:3000/_image/ipx/local/_/s_180_180_inside/img.jpeg` works great, but `sizes="180 180"` has no effect.
