### ISSUE TITLE
Too many Requests on single image

### ISSUE THREAD

**Issue by professorhaseeb** [nuxt/image#910]
I'm using IPX with firebase storage using `"@nuxt/image": "^1.0.0-rc.1",`

it's making multiple requests for a single image and exhausting bandwidth.

![image](https://github.com/nuxt/image/assets/1492888/e80da69b-63e3-4d93-bef4-e85d8bfb3772)

Previously using `"@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",` which was working fine.

**Comment by madebyfabian** [comment]
Can confirm. The latest edge version `1.0.0-rc.1-28143901.afe4120` works fine. No duplicated requests. On the current rc version `1.0.0-rc.1`, I get duplicated requests (e.g. on mobile, two images are being loaded, the correct one and also the one for desktop with the config sizes: `sm:100vw lg:450px`). And also, on window resize, the images do not update.

**Comment by professorhaseeb** [comment]
this issue still exists on `@nuxt/image@rc` using IPX

**Comment by dosstx** [comment]
I noticed my images are downloading twice.

**Comment by Arxi** [comment]
The image is downloaded for me twice as well. These are my npm packages:

```
@nuxt/content@2.13.2
@nuxt/image@1.8.0
@nuxtjs/tailwindcss@6.12.1
@tabler/icons-vue@3.16.0
nuxt-bus@0.9.3
nuxt-easy-lightbox@1.0.2
nuxt-gtag@3.0.1
nuxt@3.13.1
vue-router@4.4.4
vue@3.5.4
```

This is what I have in my nuxt config:

```
  image: {
    provider: "ipx",  // the default
  },
```

I have this simple page in `pages/test.vue`:

```vue
<template>
    <NuxtImg src="/images/1-front-matter.webp"
            sizes="500px"
            placeholder="/x-600.png"
    />
</template>
```

What I see in developer console in Network tab is this:
![Screenshot 2024-09-10 at 22 03 12](https://github.com/user-attachments/assets/f66d37ad-5ea9-4bc5-a7a6-e4334396246f)

Two separate requests are sent. One image is 37kB, but 78.7kB of image data was transferred (that includes favicon and the placeholder image which is cancelled and then downloaded anyway).

If I remove the placeholder line:

```vue
<template>
    <NuxtImg src="/images/1-front-matter.webp"
            sizes="500px"
    />
</template>
```

the image is correctly loaded just once:

![Screenshot 2024-09-10 at 22 06 20](https://github.com/user-attachments/assets/293d4bef-32a0-4567-8cd7-1ad0355ec125)

If I use the placeholder like this:
```vue
<template>
    <NuxtImg src="/images/1-front-matter.webp"
            sizes="500px"
            :placeholder="[50, 50]"
    />
</template>
```

my image is again downloaded twice, with one cancellation:
![Screenshot 2024-09-10 at 22 09 19](https://github.com/user-attachments/assets/0780eac8-fcd2-4a69-90ea-bd304eb2dfed)

This happens in `nuxt dev` and also when I use `nuxt generate` and preview the site.

I tried to [replicate it in CodeSandbox](https://codesandbox.io/p/devbox/nuxt-image-placeholder-bug-qpl7vr?workspaceId=4318f5ed-9331-41ed-a5e4-7472d5f45007&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0wr1ydf00073b6vqilzh6co%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0wr1ydf00023b6v2ijvdwru%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0wr1ydf00043b6v16h196my%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0wr1ydf00063b6v8oudbwvf%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0wr1ydf00023b6v2ijvdwru%2522%253A%257B%2522id%2522%253A%2522cm0wr1ydf00023b6v2ijvdwru%2522%252C%2522activeTabId%2522%253A%2522cm0wtzokq00023b7040moa77n%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wr1yde00013b6vlgrhgml6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cm0wrdnvm004i3b6uh9wgmsgw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0wtzokq00023b7040moa77n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cm0wr1ydf00063b6v8oudbwvf%2522%253A%257B%2522id%2522%253A%2522cm0wr1ydf00063b6v8oudbwvf%2522%252C%2522activeTabId%2522%253A%2522cm0wtf7z5009k3b6ukrjyrn9u%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wr1ydf00053b6vp7kx2buo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Atrue%252C%2522id%2522%253A%2522cm0wr34dj000k3b6ubb2niqex%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522VIRTUAL_MACHINE%2522%252C%2522id%2522%253A%2522cm0wtf7z5009k3b6ukrjyrn9u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0wr1ydf00043b6v16h196my%2522%253A%257B%2522id%2522%253A%2522cm0wr1ydf00043b6v16h196my%2522%252C%2522activeTabId%2522%253A%2522cm0wr1ydf00033b6vgocya479%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wr1ydf00033b6vgocya479%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522generate%2522%252C%2522id%2522%253A%2522cm0wrw0bd00783b6u6q7e5qjp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%252C%2522id%2522%253A%2522cm0wrwqqh007o3b6uu3376vft%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), unfortunately I don't see any images loaded in the developer tools in Preview pane, so I'm not sure what's happening there.

![Screenshot 2024-09-10 at 22 14 17](https://github.com/user-attachments/assets/ca90a708-fe38-4d3e-bb0f-6793bd3265b8)


**But when I open the official playground,** let it load and then reload just the Preview pane with the reload button, I see `mountains_1.jpg` being downloaded twice as well (the first one is the small placeholder):

![Screenshot 2024-09-10 at 22 23 05](https://github.com/user-attachments/assets/ebae2188-a76f-4579-b695-8a7ecbe641b1)

**Comment by ram-you** [comment]
Hi @Baroshem 
Please reopen this issue as it's not solved.
Thank you

**Comment by UnSpiraTive** [comment]
@Baroshem 
 
I copied an example from the docs with custom props and added ```v-if``` or a ```:key```, and it's making 2 requests. Is this a bug or can I manage it somehow?

**Edit:** using example from docs (```custom=true```), always fire 2x times request on init load.  (disabled cache)
