### ISSUE TITLE
Cannot destructure property 'file' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by jorge-vnarvaez** [nuxt/image#911]
Hi, i'm installing @nuxt/image on my nuxt 2 project but i'm getting this error.

Cannot destructure property 'file' of 'undefined' as it is undefined.

**OS**
Windows 10 64bits

**Node version**
16.17.0

**Package manager**
Yarn

This is how i configure my nuxt.config.js file

```js
target: 'static',
// Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
buildModules: [
    '@nuxtjs/vuetify',
    '@nuxt/postcss8',
    '@nuxtjs/moment',
    '@nuxt/image',
],

image: {

},
```
Any ideas of what i'm doing wrong?

**Comment by jjephson** [comment]
Hello,

Not sure if this helps but I got the same error when I used: npm i @nuxt/image (from the NPM page: https://www.npmjs.com/package/@nuxt/image).

But in the nuxt image documentation (https://image.nuxtjs.org/get-started) they tell you to use: **npm install -D @nuxt/image@rc**

This worked for me, no problem at all now. I hope it might solve yours as well.

**Comment by jorge-vnarvaez** [comment]
Wonderfull now it's working. Thank you so much.
