### ISSUE TITLE
Cloudinary chained transformations

### ISSUE THREAD

**Issue by bart** [nuxt/image#913]
Hey, first of all thanks for the great module to deliver optimized images in a Nuxt project easily.
For a project I'm using Cloudinary as my image provider. We want to resize an image dynamically and also want to add a watermark (also resized) onto that image. The only approach we see here are `Chained Transformations` which a separated by a slash.

For example: `https://res.cloudinary.com/bucket/image/upload/c_fill,h_1200,w_800/c_scale,g_south_east,l_logo,w_150,x_30,y_30,o_30/v1234567890/image.jpg`

I'm now wondering which property I have to use to add the image as a separate chunk (with an additional slash like in my example above). Everything I tried out with `modifiers` add them to the same chunk (without an additional slash). Any help is highly appreciated, thanks in advance!

**Comment by vanling** [comment]
I'm guessing this is still not possible?

**Comment by Baroshem** [comment]
Hey there, if you still have this issue, I may recommend trying Nuxt Cloudinary module that allows for more transformations out of the box :)
