### ISSUE TITLE
nuxt-picture loads multiple sources in safari while loading paginated results (infinite scroll)

### ISSUE THREAD

**Issue by dennisadriaans** [nuxt/image#914]
i have an infinite scroll list in Nuxt 2, and I use picture elements for the images. In Chrome, the picture tag controls which sources are fetched from the server, even if the content is dynamically added. However,  a small JPEG, a large JPEG, and finally the desired WebP. 

Extra note: while loading dynamic/paginated data, all images are served at once, loading="lazy" attribute not working on dynamic content.

I expected the picture tag to control which sources are fetched from the server, just as it does in Chrome. However, in Safari, three images are loaded per picture tag, which is not the desired behavior.

I would appreciate it if you could investigate this issue and let me know if there is a way to fix it.

Image example = browserstack

`        <nuxt-picture
          :src="imageUrl"
          :img-attrs="{loading: 'lazy'}"
        />`

![safari-bug](https://github.com/nuxt/image/assets/9150766/3c8af4cc-bbee-4db2-a8ac-569a4404de39)

**Comment by Sadarex** [comment]
Is your infinite scroll solution using https://imagesloaded.desandro.com/ or something similar? In the case of "imagesloaded" the isses comes from this library and not from nuxt-image.

**Comment by dennisadriaans** [comment]
No we write is ourself, a simple array fetched in asyncData hook. Then, when bottom of the list is almost visible in the viewport we push new entries into the array. Nothing special.

**Comment by danielroe** [comment]
`loading=lazy` is now supported in Safari, so we can close this.
