### ISSUE TITLE
IPX image paths containing sizes are invalid on Mac 

### ISSUE THREAD

**Issue by Jordan-Ellis** [nuxt/image#922]
When prerendering with the IPX provider, the image path contains colons when using image sizes:
![screenshot](https://github.com/nuxt/image/assets/18269476/5940fc56-9485-4d30-8e57-cccaf782ed2c)

Colons are an invalid character for file names on mac and they turn into slashes, causing a 404:
![Screenshot 2023-07-19 at 8 54 41 PM](https://github.com/nuxt/image/assets/18269476/0007e726-bc6f-4da8-907e-ff32d60dc0e4)

IPX out path: `q_75&f_webp&sixes_sm:90vw%20md:480px%20lg:680px&loading_lazy&w_1536`
Mac out path: `q_75&f_webp&sixes_sm/90vw%20md/480px%20lg/680px&loading_lazy&w_1536`

Is there way to remove the colon or replace it with a different character when generating the file name?

**Comment by Baroshem** [comment]
Hey there,

I dont think there is a way right now and not sure if there are any plans for that.
