### ISSUE TITLE
IPX 404 File not found 

### ISSUE THREAD

**Issue by Morraycage** [nuxt/image#925]
Hi hope you are doing great i'm using `nuxt3@latest` and `nuxt/image@rc` and it seems it's not working pretty well when using `nuxi generate` ...

I'm getting this error:

`http://localhost:3000/_ipx/_/illustrations/home-header-illu.png 404 (Not Found)`

I'm using it in the template like this:
`<NuxtImg preload src="/illustrations/home-header-illu.png" aria-hidden="true" />`

When `/illustrations` is a folder inside of the `public` directory

It seems that in local the file is resolved by `ipx` but in prod after looking at the `.output` folder there is no existence of `ipx`

How can i make it work ? 

Thank you

**Comment by luis-agm** [comment]
@Whbbit1999 that error seems to imply that a dependency is missing for the IPX server, since Sharp is the package used for image manipulation.

To be clear, you are getting a 404 on the client side and getting this error on the server side on every image request?

**Comment by Whbbit1999** [comment]
@luis-agm  Yes. After packaging, if you place the generated .output folder directly on the server, an error will be reported. Could it be a problem caused by different systems?

**Comment by luis-agm** [comment]
Yes, I believe since sharp is a native dependency it has to be compiled for the specific architecture of the production server. You could potentially try to run the build inside a docker container with the default [Node image](https://hub.docker.com/_/node/) and that should be enough.

However what I find funny is that you get a 404 instead of a 500.

**Comment by dosstx** [comment]
Is it possible it's PNG files only? FOr some reason when I use SVG files, it deploys fine, but 404 if I use PNG.....

**Comment by oguilleux** [comment]
Hi anyone solved this issue ? I get 404 as well.

nuxt 3.6.5
@nuxt/image 1.0.0-rc.1

**Comment by KareemDa** [comment]
`pnpm i -D sharp` solved the problem for me 
"installing the missing dependency"

**Comment by oguilleux** [comment]
I managed to figure out it's because of the spaces inside the name of the file. 

This works : "/public/img/test-image.jpg" 
This doesn't work : "public/img/test image.jpg"

it seems that in dev mode I get this : "_ipx/s_720x1020/img/test%20image.jpg"
but in production with generate : "_ipx/s_720x1020/img/test%2520image.jpg"

same things happen with special caracters. For example the file "María González.jpg" will render :
dev : "_ipx/s_720x1020/img/Mar%C3%ADa%20Gonz%C3%A1lez.jpg"
generate : "_ipx/s_720x1020/img/Mar%25C3%25ADa%2520Gonz%25C3%25A1lez.jpg"

I'm on MacOSX 13.4.1
nuxt 3.6.5
@nuxt/image 1.0.0-rc.1

Can anyone of the module core team help please ?

**Comment by rahulkumarsingh73690** [comment]
Same issue

**Comment by vanminhquangtri** [comment]
I have same issue and until now i can't solve. The only way I can do is to replace NuxtImg by normal img tag. 
I am sorry but as I see NuxtImg has so many error, not only for Netlify, it also many error when I deploy to other platform such as AWS.

**Comment by oguilleux** [comment]
Managed to solve it by deleting spaces (replaced by _ ) and modifying special characters in the name of the file.

**Comment by getshcc** [comment]
> `pnpm i -D sharp` solved the problem for me "installing the missing dependency"

problem solved. Thank you 🍻

**Comment by getshcc** [comment]
> `pnpm i -D sharp` solved the problem for me "installing the missing dependency"

problem solved. Thank you @KareemDa 🍻

**Comment by jonkuze** [comment]
I'm seeing this issue in production as well on Cloudflare. I've tried all the work-arounds above but nothing works.

**Comment by jonkuze** [comment]
> @jonkuze please make sure that nuxt-image is not running client side. For example you are using this in some component that is placed inside or SSR: false. For me this is problem. Nuxt-image must be at server-side. Good lucks.

Thank you for the response! Interesting enough the Nuxts 3 docs do not state this is strictly a server-side component... it's gives the impression that it is their replacement for <img> 

I removed NuxtImg and just replaced with <img> and everything is working now. Thank you!!

**Comment by vanminhquangtri** [comment]
@jonkuze I mean that you don't need to remove NuxtImage. You only need to make sure that your <NuxtImage> is not rendered inside <ClientOnly>.

**Comment by jonkuze** [comment]
> @jonkuze I mean that you don't need to remove NuxtImage. You only need to make sure that your is not rendered inside .

You mean not rendered on Client Side right? I don't have SSR enabled, my website only uses `nuxt run generate` for static builds. So I think that's the issue. Don't think it will work in static mode.

**Comment by bkan36** [comment]
same issue I use supabase private bucket and nuxt 3 and I can't display my images 

if someone has a solution... tanks in advance

**Comment by 2u841r** [comment]
> > [@jonkuze](https://github.com/jonkuze) please make sure that nuxt-image is not running client side. For example you are using this in some component that is placed inside or SSR: false. For me this is problem. Nuxt-image must be at server-side. Good lucks.
> 
> Thank you for the response! Interesting enough the Nuxts 3 docs doesn't state this is strictly a server-side component... it gives the impression that this is their replacement for `<img>` https://nuxt.com/docs/api/components/nuxt-img
> 
> I removed NuxtImg and just replaced with `<img>` and everything is working now. Thank you!!

worked for me.
 
but previously installed `pnpm i -D sharp`, 
i am not sure is that mandatory with `<img />` 
or simply removing `<NuxtImg />` to `<img />` is enough.
