### ISSUE TITLE
nuxt-picture don't support densities setting, only on nuxt-img

### ISSUE THREAD

**Issue by ausir0726** [nuxt/image#927]
I want to force the densities to 1x on nuxt-picture. Unfortunately, it can only be set on nuxt-img. However, we need to use both webp and jpeg formats simultaneously, so we have to use nuxt-image.

**Comment by hartmut-co-uk** [comment]
Do you want to set it with module config, or for individual components?
Could you provide a code example?
<nuxt-picture> should recognise `densities` settings.

**Comment by ausir0726** [comment]
@hartmut-co-uk 

This fix is specific to the configuration of the nuxt-picture component, and the global config settings work correctly when running with nuxt-picture.

when use `nuxt-img` ( pug template )
```pug
nuxt-img(densities="1", sizes="488px", src="https://img/img.jpg")
```
result
```html
<img src="/_ipx/w_488/https://img/img.jpg" data-nuxt-img="" srcset="/_ipx/w_488/https://img/img.jpg 1x">
```

when use `nuxt-picture` ( pug template )
```pug
nuxt-picture(densities="1", sizes="488px", src="https://img/img.jpg")
```
result
```html
<picture>
  <source type="image/webp"
    srcset="/_ipx/w_488&amp;f_webp/https://img/img.jpg 1x, /_ipx/w_976&amp;f_webp/https://img/img.jpg 2x">
  <img data-nuxt-pic=""
    src="/_ipx/w_976&amp;f_jpeg/https://img/img.jpg"
    srcset="/_ipx/w_488&amp;f_jpeg/https://img/img.jpg 1x, /_ipx/w_976&amp;f_jpeg/https://img/img.jpg 2x">
</picture>
```
expect reuslt ( after fix )
```html
<picture>
  <source type="image/webp"
    srcset="/_ipx/w_488&amp;f_webp/https://img/img.jpg 1x">
  <img data-nuxt-pic=""
    src="/_ipx/w_488&amp;f_jpeg/https://img/img.jpg"
    srcset="/_ipx/w_488&amp;f_jpeg/https://img/img.jpg 1x">
</picture>
```

**Comment by hartmut-co-uk** [comment]
thanks, could you try and set `width` and `height` for your image?

**Comment by ausir0726** [comment]
I can't do that because my image can only provide a maximum of 488px (even less). The computed size is also 488px, and I cannot set a fixed width or height for this image. I need to use the original size of this image to squeeze out space, and only a few images are like this. However, I must maintain compatibility with both webp and jpeg formats. Providing an undersized 2x image disrupts the entire page. Another point is that I hope to have consistency (or almost similarity) in the behavior patterns of both nuxt-picture and nuxt-img.

**Comment by hartmut-co-uk** [comment]
setting `width` and `height` is not used to define how the images should be rendered in the browser, but to allow calculating the aspect ratio and the variants under the `<picture>` element.
I strongly recommend defining how it's supposed to be rendered using CSS.

Let me try to provide an example tomorrow...

**Comment by ausir0726** [comment]
Although the method you provided (setting width) can lock the width of the image, it will stretch the image to the specified width. However, in my case, I need to display the actual width of the image. I have three images displayed side by side to show the differences among them. All three images have the base setting sizes="1200px", but the true pixel width of the image is 1000px (in fact, I don't know the actual size of the image). This means that even if I use w_1200 or w_2400, I can only get an image with a width of 1000px. As a result, the first image, with only a 1000px (w_2400) 2x image available, will be scaled down by the browser for display. The second image has an added setting of width="1200px", and the browser forcibly renders the 1000px image as 1200px in size. However, the third image, which uses densities="1" setting with nuxt-img, displays the image in its true size by using only densities="1".

This configuration means that my end users may upload images larger than 1200px, but I will resize the images to a maximum of 1200px. However, if they upload images smaller than 1200px, I will display them in their true size without enlarging the images to avoid image distortion. Although the usage is not extensive, nuxt-img can handle this situation. However, when I need to support both webp and jpeg formats, switching to nuxt-picture disrupts the layout.


```pug
<template lang="pug">
div
  nuxt-picture(sizes="1200px", src="https://storage.googleapis.com/upage/55a489ca4cfb0e11005f8f9d/2023/06/06/0e47055e467b5169597db29e249d6b28.jpg")
  nuxt-picture(width="1200", sizes="1200px", src="https://storage.googleapis.com/upage/55a489ca4cfb0e11005f8f9d/2023/06/06/0e47055e467b5169597db29e249d6b28.jpg")
  nuxt-img(densities="1", sizes="1200px", src="https://storage.googleapis.com/upage/55a489ca4cfb0e11005f8f9d/2023/06/06/0e47055e467b5169597db29e249d6b28.jpg")
</template>
```


![image](https://github.com/nuxt/image/assets/7247064/04932c2b-cd0f-44d3-83a7-1d4d5c0e6218)

**Comment by ausir0726** [comment]
As proposed in my PR, I have added 'densities' to the generation of 'src' and 'srcset' in nuxt-picture, ensuring that both produce the same results.

https://github.com/nuxt/image/pull/928

```pug
<template lang="pug">
div
  nuxt-picture(densities="1", sizes="1200px", src="https://storage.googleapis.com/upage/55a489ca4cfb0e11005f8f9d/2023/06/06/0e47055e467b5169597db29e249d6b28.jpg")
  nuxt-img(densities="1", sizes="1200px", src="https://storage.googleapis.com/upage/55a489ca4cfb0e11005f8f9d/2023/06/06/0e47055e467b5169597db29e249d6b28.jpg")
</template>
```

<img width="835" alt="image" src="https://github.com/nuxt/image/assets/7247064/b007f536-9cd8-4717-bf41-ee4c1feab529">
