### ISSUE TITLE
How to turn off image optimization？

### ISSUE THREAD

**Issue by senher** [nuxt/image#929]
I don't want to start image optimization, how can I turn off the image address prefix /_ipx/s_1920x700/ automatically added to the image?

**Comment by ausir0726** [comment]
Based on the explanation from unjs/ipx, your issue can be resolved by simply using the _ modifier to obtain the original image. If you only need to use the image proxy functionality, ensure that the nuxt-image module is enabled. The default / _ipx/ path should work correctly. Therefore, you only need to use a regular HTML image tag with the src set to / _ipx/_/http://image.on.www/image.jpg. Alternatively, you can directly integrate unjs/ipx as a middleware in your nuxt project.

**Comment by Matoseb** [comment]
Is there a universal modifier for this? No matter the provider

**Comment by oxedom** [comment]
Any one solved?

**Comment by TechAkayy** [comment]
As per this PR https://github.com/nuxt/image/pull/860, this should work: 

```
// nuxt.config.ts

image: {
    provider: 'none'
}
```
or env:

`NUXT_IMAGE_PROVIDER=none`

**Comment by Baroshem** [comment]
Closing as the solutions was given.

Feel free to reopen if needed :)

**Comment by bropuffshroom** [comment]
> As per this PR [#860](https://github.com/nuxt/image/pull/860), this should work:
> 
> ```
> // nuxt.config.ts
> 
> image: {
>     provider: 'none'
> }
> ```
> 
> or env:
> 
> `NUXT_IMAGE_PROVIDER=none`

this one really should be in the documentation
