### ISSUE TITLE
srcset is not generating correct image urls

### ISSUE THREAD

**Issue by bdrtsky** [nuxt/image#93]
I am using module with Cloudinary, and have setup like:

```js
image: {
    presets: [
      {
        name: '4/3',
        modifiers: {
          fit: 'cover',
          format: 'auto',
        }
      }
    ],
    providers: {
      cloudinary: {
        baseURL: 'https://res.cloudinary.com/nuxt/image/upload/'
      }
    }
  },
```

```html
<NuxtImage sizes="100,300:300,500:500,1000:1000" responsive src="cloudinary+4/3:/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg" />
```

I expect module to generate srcset with different size image variations, but got same image url for each viewport:

```<img alt="4d02deda597adab13fac9341c22458aa" class="__nim_o" style="position: absolute; left: 0px; top: 0px; margin: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; transition: opacity 800ms ease 0ms; opacity: 1;" src="https://res.cloudinary.com/nuxt/image/upload/c_fit,f_auto/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg" srcset="https://res.cloudinary.com/nuxt/image/upload/c_fit,f_auto/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg 100w, https://res.cloudinary.com/nuxt/image/upload/c_fit,f_auto/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg 300w, https://res.cloudinary.com/nuxt/image/upload/c_fit,f_auto/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg 500w, https://res.cloudinary.com/nuxt/image/upload/c_fit,f_auto/vue-telemetry/4d02deda597adab13fac9341c22458aa.jpg 1000w" sizes="(min-width: 1000px) 1000px, (min-width: 500px) 500px, (min-width: 300px) 300px, 100px">```

Reproduction: https://github.com/bdrtsky/image-module-issues

**Comment by emsitkowski** [comment]
I have the same problem.
In my app running on dev server, everything is fine. The problem occurs when I generate static website and deploy it to a hosting. Srcset shows the same url for every breakpoint.
