### ISSUE TITLE
custom provider called 3x

### ISSUE THREAD

**Issue by tasiotas** [nuxt/image#930]
Hi,

I made a custom provider, but it seems its being called 3 times.

![image](https://github.com/nuxt/image/assets/9046931/13063668-e9b0-429a-9cfc-ac07ecfa543b)

Any idea why?

```js
//b2ImageProvider.js
import { joinURL } from 'ufo'

// import {} from '#image'

export function getImage(src, { modifiers, baseURL } = {}, { options, $img }) {
  console.log('hello from b2 provider')
  
  const { width, height, format, fit, ...providerModifiers } = modifiers
  const operations = []
  // process modifiers
  const operationsString = operations.join(',')
  return {
    url: joinURL(baseURL, operationsString, src),
  }
}
```

```js
//nuxt.config.ts
  'image': {
    domains: ['f002.backblazeb2.com', 'cdn.pixabay.com'],
    providers: {
      b2: {
        name: 'b2',
        provider: resolve('./composables/b2ImageProvider.js'),
      },
    },
  },
```

**Comment by tasiotas** [comment]
actually default ipx provider does the same

**Comment by tasiotas** [comment]
its because there were 3 src paths generated... all good

**Comment by niek-o** [comment]
I'm also running into this issue. Did you find any way to solve this? I haven't been able to identify the source yet. 

My last request is twice the resolution of the first two, causing the site to slow down quite a lot.

**Comment by tasiotas** [comment]
my issue was completely my fault. Seems like you are talking about resolution issue? Make sure you set `densities` correctly. At default its `1x 2x`, that will generate 2x larger set of images.

**Comment by niek-o** [comment]
Cool, thanks!
For anyone else having this issue, here's how you fix this:
```html
 <nuxt-img
      src="https://example.com/image.png"
      width="512"
      height="512"
      provider="<provider name>"
      densities="1" <!-- THIS LINE HERE -->
    />
```
