### ISSUE TITLE
Update netlify provider docs for usage without large-media

### ISSUE THREAD

**Issue by JPOstholt** [nuxt/image#936]
Using nuxt-img with netlify actually works without setting up [Netlify Large Media](https://docs.netlify.com/large-media/overview/) if you add the following to your `nuxt.config.js`

```
image: {
    provider: 'netlify',
    netlify: {
      baseURl: process.env.IMAGES_URL
    }
  }
```

If you agree that this makes sense I would add a PR 🙂

**Comment by danielroe** [comment]
That seems a great default!

**Comment by flozero** [comment]
this would work with the ipx issue that target the wrong folder ? If we switch to netlify this way it would work ?

**Comment by cfab** [comment]
No it is not working !
Images are there (instead of 404) but they are not optimized with this setup.

**Comment by robinsimonklein** [comment]
⚠️ This is not a viable solution. As @cfab also said, images will load because they are exposed in `/public`, but no optimization will be applied to them...

@danielroe any plan for the replacement of Large Image Media ?

**Comment by cfab** [comment]
Hello, any news on this rather blocking pbl ?

**Comment by danielroe** [comment]
I think this should be resolved in the latest version of the netlify provider.
