### ISSUE TITLE
Pocketbase Provider

### ISSUE THREAD

**Issue by Niki2k1** [nuxt/image#937]
Hi I am creating a custom provider for the Pocketbase CMS but I am having an issue providing a good dx

The image URL looks something like this:
BASE_URL/api/files/COLLECTION_ID_OR_NAME/RECORD_ID/FILENAME

How should I inject the Collection Id/Name and the Record ID into the src url?

Like this:
```vue
<nuxt-img
  :src="`${collection}/${id}/${filename}`"
  provider="pocketbase"
/>
```

or is there another way to inject anything else but the src? I Imagine somethin likes this:
```vue
<nuxt-img
  :src="filename"
  :collection="collection"
  :id="id"
  provider="pocketbase"
/>
```

Is there any way I can extend the nuxt-img and create those custom props? Or should I just do it like the first example.

**Comment by Niki2k1** [comment]
I noticed both variants use the same amount of writing so I go with the first one.
But I am creating an composable which will look like this:
pbImage(obj, 'key')

This can then get the collection name and id of the obj from the obj itself which makes improves the dx a little.

Would be nice to put that in the nuxt-img provider function but I don't know how to add custom props

**Comment by VictorioBerra** [comment]
@Niki2k1 did you finish this? I am looking for this as well. In my case, I want to just do:

`const url = pocketbase.files.getUrl(record, firstImage);` to get the URL, and then let the provder handler the rest since you will now only need to add `?thumb=100x300`.

`<NuxtImg :src="url" provider="procketbase" />`

Can you share your provider with me?

**Comment by Niki2k1** [comment]
Hi @VictorioBerra I didn't finished a custom provider as I wanted to use the ipx/sharp one. I had to set the url in nuxt config and built myself a little composable
```ts
function getImage<T extends BaseSystemFields<unknown>>(item: T, key: keyof T, index: number = 0) {
    if (Array.isArray(item[key])) {
      return `${BASE_PATH}/${item.collectionName}/${item.id}/${(item[key] as string[])[index]}`
    } else {
      return `${BASE_PATH}/${item.collectionName}/${item.id}/${item[key]}`
    }
  }
  ```
  
  Which I use like this:
  description is the object from pocketbase and images is the field in pocketbase.
  ```ts
  getImage(description, 'images')
  ```
  
  Not ideal but worked for my usecase
