### ISSUE TITLE
ERROR  Cannot start nuxt:  Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ipx' imported from ..node_modules/@nuxt/image/dist/module.mjs                                                                                                   

### ISSUE THREAD

**Issue by jcruzdev6** [nuxt/image#938]
I installed nuxt-image by running "npm install -D @nuxt/image@rc" but I'm getting error as soon as I run npm run dev.
I tried "npm install -D @nuxt/image-edge" also but got the same error.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by jonatanvm** [comment]
I get the same error:

```
 WARN  "ipx" is imported by "node_modules/@nuxt/image/dist/runtime/ipx.mjs", but could not be resolved – treating it as an external dependency.

✔ Nitro built in 1146 ms

 ERROR  [worker reload] [worker init] Cannot find package 'ipx' imported from /.../<my-project>/.nuxt/dev/index.mjs  
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at packageResolve (node:internal/modules/esm/resolve:890:9)
  at moduleResolve (node:internal/modules/esm/resolve:939:20)
  at defaultResolve (node:internal/modules/esm/resolve:1132:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
```

**Comment by dan-hammond** [comment]
I was just having similar issues. It turns out that in our production build we're skipping optional dependencies during our NPM install, and @nuxt/image lists ipx as an optional dependency, causing it to not be present.

The solution I went with was to install ipx directly in my project for now, as I don't really want to install any other optional dependencies.

**Comment by CallBoson** [comment]
> I installed nuxt-image by running "npm install -D @nuxt/image@rc" but I'm getting error as soon as I run npm run dev.
> 
> I tried "npm install -D @nuxt/image-edge" also but got the same error.

I got the same error both in windows and mac, did you solve this problem？

**Comment by samuelreichor** [comment]
Same here

**Comment by ThePlastic** [comment]
Same error here

**Comment by Relianco** [comment]
Try: `npm install -D ipx`

@samuelreichor @ThePlastic @CallBoson

**Comment by ThePlastic** [comment]
> Try: `npm install -D ipx`
> 
> @samuelreichor @ThePlastic @CallBoson

Was not needed, it was enough to update node to the latest version to fix the problem, in the development machine it was still 18.17 it is worth trying

Updating to the LTS solved the problem. Unfortunately, the other IPX related bug is still present on the production environment 


[https://github.com/nuxt/image/issues/1210](url)
