### ISSUE TITLE
Prerendering pages that use `nuxt-img` fails when deploying on the edge

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt/image#939]
Basically the title. Been trying to integrate this module into my site at Lexpeartha/portfolio#5 but when I'm using preset for the deployment on the edge, prerendering just fails with error 500:
![example](https://github.com/nuxt/image/assets/43365376/87f14fa7-753e-49cc-b137-9c2bbf4f22d9)

When removing those pages from prerender array in config it works but ofc that's not really a workaround
After switching to standard build (no preset) it deploys correctly now

NOTE: locally even with preset it seems to work fine, this issue happens only on vercel platform it seeems

**Comment by Joepocalyptic** [comment]
I'm experiencing this same problem, but with the `netlify_edge` preset. It also occurs both locally and on the Netlify platform. Using the base `netlify` preset eliminates this problem.

**Comment by hi-reeve** [comment]
+1 for this, the same error when prerender page using nuxt-img

**Comment by Lexpeartha** [comment]
Seems like v1.0 silently fixed this (at least for me). If this isn't the case let me know and I'll re-open the issue
