### ISSUE TITLE
Module doesn't work with nuxt layer images

### ISSUE THREAD

**Issue by dimaTarhan** [nuxt/image#940]
Hi there. Thanks for cool module.
I use "nuxt-layers" with images in public folder. Also, I use default config for "nuxt-image" module for my test. 
Everything is good with main project images, they loaded correct. 

![image](https://github.com/nuxt/image/assets/43604553/7e2c089c-342d-42fa-9b25-1a1b6ccd563d)

As for images from layer, there are problems. I think, this images don't include in build process in time...

![image](https://github.com/nuxt/image/assets/43604553/dc9740b7-6eb2-4766-8c7f-caa3d2138d68)

Could you give me some recommendations about that?

**Comment by oemer-aran** [comment]
I have the same issue. Images in the`/public` folder of a nuxt layer will cause 404 error for any images you want to load with `nuxt-img`.

Let's say Layer 2 extends Layer 1. Layer 1 has a `/public/image.png`. 

Using `nuxt-img `:
```html
<!-- response will be 404 -->
<nuxt-img src="/image.png"/>
```

Using plain html:
```html
<!-- response is 200 -->
<img src="/image.png"/>
```

Basically `@nuxt/image` should account for images from other layers.

**Comment by oemer-aran** [comment]
I fixed it by adding this to the base layer / `layer-1`:
```ts
// layer-1/nuxt.config.ts
import { createResolver } from "@nuxt/kit"
const { resolve } = createResolver(import.meta.url)

export default defineNuxtConfig({
  image: {
    dir: resolve("./public"),
  },
})
```
```ts
// ./layer-2/nuxt.config.ts
export default defineNuxtConfig({
  extends: ["../layer-1"],
})
```

But this approach will make the `/public` folder in the current layer not work then (`layer-2/public`).

**Comment by darthf1** [comment]
@danielroe apologies for pinging you; is there something we can do to fix this? So moving `/public` to layers does not work for the `nuxt-image` component, but works for the regular `<img>` tag. If you can give some pointers I can try a PR.

**Comment by danielroe** [comment]
@darthf1 Here would be my debugging steps:

1. identify it is in dev or build mode or both
2. check what IPX is doing - is it performing a network request to get the image, or getting it from the FS directly?
3. see what path it's trying to resolve if it's from the FS, or try the network request yourself, manually
4. fix the bug

**Comment by Aareksio** [comment]
Attaching reproduction:
https://stackblitz.com/edit/nuxt-image-ph6pdk

**Comment by Baroshem** [comment]
Closing as the issue only affects dev environment.

**Comment by Aareksio** [comment]
I do not recall exactly how, but the issue has been fixed. Or at least does not seem to reproduce using the link above with latest `nuxt/image`.

@Baroshem When has the policy changed to "DX can be broken, we care only about production"? Nuxt approach, if anything, usually seems the complete opposite. Not that I oppose, but your closing comment seems a bit odd.

**Comment by Baroshem** [comment]
It wasnt.  We still care about DX a lot.

I was just going through the old issues in the repo to help clean it and make it easier to work with.

I should probably add more descriptive comment than that but after doing that for the X other issues I was lacking creativity :)
