### ISSUE TITLE
Failed to resolve component: nuxt-img

### ISSUE THREAD

**Issue by goshku** [nuxt/image#943]
Hello,
after installation of nuxt/image and use it with `<nuxt-img src="/images/test-tm.webp" />` i am receiving this error:

![image](https://github.com/nuxt/image/assets/6755277/a7d73fda-d920-4b4b-8e2d-7d78f75a1e8b)

package.json:

![image](https://github.com/nuxt/image/assets/6755277/745b60f1-e669-4aba-b899-0ed1de9c72ab)

nuxt.config.js:

![image](https://github.com/nuxt/image/assets/6755277/a1d1f741-3294-45d6-8416-cbc90b610796)

![image](https://github.com/nuxt/image/assets/6755277/77e16ba9-448c-4e09-8074-1ae2c4c99d55)

Any ideas?

**Comment by danielroe** [comment]
Could you provide a reproduction? 🙏

**Comment by goshku** [comment]
Sure, here you go - https://codesandbox.io/p/sandbox/awesome-dirac-p49z73

In dev terminal.

**Comment by goshku** [comment]
Thanks to @kswedberg from discord for the help. 
Problem was that i am using axios and auth that are for nuxt v2.
