### ISSUE TITLE
Update Cloudimage url pattern

### ISSUE THREAD

**Issue by TiborPL** [nuxt/image#954]
Spent some time figuring out why [Cloudimage](https://www.cloudimage.io/) doesn't work for me.  

Seems the old url pattern is hardcoded which doesn't work with new tokens.

```javascript
// providers/cloudimage.mjs
cdnURL = `https://${token}.cloudimg.io/v7`;
```
Maybe if would be better to provide a `legacy` flag or something similar and add `v7` only if legacy mode is enabled (would be false by default).

**Comment by danielroe** [comment]
PR would be very welcome. Is there any way to tell based on the token?

**Comment by TiborPL** [comment]
I asked scaflex support to confirm, but as far as I can see in the official Vue component as soon as v7 hss been released they [introduced](https://github.com/scaleflex/vue-cloudimage-responsive-plain#type-string-default-v7--optional) the `apiVersion` parameter.
