### ISSUE TITLE
Images not being optimized when deploying to Cloudflare Workers

### ISSUE THREAD

**Issue by BernardoSM** [nuxt/image#980]
Hi guys, I'm trying to optmize the images with the following code:

Component.vue
```html
<nuxt-img
  :src="image"
  :quality="85"
  format="webp"
  width="364"
  height="364"
  alt="Roadmap"
  class="h-full w-full object-cover object-center transition-all group-hover:scale-110"
/>
```

The images are coming from github, so I added image domains:

nuxt.config.ts
```js
image: {
  domains: ["raw.githubusercontent.com"],
},
```

When I test locally it's working 100%, we can see the "_ipx" prefix like image below.

![image](https://github.com/nuxt/image/assets/36281298/cccc134e-fb90-48bf-8b67-e60367314237)

But when I deploy to cloudflare workers as **SSR + nitro preset 'cloudflare'**, images are not being optmized like image below.

![image](https://github.com/nuxt/image/assets/36281298/3933a885-e1bd-4952-97d1-7b38b88aeac7)

What can I do to solve that?

**Comment by danielroe** [comment]
This should be resolved in https://github.com/nuxt/image/pull/878.
